Utopszkij_db: Stream Class Reference
Stream Class Reference
Public Member Functions
__construct ()
_parse_path ($path)
_stream_open ($path, $mode, $options, &$opened_path)
_stream_read ($count)
_stream_write ($data)
_stream_tell ()
_stream_eof ()
_stream_seek ($offset, $whence)
_stream_metadata ($path, $option, $var)
_stream_cast ($cast_as)
_stream_lock ($operation)
_rename ($path_from, $path_to)
_dir_opendir ($path, $options)
_dir_readdir ()
_dir_rewinddir ()
_dir_closedir ()
_mkdir ($path, $mode, $options)
_rmdir ($path, $options)
_stream_flush ()
_stream_stat ()
_unlink ($path)
_url_stat ($path, $flags)
_stream_truncate ($new_size)
_stream_set_option ($option, $arg1, $arg2)
_stream_close ()
__call ($name, $arguments)
Static Public Member Functions
static register ($protocol='sftp')
Public Attributes
$sftp
$path
$mode
$pos
$size
$entries
$eof
$context
$notification
Static Public Attributes
static $instances
Constructor & Destructor Documentation
__construct()
__construct ()
The Constructor
@access public
Member Function Documentation
__call()
__call ($name, $arguments)
__call Magic Method
When you're utilizing an SFTP stream you're not calling the methods in this class directly - PHP is calling them for you. Which kinda begs the question... what methods is PHP calling and what parameters is it passing to them? This function lets you figure that out.
If NET_SFTP_STREAM_LOGGING is defined all calls will be output on the screen and then (regardless of whether or not NET_SFTP_STREAM_LOGGING is enabled) the parameters will be passed through to the appropriate method.
Parameters
string $name
array $arguments
Returns
mixed @access public
_dir_closedir()
_dir_closedir ()
Close directory handle
Returns
bool @access public
_dir_opendir()
_dir_opendir ($path, $options)
Open directory handle
The only $options is "whether or not to enforce safe_mode (0x04)". Since safe mode was deprecated in 5.3 and removed in 5.4 I'm just going to ignore it.
Also, nlist() is the best that this function is realistically going to be able to do. When an SFTP client sends a SSH_FXP_READDIR packet you don't generally get info on just one file but on multiple files. Quoting the SFTP specs:
The SSH_FXP_NAME response has the following format:
uint32     id
uint32     count
repeats count times:
        string     filename
        string     longname
        ATTRS      attrs
Parameters
string $path
int $options
Returns
bool @access public
_dir_readdir()
_dir_readdir ()
Read entry from directory handle
Returns
mixed @access public
_dir_rewinddir()
_dir_rewinddir ()
Rewind directory handle
Returns
bool @access public
_mkdir()
_mkdir ($path, $mode, $options)
Create a directory
Only valid $options is STREAM_MKDIR_RECURSIVE
Parameters
string $path
int $mode
int $options
Returns
bool @access public
_parse_path()
_parse_path ($path)
Path Parser
Extract a path from a URI and actually connect to an SSH server if appropriate
If "notification" is set as a context parameter the message code for successful login is NET_SSH2_MSG_USERAUTH_SUCCESS. For a failed login it's NET_SSH2_MSG_USERAUTH_FAILURE.
Parameters
string $path
Returns
string @access private
Referenced by Stream\_dir_opendir(), Stream\_mkdir(), Stream\_rename(), Stream\_rmdir(), Stream\_stream_metadata(), Stream\_stream_open(), Stream\_unlink(), and Stream\_url_stat().
_rename()
_rename ($path_from, $path_to)
Renames a file or directory
Attempts to rename oldname to newname, moving it between directories if necessary. If newname exists, it will be overwritten. This is a departure from what \phpseclib\Net\SFTP does.
Parameters
string $path_from
string $path_to
Returns
bool @access public
_rmdir()
_rmdir ($path, $options)
Removes a directory
Only valid $options is STREAM_MKDIR_RECURSIVE per http://php.net/streamwrapper.rmdir, however, http://php.net/rmdir does not have a $recursive parameter as mkdir() does so I don't know how STREAM_MKDIR_RECURSIVE is supposed to be set. Also, when I try it out with rmdir() I get 8 as $options. What does 8 correspond to?
Parameters
string $path
int $options
Returns
bool @access public
_stream_cast()
_stream_cast ($cast_as)
Retrieve the underlaying resource
Parameters
int $cast_as
Returns
resource @access public
_stream_close()
_stream_close ()
Close an resource
@access public
_stream_eof()
_stream_eof ()
Tests for end-of-file on a file pointer
In my testing there are four classes functions that normally effect the pointer: fseek, fputs / fwrite, fgets / fread and ftruncate.
Only fgets / fread, however, results in feof() returning true. do fputs($fp, 'aaa') on a blank file and feof() will return false. do fread($fp, 1) and feof() will then return true. do fseek($fp, 10) on ablank file and feof() will return false. do fread($fp, 1) and feof() will then return true.
Returns
bool @access public
_stream_flush()
_stream_flush ()
Flushes the output
See http://php.net/fflush. Always returns true because \phpseclib\Net\SFTP doesn't cache stuff before writing
Returns
bool @access public
_stream_lock()
_stream_lock ($operation)
Advisory file locking
Parameters
int $operation
Returns
bool @access public
_stream_metadata()
_stream_metadata ($path, $option, $var)
Change stream options
Parameters
string $path
int $option
mixed $var
Returns
bool @access public
_stream_open()
_stream_open ($path, $mode, $options, & $opened_path)
Opens file or URL
Parameters
string $path
string $mode
int $options
string $opened_path
Returns
bool @access public
_stream_read()
_stream_read ($count)
Read from stream
Parameters
int $count
Returns
mixed @access public
_stream_seek()
_stream_seek ($offset, $whence)
Seeks to specific location in a stream
Parameters
int $offset
int $whence
Returns
bool @access public
_stream_set_option()
_stream_set_option ($option, $arg1, $arg2)
Change stream options
STREAM_OPTION_WRITE_BUFFER isn't supported for the same reason stream_flush isn't. The other two aren't supported because of limitations in \phpseclib\Net\SFTP.
Parameters
int $option
int $arg1
int $arg2
Returns
bool @access public
_stream_stat()
_stream_stat ()
Retrieve information about a file resource
Returns
mixed @access public
_stream_tell()
_stream_tell ()
Retrieve the current position of a stream
Returns
int @access public
_stream_truncate()
_stream_truncate ($new_size)
Truncate stream
Parameters
int $new_size
Returns
bool @access public
_stream_write()
_stream_write ($data)
Write to stream
Parameters
string $data
Returns
mixed @access public
_unlink()
_unlink ($path)
Delete a file
Parameters
string $path
Returns
bool @access public
_url_stat()
_url_stat ($path, $flags)
Retrieve information about a file
Ignores the STREAM_URL_STAT_QUIET flag because the entirety of \phpseclib\Net\SFTP\Stream is quiet by default might be worthwhile to reconstruct bits 12-16 (ie. the file type) if mode doesn't have them but we'll cross that bridge when and if it's reached
Parameters
string $path
int $flags
Returns
mixed @access public
register()
static register ($protocol = 'sftp') static
Registers this class as a URL wrapper.
Parameters
string $protocol The wrapper name to be registered.
Returns
bool True on success, false otherwise. @access public
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP/Stream.php