Utopszkij_db: SCP Class Reference
SCP Class Reference
Public Member Functions
__construct ($ssh)
put ($remote_file, $data, $mode=self::SOURCE_STRING, $callback=null)
get ($remote_file, $local_file=false)
_send ($data)
_receive ()
_close ()
Public Attributes
const SOURCE_LOCAL_FILE = 1
const SOURCE_STRING = 2
const MODE_SSH1 = 1
const MODE_SSH2 = 2
$ssh
$packet_size
$mode
Constructor & Destructor Documentation
__construct()
__construct ($ssh)
Default Constructor.
Connects to an SSH server
Parameters
\phpseclib\Net\SSH1 | \phpseclib\Net\SSH2 $ssh
Returns
\phpseclib\Net\SCP @access public
Member Function Documentation
_close()
_close ()
Closes the connection to an SSH server
@access private
Referenced by SCP\get(), and SCP\put().
_receive()
_receive ()
Receives a packet from an SSH server
Returns
string @access private
Referenced by SCP\get(), and SCP\put().
_send()
_send ($data)
Sends a packet to an SSH server
Parameters
string $data @access private
Referenced by SCP\get(), and SCP\put().
get()
get ($remote_file, $local_file = false)
Downloads a file from the SCP server.
Returns a string containing the contents of $remote_file if $local_file is left undefined or a boolean false if the operation was unsuccessful. If $local_file is defined, returns true or false depending on the success of the operation
Parameters
string $remote_file
string $local_file
Returns
mixed @access public
put()
put ($remote_file, $data, $mode = self::SOURCE_STRING, $callback = null)
Uploads a file to the SCP server.
By default, \phpseclib\Net\SCP::put() does not read from the local filesystem. $data is dumped directly into $remote_file. So, for example, if you set $data to 'filename.ext' and then do \phpseclib\Net\SCP::get(), you will get a file, twelve bytes long, containing 'filename.ext' as its contents.
Setting $mode to self::SOURCE_LOCAL_FILE will change the above behavior. With self::SOURCE_LOCAL_FILE, $remote_file will contain as many bytes as filename.ext does on your local filesystem. If your filename.ext is 1MB then that is how large $remote_file will be, as well.
Currently, only binary mode is supported. As such, if the line endings need to be adjusted, you will need to take care of that, yourself.
Parameters
string $remote_file
string $data
int $mode
callable $callback
Returns
bool @access public
Member Data Documentation
MODE_SSH1
const MODE_SSH1 = 1
#- #+ @access private
See also
\phpseclib\Net\SCP::_send()
\phpseclib\Net\SCP::_receive() SSH1 is being used.
Referenced by SCP\__construct(), SCP\_close(), SCP\_receive(), and SCP\_send().
MODE_SSH2
const MODE_SSH2 = 2
SSH2 is being used.
Referenced by SCP\__construct(), SCP\_close(), SCP\_receive(), and SCP\_send().
SOURCE_LOCAL_FILE
const SOURCE_LOCAL_FILE = 1
#+ @access public
See also
\phpseclib\Net\SCP::put() Reads data from a local file.
SOURCE_STRING
const SOURCE_STRING = 2
Reads data from a string.
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/Net/SCP.php