Utopszkij_db: Is Class Reference
Is Class Reference
Static Public Member Functions
static pending (PromiseInterface $promise)
static settled (PromiseInterface $promise)
static fulfilled (PromiseInterface $promise)
static rejected (PromiseInterface $promise)
Member Function Documentation
fulfilled()
static fulfilled (PromiseInterface $promise) static
Returns true if a promise is fulfilled.
Returns
bool
pending()
static pending (PromiseInterface $promise) static
Returns true if a promise is pending.
Returns
bool
Referenced by Utils\all(), Utils\task(), FulfilledPromise\then(), and RejectedPromise\then().
rejected()
static rejected (PromiseInterface $promise) static
Returns true if a promise is rejected.
Returns
bool
settled()
static settled (PromiseInterface $promise) static
Returns true if a promise is fulfilled or rejected.
Returns
bool
Referenced by Utils\some().
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/guzzlehttp/promises/src/Is.php