Utopszkij_db: SSH1 Class Reference
SSH1 Class Reference
Public Member Functions
__construct ($host, $port=22, $timeout=10, $cipher=self::CIPHER_3DES)
_connect ()
login ($username, $password='')
setTimeout ($timeout)
exec ($cmd, $block=true)
_initShell ()
write ($cmd)
read ($expect, $mode=self::READ_SIMPLE)
interactiveWrite ($cmd)
interactiveRead ()
disconnect ()
__destruct ()
_disconnect ($msg='Client Quit')
_get_binary_packet ()
_send_binary_packet ($data)
_crc ($data)
_string_shift (&$string, $index=1)
_rsa_crypt ($m, $key)
_define_array ()
getLog ()
_format_log ($message_log, $message_number_log)
_format_log_helper ($matches)
getServerKeyPublicExponent ($raw_output=false)
getServerKeyPublicModulus ($raw_output=false)
getHostKeyPublicExponent ($raw_output=false)
getHostKeyPublicModulus ($raw_output=false)
getSupportedCiphers ($raw_output=false)
getSupportedAuthentications ($raw_output=false)
getServerIdentification ()
_append_log ($protocol_flags, $message)
Public Attributes
const CIPHER_NONE = 0
const CIPHER_IDEA = 1
const CIPHER_DES = 2
const CIPHER_3DES = 3
const CIPHER_BROKEN_TSS = 4
const CIPHER_RC4 = 5
const CIPHER_BLOWFISH = 6
const AUTH_RHOSTS = 1
const AUTH_RSA = 2
const AUTH_PASSWORD = 3
const AUTH_RHOSTS_RSA = 4
const TTY_OP_END = 0
const RESPONSE_TYPE = 1
const RESPONSE_DATA = 2
const MASK_CONSTRUCTOR = 0x00000001
const MASK_CONNECTED = 0x00000002
const MASK_LOGIN = 0x00000004
const MASK_SHELL = 0x00000008
const LOG_SIMPLE = 1
const LOG_COMPLEX = 2
const LOG_REALTIME = 3
const LOG_REALTIME_FILE = 4
const READ_SIMPLE = 1
const READ_REGEX = 2
$identifier = 'SSH-1.5-phpseclib'
$fsock
$crypto = false
$bitmap = 0
$server_key_public_exponent
$server_key_public_modulus
$host_key_public_exponent
$host_key_public_modulus
$supported_ciphers
$supported_authentications
$server_identification = ''
$protocol_flags = array()
$protocol_flag_log = array()
$message_log = array()
$realtime_log_file
$realtime_log_size
$realtime_log_wrap
$interactiveBuffer = ''
$timeout
$curTimeout
$log_boundary = ':'
$log_long_width = 65
$log_short_width = 16
$host
$port
$connectionTimeout
$cipher
Constructor & Destructor Documentation
__construct()
__construct ($host, $port = 22, $timeout = 10, $cipher = self::CIPHER_3DES)
Default Constructor.
Connects to an SSHv1 server
Parameters
string $host
int $port
int $timeout
int $cipher
Returns
\phpseclib\Net\SSH1 @access public
__destruct()
__destruct ()
Destructor.
Will be called, automatically, if you're supporting just PHP5. If you're supporting PHP4, you'll need to call disconnect().
@access public
Member Function Documentation
_append_log()
_append_log ($protocol_flags, $message)
Logs data packets
Makes sure that only the last 1MB worth of packets will be logged
Parameters
int $protocol_flags
string $message @access private
Referenced by SSH1\_connect(), SSH1\_get_binary_packet(), and SSH1\_send_binary_packet().
_connect()
_connect ()
Connect to an SSHv1 server
Returns
bool @access private
Referenced by SSH1\login().
_crc()
_crc ($data)
Cyclic Redundancy Check (CRC)
PHP's crc32 function is implemented slightly differently than the one that SSH v1 uses, so we've reimplemented it. A more detailed discussion of the differences can be found after $crc_lookup_table's initialization.
See also
self::_get_binary_packet()
self::_send_binary_packet()
Parameters
string $data
Returns
int @access private
Referenced by SSH1\_send_binary_packet().
_define_array()
_define_array ()
Define Array
Takes any number of arrays whose indices are integers and whose values are strings and defines a bunch of named constants from it, using the value as the name of the constant and the index as the value of the constant. If any of the constants that would be defined already exists, none of the constants will be defined.
@access private
Referenced by SSH1\__construct().
_disconnect()
_disconnect ($msg = 'Client Quit')
Disconnect
Parameters
string $msg @access private
Referenced by SSH1\__destruct(), and SSH1\disconnect().
_format_log()
_format_log ($message_log, $message_number_log)
Formats a log for printing
Parameters
array $message_log
array $message_number_log @access private
Returns
string
Referenced by SSH1\_append_log(), and SSH1\getLog().
_format_log_helper()
_format_log_helper ($matches)
Helper function for _format_log
For use with preg_replace_callback()
Parameters
array $matches @access private
Returns
string
_get_binary_packet()
_get_binary_packet ()
Gets Binary Packets
See 'The Binary Packet Protocol' of protocol-1.5.txt for more info.
Also, this function could be improved upon by adding detection for the following exploit: http://www.securiteam.com/securitynews/5LP042K3FY.html
See also
self::_send_binary_packet()
Returns
array @access private
Referenced by SSH1\_connect(), SSH1\_initShell(), SSH1\exec(), SSH1\interactiveRead(), SSH1\login(), and SSH1\read().
_initShell()
_initShell ()
Creates an interactive shell
See also
self::interactiveRead()
self::interactiveWrite()
Returns
bool @access private
Referenced by SSH1\interactiveRead(), SSH1\interactiveWrite(), and SSH1\read().
_rsa_crypt()
_rsa_crypt ($m, $key)
RSA Encrypt
Returns mod(pow($m, $e), $n), where $n should be the product of two (large) primes $p and $q and where $e should be a number with the property that gcd($e, ($p - 1) * ($q - 1)) == 1. Could just make anything that calls this call modexp, instead, but I think this makes things clearer, maybe...
See also
self::__construct()
Parameters
BigInteger $m
array $key
Returns
BigInteger @access private
Referenced by SSH1\_connect().
_send_binary_packet()
_send_binary_packet ($data)
Sends Binary Packets
Returns true on success, false on failure.
See also
self::_get_binary_packet()
Parameters
string $data
Returns
bool @access private
Referenced by SSH1\_connect(), SSH1\_disconnect(), SSH1\_initShell(), SSH1\exec(), SSH1\interactiveWrite(), and SSH1\login().
_string_shift()
_string_shift (& $string, $index = 1)
String Shift
Inspired by array_shift
Parameters
string $string
int $index
Returns
string @access private
Referenced by SSH1\_append_log(), SSH1\_connect(), SSH1\_format_log(), and SSH1\read().
disconnect()
disconnect ()
Disconnect
@access public
exec()
exec ($cmd, $block = true)
Executes a command on a non-interactive shell, returns the output, and quits.
An SSH1 server will close the connection after a command has been executed on a non-interactive shell. SSH2 servers don't, however, this isn't an SSH2 client. The way this works, on the server, is by initiating a shell with the -s option, as discussed in the following links:
http://www.faqs.org/docs/bashman/bashref_65.html http://www.faqs.org/docs/bashman/bashref_62.html
To execute further commands, a new \phpseclib\Net\SSH1 object will need to be created.
Returns false on failure and the output, otherwise.
See also
self::interactiveRead()
self::interactiveWrite()
Parameters
string $cmd
bool $block
Returns
mixed @access public
getHostKeyPublicExponent()
getHostKeyPublicExponent ($raw_output = false)
Return the host key public exponent
Returns, by default, the base-10 representation. If $raw_output is set to true, returns, instead, the raw bytes. This behavior is similar to PHP's md5() function.
Parameters
bool $raw_output
Returns
string @access public
getHostKeyPublicModulus()
getHostKeyPublicModulus ($raw_output = false)
Return the host key public modulus
Returns, by default, the base-10 representation. If $raw_output is set to true, returns, instead, the raw bytes. This behavior is similar to PHP's md5() function.
Parameters
bool $raw_output
Returns
string @access public
getLog()
getLog ()
Returns a log of the packets that have been sent and received.
Returns a string if NET_SSH1_LOGGING == self::LOG_COMPLEX, an array if NET_SSH1_LOGGING == self::LOG_SIMPLE and false if !defined('NET_SSH1_LOGGING')
@access public
Returns
array|false|string
getServerIdentification()
getServerIdentification ()
Return the server identification.
Returns
string @access public
getServerKeyPublicExponent()
getServerKeyPublicExponent ($raw_output = false)
Return the server key public exponent
Returns, by default, the base-10 representation. If $raw_output is set to true, returns, instead, the raw bytes. This behavior is similar to PHP's md5() function.
Parameters
bool $raw_output
Returns
string @access public
getServerKeyPublicModulus()
getServerKeyPublicModulus ($raw_output = false)
Return the server key public modulus
Returns, by default, the base-10 representation. If $raw_output is set to true, returns, instead, the raw bytes. This behavior is similar to PHP's md5() function.
Parameters
bool $raw_output
Returns
string @access public
getSupportedAuthentications()
getSupportedAuthentications ($raw_output = false)
Return a list of authentications supported by SSH1 server.
Just because a cipher is supported by an SSH1 server doesn't mean it's supported by this library. If $raw_output is set to true, returns, instead, an array of constants. ie. instead of array('password authentication'), you'll get array(self::AUTH_PASSWORD).
Parameters
bool $raw_output
Returns
array @access public
getSupportedCiphers()
getSupportedCiphers ($raw_output = false)
Return a list of ciphers supported by SSH1 server.
Just because a cipher is supported by an SSH1 server doesn't mean it's supported by this library. If $raw_output is set to true, returns, instead, an array of constants. ie. instead of array('Triple-DES in CBC mode'), you'll get array(self::CIPHER_3DES).
Parameters
bool $raw_output
Returns
array @access public
interactiveRead()
interactiveRead ()
Returns the output of an interactive shell when no more output is available.
Requires PHP 4.3.0 or later due to the use of the stream_select() function. If you see stuff like "^[[00m", you're seeing ANSI escape codes. According to How to Enable ANSI.SYS in a Command Window, "Windows NT does not support ANSI escape sequences in Win32 Console applications", so if you're a Windows user, there's not going to be much recourse.
See also
self::interactiveRead()
Returns
string @access public
interactiveWrite()
interactiveWrite ($cmd)
Inputs a command into an interactive shell.
See also
self::interactiveRead()
Parameters
string $cmd
Returns
bool @access public
Referenced by SSH1\write().
login()
login ($username, $password = '')
Login
Parameters
string $username
string $password
Returns
bool @access public
read()
read ($expect, $mode = self::READ_SIMPLE)
Returns the output of an interactive shell when there's a match for $expect
$expect can take the form of a string literal or, if $mode == self::READ_REGEX, a regular expression.
See also
self::write()
Parameters
string $expect
int $mode
Returns
bool @access public
setTimeout()
setTimeout ($timeout)
Set Timeout
$ssh->exec('ping 127.0.0.1'); on a Linux host will never return and will run indefinitely. setTimeout() makes it so it'll timeout. Setting $timeout to false or 0 will mean there is no timeout.
Parameters
mixed $timeout
write()
write ($cmd)
Inputs a command into an interactive shell.
See also
self::interactiveWrite()
Parameters
string $cmd
Returns
bool @access public
Member Data Documentation
$curTimeout
$curTimeout
Current Timeout
See also
self::_get_channel_packet() @access private
$log_boundary
$log_boundary = ':'
Log Boundary
See also
self::_format_log() @access private
$log_long_width
$log_long_width = 65
Log Long Width
See also
self::_format_log() @access private
$log_short_width
$log_short_width = 16
Log Short Width
See also
self::_format_log() @access private
$supported_authentications
$supported_authentications
Initial value:
= array(
        self::AUTH_RHOSTS     => '.rhosts or /etc/hosts.equiv',
        self::AUTH_RSA        => 'pure RSA authentication',
        self::AUTH_PASSWORD   => 'password authentication',
        self::AUTH_RHOSTS_RSA => '.rhosts with RSA host authentication'
    )
$supported_ciphers
$supported_ciphers
Initial value:
= array(
        self::CIPHER_NONE       => 'No encryption',
        self::CIPHER_IDEA       => 'IDEA in CFB mode',
        self::CIPHER_DES        => 'DES in CBC mode',
        self::CIPHER_3DES       => 'Triple-DES in CBC mode',
        self::CIPHER_BROKEN_TSS => 'TRI\'s Simple Stream encryption CBC',
        self::CIPHER_RC4        => 'RC4',
        self::CIPHER_BLOWFISH   => 'Blowfish'
    )
$timeout
$timeout
Timeout
See also
self::setTimeout() @access private
Referenced by SSH1\__construct(), and SSH1\setTimeout().
AUTH_PASSWORD
const AUTH_PASSWORD = 3
password authentication
This is the only method that is supported by this library.
AUTH_RHOSTS
const AUTH_RHOSTS = 1
#- #+ Authentication Methods
See also
\phpseclib\Net\SSH1::getSupportedAuthentications() @access public .rhosts or /etc/hosts.equiv
AUTH_RHOSTS_RSA
const AUTH_RHOSTS_RSA = 4
.rhosts with RSA host authentication
AUTH_RSA
const AUTH_RSA = 2
pure RSA authentication
CIPHER_3DES
const CIPHER_3DES = 3
Triple-DES in CBC mode
All implementations are required to support this
Referenced by SSH1\_connect().
CIPHER_BLOWFISH
const CIPHER_BLOWFISH = 6
Blowfish
Not supported nor is it defined in the official SSH1 specs. OpenSSH, however, defines it (see cipher.h) and uses it (see cipher.c)
CIPHER_BROKEN_TSS
const CIPHER_BROKEN_TSS = 4
TRI's Simple Stream encryption CBC
Not supported nor is it defined in the official SSH1 specs. OpenSSH, however, does define it (see cipher.h), although it doesn't use it (see cipher.c)
CIPHER_DES
const CIPHER_DES = 2
DES in CBC mode
Referenced by SSH1\_connect().
CIPHER_IDEA
const CIPHER_IDEA = 1
IDEA in CFB mode
Not supported.
CIPHER_NONE
const CIPHER_NONE = 0
#+ Encryption Methods
See also
\phpseclib\Net\SSH1::getSupportedCiphers() @access public No encryption
Not supported.
CIPHER_RC4
const CIPHER_RC4 = 5
RC4
Not supported.
LOG_COMPLEX
const LOG_COMPLEX = 2
Returns the message content
Referenced by SSH1\_append_log(), and SSH1\getLog().
LOG_REALTIME
const LOG_REALTIME = 3
Outputs the content real-time
Referenced by SSH1\_append_log().
LOG_REALTIME_FILE
const LOG_REALTIME_FILE = 4
Dumps the content real-time to a file
Referenced by SSH1\_append_log().
LOG_SIMPLE
const LOG_SIMPLE = 1
#- #+ @access public
See also
\phpseclib\Net\SSH1::getLog() Returns the message numbers
Referenced by SSH1\_append_log(), and SSH1\getLog().
MASK_CONSTRUCTOR
const MASK_CONSTRUCTOR = 0x00000001
#+ Execution Bitmap Masks
See also
\phpseclib\Net\SSH1::bitmap @access private
Referenced by SSH1\login().
READ_REGEX
const READ_REGEX = 2
Returns when a string matching the regular expression $expect is found
READ_SIMPLE
const READ_SIMPLE = 1
#- #+ @access public
See also
\phpseclib\Net\SSH1::read() Returns when a string matching $expect exactly is found
RESPONSE_DATA
const RESPONSE_DATA = 2
The Response Data
See also
\phpseclib\Net\SSH1::_get_binary_packet() @access private
Referenced by SCP\_receive().
RESPONSE_TYPE
const RESPONSE_TYPE = 1
#- The Response Type
See also
\phpseclib\Net\SSH1::_get_binary_packet() @access private
Referenced by SCP\_receive().
TTY_OP_END
const TTY_OP_END = 0
#- #+ Terminal Modes
private
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/Net/SSH1.php