Utopszkij_db: Hash Class Reference
Hash Class Reference
Public Member Functions
__construct ($hash='sha1')
setKey ($key=false)
_computeKey ()
getHash ()
setHash ($hash)
hash ($text)
getLength ()
_md5 ($m)
_sha1 ($m)
_md2 ($m)
_sha256 ($m)
_sha512 ($m)
_rightRotate ($int, $amt)
_rightShift ($int, $amt)
_not ($int)
_add ()
_string_shift (&$string, $index=1)
Public Attributes
const MODE_INTERNAL = 1
const MODE_MHASH = 2
const MODE_HASH = 3
$hashParam
$b
$l = false
$hash
$key = false
$computedKey = false
$opad
$ipad
$engine
Constructor & Destructor Documentation
__construct()
__construct ($hash = 'sha1')
Default Constructor.
Parameters
string $hash
Returns
\phpseclib\Crypt\Hash @access public
Member Function Documentation
_add()
_add ()
Add
_sha256() adds multiple unsigned 32-bit integers. Since PHP doesn't support unsigned integers and since the possibility of overflow exists, care has to be taken. BigInteger could be used but this should be faster.
Returns
int
See also
self::_sha256() @access private
Referenced by Hash\_sha256().
_computeKey()
_computeKey ()
Pre-compute the key used by the HMAC
Quoting http://tools.ietf.org/html/rfc2104#section-2, "Applications that use keys longer than B bytes will first hash the key using H and then use the resultant L byte string as the actual key to HMAC."
As documented in https://www.reddit.com/r/PHP/comments/9nct2l/symfonypolyfill_hash_pbkdf2_correct_fix_for/ when doing an HMAC multiple times it's faster to compute the hash once instead of computing it during every call
@access private
Referenced by Hash\setHash(), and Hash\setKey().
_md2()
_md2 ($m)
Pure-PHP implementation of MD2
See RFC1319.
@access private
Parameters
string $m
_md5()
_md5 ($m)
Wrapper for MD5
@access private
Parameters
string $m
_not()
_not ($int)
Not
@access private
Parameters
int $int
See also
self::_sha256()
Returns
int
Referenced by Hash\_sha256().
_rightRotate()
_rightRotate ($int, $amt)
Right Rotate
@access private
Parameters
int $int
int $amt
See also
self::_sha256()
Returns
int
Referenced by Hash\_sha256().
_rightShift()
_rightShift ($int, $amt)
Right Shift
@access private
Parameters
int $int
int $amt
See also
self::_sha256()
Returns
int
Referenced by Hash\_sha256().
_sha1()
_sha1 ($m)
Wrapper for SHA1
@access private
Parameters
string $m
_sha256()
_sha256 ($m)
Pure-PHP implementation of SHA256
See SHA-256 (a SHA-2 variant) pseudocode - Wikipedia.
@access private
Parameters
string $m
_sha512()
_sha512 ($m)
Pure-PHP implementation of SHA384 and SHA512
@access private
Parameters
string $m
_string_shift()
_string_shift (& $string, $index = 1)
String Shift
Inspired by array_shift
Parameters
string $string
int $index
Returns
string @access private
Referenced by Hash\_sha256(), and Hash\_sha512().
getHash()
getHash ()
Gets the hash function.
As set by the constructor or by the setHash() method.
@access public
Returns
string
getLength()
getLength ()
Returns the hash length (in bytes)
@access public
Returns
int
hash()
hash ($text)
Compute the HMAC.
@access public
Parameters
string $text
Returns
string
Referenced by Hash\_computeKey(), Hash\hash(), and Hash\setHash().
setHash()
setHash ($hash)
Sets the hash function.
@access public
Parameters
string $hash
Referenced by Hash\__construct().
setKey()
setKey ($key = false)
Sets the key for HMACs
Keys can be of any length.
@access public
Parameters
string $key
Member Data Documentation
MODE_HASH
const MODE_HASH = 3
Toggles the hash() implementation, which works on PHP 5.1.2+.
Referenced by Hash\_computeKey(), Hash\hash(), and Hash\setHash().
MODE_INTERNAL
const MODE_INTERNAL = 1
#+ @access private
See also
\phpseclib\Crypt\Hash::__construct() Toggles the internal implementation
Referenced by Hash\_computeKey(), Hash\hash(), and Hash\setHash().
MODE_MHASH
const MODE_MHASH = 2
Toggles the mhash() implementation, which has been deprecated on PHP 5.3.0+.
Referenced by Hash\_computeKey(), Hash\hash(), and Hash\setHash().
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/Crypt/Hash.php