Utopszkij_db: Base Class Reference
Base Class Reference
Public Member Functions
__construct ($mode=self::MODE_CBC)
setIV ($iv)
setKeyLength ($length)
getKeyLength ()
getBlockLength ()
setKey ($key)
setPassword ($password, $method='pbkdf2')
encrypt ($plaintext)
decrypt ($ciphertext)
_openssl_ctr_process ($plaintext, &$encryptIV, &$buffer)
_openssl_ofb_process ($plaintext, &$encryptIV, &$buffer)
_openssl_translate_mode ()
enablePadding ()
disablePadding ()
enableContinuousBuffer ()
disableContinuousBuffer ()
isValidEngine ($engine)
setPreferredEngine ($engine)
getEngine ()
_setEngine ()
_encryptBlock ($in)
_decryptBlock ($in)
_setupKey ()
_setup ()
_setupMcrypt ()
_pad ($text)
_unpad ($text)
_clearBuffers ()
_string_shift (&$string, $index=1)
_string_pop (&$string, $index=1)
_increment_str (&$var)
_setupInlineCrypt ()
_createInlineCryptFunction ($cipher_code)
& _getLambdaFunctions ()
_hashInlineCryptFunction ($bytes)
safe_intval ($x)
safe_intval_inline ()
do_nothing ()
Public Attributes
const MODE_CTR = -1
const MODE_ECB = 1
const MODE_CBC = 2
const MODE_CFB = 3
const MODE_CFB8 = 6
const MODE_OFB8 = 7
const MODE_OFB = 4
const MODE_STREAM = 5
const ENGINE_INTERNAL = 1
const ENGINE_MCRYPT = 2
const ENGINE_OPENSSL = 3
$mode
$block_size = 16
$key = "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
$iv = ''
$encryptIV
$decryptIV
$continuousBuffer = false
$enbuffer
$debuffer
$enmcrypt
$demcrypt
$enchanged = true
$dechanged = true
$ecb
$cfb_init_len = 600
$changed = true
$padding = true
$paddable = false
$engine
$preferredEngine
$cipher_name_mcrypt
$cipher_name_openssl
$cipher_name_openssl_ecb
$password_default_salt = 'phpseclib/salt'
$inline_crypt
$use_inline_crypt = true
$openssl_emulate_ctr = false
$openssl_options
$explicit_key_length = false
$skip_key_adjustment = false
Static Public Attributes
static $WHIRLPOOL_AVAILABLE
Constructor & Destructor Documentation
__construct()
__construct ($mode = self::MODE_CBC)
Default Constructor.
Determines whether or not the mcrypt extension should be used.
$mode could be:
self::MODE_ECB
self::MODE_CBC
self::MODE_CTR
self::MODE_CFB
self::MODE_OFB
If not explicitly set, self::MODE_CBC will be used.
Parameters
int $mode @access public
Reimplemented in TripleDES.
Member Function Documentation
_clearBuffers()
_clearBuffers ()
Clears internal buffers
Clearing/resetting the internal buffers is done everytime after disableContinuousBuffer() or on cipher $engine (re)init ie after setKey() or setIV()
@access public
Referenced by Base\_setup(), Base\_setupMcrypt(), Base\decrypt(), and Base\encrypt().
_createInlineCryptFunction()
_createInlineCryptFunction ($cipher_code)
Creates the performance-optimized function for en/decrypt()
Internally for phpseclib developers:
_createInlineCryptFunction():
merge the $cipher_code [setup'ed by _setupInlineCrypt()] with the current [$this->]mode of operation code
create the $inline function, which called by encrypt() / decrypt() as its replacement to speed up the en/decryption operations.
return the name of the created $inline callback function
used to speed up en/decryption
The main reason why can speed up things [up to 50%] this way are:
using variables more effective then regular. (ie no use of expensive arrays but integers $k_0, $k_1 ... or even, for example, the pure $key[] values hardcoded)
avoiding 1000's of function calls of ie _encryptBlock() but inlining the crypt operations. in the mode of operation for() loop.
full loop unroll the (sometimes key-dependent) rounds avoiding this way ++$i counters and runtime-if's etc...
The basic code architectur of the generated $inline en/decrypt() lambda function, in pseudo php, is:
+-------------------------------------------------------------------------------------------—+ | callback $inline = create_function: | | lambda_function_0001_crypt_ECB($action, $text) | | { | | INSERT PHP CODE OF: | | $cipher_code['init_crypt']; // general init code. | | // ie: $sbox'es declarations used for |
// encrypt and decrypt'ing.
switch ($action) {
case 'encrypt':
INSERT PHP CODE OF:
$cipher_code['init_encrypt']; // encrypt sepcific init code.
ie: specified $key or $box
declarations for encrypt'ing.
foreach ($ciphertext) {
$in = $block_size of $ciphertext;
INSERT PHP CODE OF:
$cipher_code['encrypt_block']; // encrypt's (string) $in, which is always:
// strlen($in) == $this->block_size
// here comes the cipher algorithm in action
// for encryption.
// $cipher_code['encrypt_block'] has to
// encrypt the content of the $in variable
$plaintext .= $in;
}
return $plaintext;
case 'decrypt':
INSERT PHP CODE OF:
$cipher_code['init_decrypt']; // decrypt sepcific init code
ie: specified $key or $box
declarations for decrypt'ing.
foreach ($plaintext) {
$in = $block_size of $plaintext;
INSERT PHP CODE OF:
$cipher_code['decrypt_block']; // decrypt's (string) $in, which is always
// strlen($in) == $this->block_size
// here comes the cipher algorithm in action
// for decryption.
// $cipher_code['decrypt_block'] has to
// decrypt the content of the $in variable
$ciphertext .= $in;
}
return $ciphertext;
}
}
+-------------------------------------------------------------------------------------------—+
See also the \phpseclib\Crypt*::_setupInlineCrypt()'s for productive inline $cipher_code's how they works.
Structure of: $cipher_code = array('init_crypt' => (string) '', // optional 'init_encrypt' => (string) '', // optional 'init_decrypt' => (string) '', // optional 'encrypt_block' => (string) '', // required 'decrypt_block' => (string) '' // required);
See also
self::_setupInlineCrypt()
self::encrypt()
self::decrypt()
Parameters
array $cipher_code @access private
Returns
string (the name of the created callback function)
Referenced by Blowfish\_setupInlineCrypt(), DES\_setupInlineCrypt(), RC2\_setupInlineCrypt(), Rijndael\_setupInlineCrypt(), and Twofish\_setupInlineCrypt().
_decryptBlock()
_decryptBlock ($in) abstract
Decrypts a block
Note: Must be extended by the child \phpseclib\Crypt* class
@access private
Parameters
string $in
Returns
string
Reimplemented in Blowfish, DES, RC2, RC4, Rijndael, and Twofish.
Referenced by Base\decrypt().
_encryptBlock()
_encryptBlock ($in) abstract
Encrypts a block
Note: Must be extended by the child \phpseclib\Crypt* class
@access private
Parameters
string $in
Returns
string
Reimplemented in Blowfish, DES, RC2, RC4, Rijndael, and Twofish.
Referenced by Base\decrypt(), and Base\encrypt().
_getLambdaFunctions()
& _getLambdaFunctions ()
Holds the lambda_functions table (classwide)
Each name of the lambda function, created from _setupInlineCrypt() && _createInlineCryptFunction() is stored, classwide (!), here for reusing.
The string-based index of $function is a classwide unique value representing, at least, the $mode of operation (or more... depends of the optimizing level) for which $mode the lambda function was created.
@access private
Returns
array &$functions
Referenced by Blowfish\_setupInlineCrypt(), DES\_setupInlineCrypt(), RC2\_setupInlineCrypt(), Rijndael\_setupInlineCrypt(), and Twofish\_setupInlineCrypt().
_hashInlineCryptFunction()
_hashInlineCryptFunction ($bytes)
Generates a digest from $bytes
See also
self::_setupInlineCrypt() @access private
Parameters
string $bytes
Returns
string
Referenced by Blowfish\_setupInlineCrypt(), DES\_setupInlineCrypt(), RC2\_setupInlineCrypt(), Rijndael\_setupInlineCrypt(), and Twofish\_setupInlineCrypt().
_increment_str()
_increment_str (& $var)
Increment the current string
See also
self::decrypt()
self::encrypt()
Parameters
string $var @access private
Referenced by Base\_openssl_ctr_process(), Base\decrypt(), and Base\encrypt().
_openssl_ctr_process()
_openssl_ctr_process ($plaintext, & $encryptIV, & $buffer)
OpenSSL CTR Processor
PHP's OpenSSL bindings do not operate in continuous mode so we'll wrap around it. Since the keystream for CTR is the same for both encrypting and decrypting this function is re-used by both Base::encrypt() and Base::decrypt(). Also, OpenSSL doesn't implement CTR for all of it's symmetric ciphers so this function will emulate CTR with ECB when necessary.
See also
self::encrypt()
self::decrypt()
Parameters
string $plaintext
string $encryptIV
array $buffer
Returns
string @access private
Referenced by Base\decrypt(), and Base\encrypt().
_openssl_ofb_process()
_openssl_ofb_process ($plaintext, & $encryptIV, & $buffer)
OpenSSL OFB Processor
PHP's OpenSSL bindings do not operate in continuous mode so we'll wrap around it. Since the keystream for OFB is the same for both encrypting and decrypting this function is re-used by both Base::encrypt() and Base::decrypt().
See also
self::encrypt()
self::decrypt()
Parameters
string $plaintext
string $encryptIV
array $buffer
Returns
string @access private
Referenced by Base\decrypt(), and Base\encrypt().
_openssl_translate_mode()
_openssl_translate_mode ()
phpseclib <-> OpenSSL Mode Mapper
May need to be overwritten by classes extending this one in some cases
Returns
int @access private
Referenced by Blowfish\isValidEngine(), DES\isValidEngine(), RC2\isValidEngine(), Rijndael\isValidEngine(), and TripleDES\isValidEngine().
_pad()
_pad ($text)
Pads a string
Pads a string using the RSA PKCS padding standards so that its length is a multiple of the blocksize. $this->block_size - (strlen($text) % $this->block_size) bytes are added, each of which is equal to chr($this->block_size - (strlen($text) % $this->block_size)
If padding is disabled and $text is not a multiple of the blocksize, the string will be padded regardless and padding will, hence forth, be enabled.
See also
self::_unpad()
Parameters
string $text @access private
Returns
string
Referenced by Base\encrypt(), and TripleDES\encrypt().
_setEngine()
_setEngine ()
Sets the engine as appropriate
See also
self::__construct() @access private
Referenced by Base\__construct(), Base\disableContinuousBuffer(), Base\enableContinuousBuffer(), Rijndael\setBlockLength(), AES\setKey(), Base\setKey(), Base\setKeyLength(), and Base\setPreferredEngine().
_setup()
_setup ()
Setup the self::ENGINE_INTERNAL $engine
(re)init, if necessary, the internal cipher $engine and flush all $buffers Used (only) if $engine == self::ENGINE_INTERNAL
_setup() will be called each time if $changed === true typically this happens when using one or more of following public methods:
setKey()
setIV()
disableContinuousBuffer()
First run of encrypt() / decrypt() with no init-settings
See also
self::setKey()
self::setIV()
self::disableContinuousBuffer() @access private
Referenced by RC4\_crypt(), Base\decrypt(), and Base\encrypt().
_setupInlineCrypt()
_setupInlineCrypt ()
Setup the performance-optimized function for de/encrypt()
Stores the created (or existing) callback function-name in $this->inline_crypt
Internally for phpseclib developers:
_setupInlineCrypt() would be called only if:
- $engine == self::ENGINE_INTERNAL and
- $use_inline_crypt === true
- each time on _setup(), after(!) _setupKey()
This ensures that _setupInlineCrypt() has always a
full ready2go initializated internal cipher $engine state
where, for example, the keys allready expanded,
keys/block_size calculated and such.
It is, each time if called, the responsibility of _setupInlineCrypt():
- to set $this->inline_crypt to a valid and fully working callback function
  as a (faster) replacement for encrypt() / decrypt()
- NOT to create unlimited callback functions (for memory reasons!)
  no matter how often _setupInlineCrypt() would be called. At some
  point of amount they must be generic re-useable.
- the code of _setupInlineCrypt() it self,
  and the generated callback code,
  must be, in following order:
  - 100% safe
  - 100% compatible to encrypt()/decrypt()
  - using only php5+ features/lang-constructs/php-extensions if
    compatibility (down to php4) or fallback is provided
  - readable/maintainable/understandable/commented and... not-cryptic-styled-code :-)
  - >= 10% faster than encrypt()/decrypt() [which is, by the way,
    the reason for the existence of _setupInlineCrypt() :-)]
  - memory-nice
  - short (as good as possible)
Note: - _setupInlineCrypt() is using _createInlineCryptFunction() to create the full callback function code.
In case of using inline crypting, _setupInlineCrypt() must extend by the child \phpseclib\Crypt* class.
The following variable names are reserved:
$_* (all variable names prefixed with an underscore)
$self (object reference to it self. Do not use $this, but $self instead)
$in (the content of $in has to en/decrypt by the generated code)
The callback function should not use the 'return' statement, but en/decrypt'ing the content of $in only
See also
self::_setup()
self::_createInlineCryptFunction()
self::encrypt()
self::decrypt() @access private
Reimplemented in Blowfish, DES, RC2, Rijndael, and Twofish.
Referenced by Base\_setup().
_setupKey()
_setupKey () abstract
Setup the key (expansion)
Only used if $engine == self::ENGINE_INTERNAL
Note: Must extend by the child \phpseclib\Crypt* class
See also
self::_setup() @access private
Reimplemented in Blowfish, DES, RC2, RC4, Rijndael, TripleDES, and Twofish.
Referenced by Base\_setup().
_setupMcrypt()
_setupMcrypt ()
Setup the self::ENGINE_MCRYPT $engine
(re)init, if necessary, the (ext)mcrypt resources and flush all $buffers Used (only) if $engine = self::ENGINE_MCRYPT
_setupMcrypt() will be called each time if $changed === true typically this happens when using one or more of following public methods:
setKey()
setIV()
disableContinuousBuffer()
First run of encrypt() / decrypt()
See also
self::setKey()
self::setIV()
self::disableContinuousBuffer() @access private
Reimplemented in RC2.
Referenced by Base\decrypt(), and Base\encrypt().
_string_pop()
_string_pop (& $string, $index = 1)
String Pop
Inspired by array_pop
Parameters
string $string
int $index @access private
Returns
string
Referenced by Base\_openssl_ctr_process(), Base\_openssl_ofb_process(), and Base\encrypt().
_string_shift()
_string_shift (& $string, $index = 1)
String Shift
Inspired by array_shift
Parameters
string $string
int $index @access private
Returns
string
Referenced by Base\_openssl_ctr_process(), Base\_openssl_ofb_process(), Base\decrypt(), and Base\encrypt().
_unpad()
_unpad ($text)
Unpads a string.
If padding is enabled and the reported padding length is invalid the encryption key will be assumed to be wrong and false will be returned.
See also
self::_pad()
Parameters
string $text @access private
Returns
string
Referenced by Base\decrypt(), and TripleDES\decrypt().
decrypt()
decrypt ($ciphertext)
Decrypts a message.
If strlen($ciphertext) is not a multiple of the block size, null bytes will be added to the end of the string until it is.
See also
self::encrypt() @access public
Parameters
string $ciphertext
Returns
string $plaintext
Reimplemented in RC2, RC4, and TripleDES.
disableContinuousBuffer()
disableContinuousBuffer ()
Treat consecutive packets as if they are a discontinuous buffer.
The default behavior.
See also
self::enableContinuousBuffer() @access public
Reimplemented in TripleDES.
disablePadding()
disablePadding ()
Do not pad packets.
See also
self::enablePadding() @access public
do_nothing()
do_nothing ()
Dummy error handler to suppress mcrypt errors
@access private
enableContinuousBuffer()
enableContinuousBuffer ()
Treat consecutive "packets" as if they are a continuous buffer.
Say you have a 32-byte plaintext $plaintext. Using the default behavior, the two following code snippets will yield different outputs:
echo $rijndael->encrypt(substr($plaintext, 0, 16)); echo $rijndael->encrypt(substr($plaintext, 16, 16)); echo $rijndael->encrypt($plaintext);
The solution is to enable the continuous buffer. Although this will resolve the above discrepancy, it creates another, as demonstrated with the following:
$rijndael->encrypt(substr($plaintext, 0, 16)); echo $rijndael->decrypt($rijndael->encrypt(substr($plaintext, 16, 16))); echo $rijndael->decrypt($rijndael->encrypt(substr($plaintext, 16, 16)));
With the continuous buffer disabled, these would yield the same output. With it enabled, they yield different outputs. The reason is due to the fact that the initialization vector's change after every encryption / decryption round when the continuous buffer is enabled. When it's disabled, they remain constant.
Put another way, when the continuous buffer is enabled, the state of the \phpseclib\Crypt*() object changes after each encryption / decryption round, whereas otherwise, it'd remain constant. For this reason, it's recommended that continuous buffers not be used. They do offer better security and are, in fact, sometimes required (SSH uses them), however, they are also less intuitive and more likely to cause you problems.
See also
self::disableContinuousBuffer() @access public
Reimplemented in TripleDES.
enablePadding()
enablePadding ()
Pad "packets".
Block ciphers working by encrypting between their specified [$this->]block_size at a time If you ever need to encrypt or decrypt something that isn't of the proper length, it becomes necessary to pad the input so that it is of the proper length.
Padding is enabled by default. Sometimes, however, it is undesirable to pad strings. Such is the case in SSH, where "packets" are padded with random bytes before being encrypted. Unpad these packets and you risk stripping away characters that shouldn't be stripped away. (SSH knows how many bytes are added because the length is transmitted separately)
See also
self::disablePadding() @access public
encrypt()
encrypt ($plaintext)
Encrypts a message.
$plaintext will be padded with additional bytes such that it's length is a multiple of the block size. Other cipher implementations may or may not pad in the same manner. Other common approaches to padding and the reasons why it's necessary are discussed in the following URL:
http://www.di-mgt.com.au/cryptopad.html
An alternative to padding is to, separately, send the length of the file. This is what SSH, in fact, does. strlen($plaintext) will still need to be a multiple of the block size, however, arbitrary values can be added to make it that length.
See also
self::decrypt() @access public
Parameters
string $plaintext
Returns
string $ciphertext
Reimplemented in RC2, RC4, and TripleDES.
getBlockLength()
getBlockLength ()
Returns the current block length in bits
@access public
Returns
int
getEngine()
getEngine ()
Returns the engine currently being utilized
See also
self::_setEngine() @access public
getKeyLength()
getKeyLength ()
Returns the current key length in bits
@access public
Returns
int
Reimplemented in RC2.
isValidEngine()
isValidEngine ($engine)
Test for engine validity
See also
self::__construct()
Parameters
int $engine @access public
Returns
bool
Reimplemented in Blowfish, DES, RC2, RC4, Rijndael, and TripleDES.
Referenced by Base\_setEngine().
safe_intval()
safe_intval ($x)
Convert float to int
On ARM CPUs converting floats to ints doesn't always work
@access private
Parameters
string $x
Returns
int
Referenced by Blowfish\_decryptBlock(), Twofish\_decryptBlock(), Blowfish\_encryptBlock(), Twofish\_encryptBlock(), and Twofish\_setupKey().
safe_intval_inline()
safe_intval_inline ()
eval()'able string for in-line float to int
@access private
Returns
string
Referenced by Blowfish\_setupInlineCrypt(), and Twofish\_setupInlineCrypt().
setIV()
setIV ($iv)
Sets the initialization vector. (optional)
SetIV is not required when self::MODE_ECB (or ie for AES: \phpseclib\Crypt\AES::MODE_ECB) is being used. If not explicitly set, it'll be assumed to be all zero's.
@access public
Parameters
string $iv
Reimplemented in RC4, and TripleDES.
Referenced by Base\setPassword().
setKey()
setKey ($key)
Sets the key.
The min/max length(s) of the key depends on the cipher which is used. If the key not fits the length(s) of the cipher it will paded with null bytes up to the closest valid key length. If the key is more than max length, we trim the excess bits.
If the key is not explicitly set, it'll be assumed to be all null bytes.
@access public
Parameters
string $key
Reimplemented in AES, DES, and TripleDES.
Referenced by Base\setPassword().
setKeyLength()
setKeyLength ($length)
Sets the key length.
Keys with explicitly set lengths need to be treated accordingly
@access public
Parameters
int $length
Reimplemented in AES, Blowfish, RC2, RC4, Rijndael, TripleDES, and Twofish.
Referenced by Base\setKey().
setPassword()
setPassword ($password, $method = 'pbkdf2')
Sets the password.
Depending on what $method is set to, setPassword()'s (optional) parameters are as follows: pbkdf2 or pbkdf1: $hash, $salt, $count, $dkLen
Where $hash (default = sha1) currently supports the following hashes: see: Crypt/Hash.php
See also
Crypt/Hash.php
Parameters
string $password
string $method
Returns
bool @access public
setPreferredEngine()
setPreferredEngine ($engine)
Sets the preferred crypt engine
Currently, $engine could be:
\phpseclib\Crypt\Base::ENGINE_OPENSSL [very fast]
\phpseclib\Crypt\Base::ENGINE_MCRYPT [fast]
\phpseclib\Crypt\Base::ENGINE_INTERNAL [slow]
If the preferred crypt engine is not available the fastest available one will be used
See also
self::__construct()
Parameters
int $engine @access public
Reimplemented in TripleDES.
Member Data Documentation
ENGINE_INTERNAL
const ENGINE_INTERNAL = 1
#+ @access private
See also
\phpseclib\Crypt\Base::__construct() Base value for the internal implementation $engine switch
Referenced by Base\_setEngine(), RC4\decrypt(), RC4\encrypt(), SSH2\getSupportedEncryptionAlgorithms(), Base\isValidEngine(), and Base\setPreferredEngine().
ENGINE_MCRYPT
const ENGINE_MCRYPT = 2
Base value for the mcrypt implementation $engine switch
Referenced by SSH2\getSupportedEncryptionAlgorithms(), Base\isValidEngine(), Rijndael\isValidEngine(), and Base\setPreferredEngine().
ENGINE_OPENSSL
const ENGINE_OPENSSL = 3
Base value for the mcrypt implementation $engine switch
Referenced by SSH2\getSupportedEncryptionAlgorithms(), Base\isValidEngine(), RC2\isValidEngine(), RC4\isValidEngine(), Rijndael\isValidEngine(), and Base\setPreferredEngine().
MODE_CBC
const MODE_CBC = 2
Encrypt / decrypt using the Code Book Chaining mode.
http://en.wikipedia.org/wiki/Block_cipher_modes_of_operation#Cipher-block_chaining_.28CBC.29
Referenced by TripleDES\__construct(), Base\__construct(), Base\_openssl_translate_mode(), Base\decrypt(), and Base\encrypt().
MODE_CFB
const MODE_CFB = 3
Encrypt / decrypt using the Cipher Feedback mode.
http://en.wikipedia.org/wiki/Block_cipher_modes_of_operation#Cipher_feedback_.28CFB.29
Referenced by Base\__construct(), Base\_createInlineCryptFunction(), Base\_openssl_translate_mode(), RSA\_parseKey(), Base\decrypt(), and Base\encrypt().
MODE_CFB8
const MODE_CFB8 = 6
Encrypt / decrypt using the Cipher Feedback mode (8bit)
Referenced by Base\__construct(), Base\_createInlineCryptFunction(), Base\_openssl_translate_mode(), Base\decrypt(), and Base\encrypt().
MODE_CTR
const MODE_CTR = -1
#+ @access public
See also
\phpseclib\Crypt\Base::encrypt()
\phpseclib\Crypt\Base::decrypt() Encrypt / decrypt using the Counter mode.
Set to -1 since that's what Crypt/Random.php uses to index the CTR mode.
http://en.wikipedia.org/wiki/Block_cipher_modes_of_operation#Counter_.28CTR.29
Referenced by Base\__construct(), Base\_createInlineCryptFunction(), SSH2\_encryption_algorithm_to_crypt_instance(), Base\_openssl_translate_mode(), Base\decrypt(), Base\encrypt(), Base\isValidEngine(), and Random\string().
MODE_ECB
const MODE_ECB = 1
Encrypt / decrypt using the Electronic Code Book mode.
http://en.wikipedia.org/wiki/Block_cipher_modes_of_operation#Electronic_codebook_.28ECB.29
Referenced by Base\__construct(), Base\_createInlineCryptFunction(), Base\_openssl_translate_mode(), Base\decrypt(), and Base\encrypt().
MODE_OFB
const MODE_OFB = 4
Encrypt / decrypt using the Output Feedback mode.
http://en.wikipedia.org/wiki/Block_cipher_modes_of_operation#Output_feedback_.28OFB.29
Referenced by Base\__construct(), Base\_createInlineCryptFunction(), Base\_openssl_translate_mode(), Base\decrypt(), and Base\encrypt().
MODE_OFB8
const MODE_OFB8 = 7
Encrypt / decrypt using the Output Feedback mode (8bit)
Referenced by Base\__construct(), Base\_createInlineCryptFunction(), Base\decrypt(), and Base\encrypt().
MODE_STREAM
const MODE_STREAM = 5
Encrypt / decrypt using streaming mode.
Referenced by Base\__construct(), RC4\__construct(), Base\_createInlineCryptFunction(), Base\decrypt(), and Base\encrypt().
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php