Utopszkij_db: ASN1 Class Reference
ASN1 Class Reference
Public Member Functions
decodeBER ($encoded)
_decode_ber ($encoded, $start=0, $encoded_pos=0)
asn1map ($decoded, $mapping, $special=array())
encodeDER ($source, $mapping, $special=array())
_encode_der ($source, $mapping, $idx=null, $special=array())
_encodeLength ($length)
_decodeOID ($content)
_encodeOID ($source)
_decodeTime ($content, $tag)
setTimeFormat ($format)
loadOIDs ($oids)
loadFilters ($filters)
_string_shift (&$string, $index=1)
convert ($in, $from=self::TYPE_UTF8_STRING, $to=self::TYPE_UTF8_STRING)
Public Attributes
const CLASS_UNIVERSAL = 0
const CLASS_APPLICATION = 1
const CLASS_CONTEXT_SPECIFIC = 2
const CLASS_PRIVATE = 3
const TYPE_BOOLEAN = 1
const TYPE_INTEGER = 2
const TYPE_BIT_STRING = 3
const TYPE_OCTET_STRING = 4
const TYPE_NULL = 5
const TYPE_OBJECT_IDENTIFIER = 6
const TYPE_REAL = 9
const TYPE_ENUMERATED = 10
const TYPE_UTF8_STRING = 12
const TYPE_SEQUENCE = 16
const TYPE_SET = 17
const TYPE_NUMERIC_STRING = 18
const TYPE_PRINTABLE_STRING = 19
const TYPE_TELETEX_STRING = 20
const TYPE_VIDEOTEX_STRING = 21
const TYPE_IA5_STRING = 22
const TYPE_UTC_TIME = 23
const TYPE_GENERALIZED_TIME = 24
const TYPE_GRAPHIC_STRING = 25
const TYPE_VISIBLE_STRING = 26
const TYPE_GENERAL_STRING = 27
const TYPE_UNIVERSAL_STRING = 28
const TYPE_BMP_STRING = 30
const TYPE_CHOICE = -1
const TYPE_ANY = -2
$oids = array()
$format = 'D, d M Y H:i:s O'
$encoded
$filters
$ANYmap
$stringTypeSize
Member Function Documentation
_decode_ber()
_decode_ber ($encoded, $start = 0, $encoded_pos = 0)
Parse BER-encoding (Helper function)
Sometimes we want to get the BER encoding of a particular tag. $start lets us do that without having to reencode. $encoded is passed by reference for the recursive calls done for self::TYPE_BIT_STRING and self::TYPE_OCTET_STRING. In those cases, the indefinite length is used.
Parameters
string $encoded
int $start
int $encoded_pos
Returns
array @access private
Referenced by ASN1\_decode_ber(), and ASN1\decodeBER().
_decodeOID()
_decodeOID ($content)
BER-decode the OID
Called by _decode_ber()
@access private
Parameters
string $content
Returns
string
Referenced by ASN1\_decode_ber().
_decodeTime()
_decodeTime ($content, $tag)
BER-decode the time
Called by _decode_ber() and in the case of implicit tags asn1map().
@access private
Parameters
string $content
int $tag
Returns
string
Referenced by ASN1\_decode_ber(), and ASN1\asn1map().
_encode_der()
_encode_der ($source, $mapping, $idx = null, $special = array())
ASN.1 Encode (Helper function)
Parameters
string $source
string $mapping
int $idx
array $special
Returns
string @access private
Referenced by ASN1\_encode_der(), and ASN1\encodeDER().
_encodeLength()
_encodeLength ($length)
DER-encode the length
DER supports lengths up to (2**8)**127, however, we'll only support lengths up to (2**8)**4. See X.690 paragraph 8.1.3 for more information.
@access private
Parameters
int $length
Returns
string
Referenced by ASN1\_encode_der().
_encodeOID()
_encodeOID ($source)
DER-encode the OID
Called by _encode_der()
@access private
Parameters
string $source
Returns
string
Referenced by ASN1\_encode_der().
_string_shift()
_string_shift (& $string, $index = 1)
String Shift
Inspired by array_shift
Parameters
string $string
int $index
Returns
string @access private
asn1map()
asn1map ($decoded, $mapping, $special = array())
ASN.1 Map
Provides an ASN.1 semantic mapping ($mapping) from a parsed BER-encoding to a human readable format.
"Special" mappings may be applied on a per tag-name basis via $special.
Parameters
array $decoded
array $mapping
array $special
Returns
array @access public
Referenced by ASN1\asn1map().
convert()
convert ($in, $from = self::TYPE_UTF8_STRING, $to = self::TYPE_UTF8_STRING)
String type conversion
This is a lazy conversion, dealing only with character size. No real conversion table is used.
Parameters
string $in
int $from
int $to
Returns
string @access public
decodeBER()
decodeBER ($encoded)
Parse BER-encoding
Serves a similar purpose to openssl's asn1parse
Parameters
string $encoded
Returns
array @access public
encodeDER()
encodeDER ($source, $mapping, $special = array())
ASN.1 Encode
DER-encodes an ASN.1 semantic mapping ($mapping). Some libraries would probably call this function an ASN.1 compiler.
"Special" mappings can be applied via $special.
Parameters
string $source
string $mapping
array $special
Returns
string @access public
loadFilters()
loadFilters ($filters)
Load filters
See \phpseclib\File\X509, etc, for an example.
@access public
Parameters
array $filters
loadOIDs()
loadOIDs ($oids)
Load OIDs
Load the relevant OIDs for a particular ASN.1 semantic mapping.
@access public
Parameters
array $oids
setTimeFormat()
setTimeFormat ($format)
Set the time format
Sets the time / date format for asn1map().
@access public
Parameters
string $format
Member Data Documentation
$ANYmap
$ANYmap
Initial value:
= array(
        self::TYPE_BOOLEAN              => true,
        self::TYPE_INTEGER              => true,
        self::TYPE_BIT_STRING           => 'bitString',
        self::TYPE_OCTET_STRING         => 'octetString',
        self::TYPE_NULL                 => 'null',
        self::TYPE_OBJECT_IDENTIFIER    => 'objectIdentifier',
        self::TYPE_REAL                 => true,
        self::TYPE_ENUMERATED           => 'enumerated',
        self::TYPE_UTF8_STRING          => 'utf8String',
        self::TYPE_NUMERIC_STRING       => 'numericString',
        self::TYPE_PRINTABLE_STRING     => 'printableString',
        self::TYPE_TELETEX_STRING       => 'teletexString',
        self::TYPE_VIDEOTEX_STRING      => 'videotexString',
        self::TYPE_IA5_STRING           => 'ia5String',
        self::TYPE_UTC_TIME             => 'utcTime',
        self::TYPE_GENERALIZED_TIME     => 'generalTime',
        self::TYPE_GRAPHIC_STRING       => 'graphicString',
        self::TYPE_VISIBLE_STRING       => 'visibleString',
        self::TYPE_GENERAL_STRING       => 'generalString',
        self::TYPE_UNIVERSAL_STRING     => 'universalString',
        self::TYPE_BMP_STRING           => 'bmpString'
    )
$stringTypeSize
$stringTypeSize
Initial value:
= array(
        self::TYPE_UTF8_STRING      => 0,
        self::TYPE_BMP_STRING       => 2,
        self::TYPE_UNIVERSAL_STRING => 4,
        self::TYPE_PRINTABLE_STRING => 1,
        self::TYPE_TELETEX_STRING   => 1,
        self::TYPE_IA5_STRING       => 1,
        self::TYPE_VISIBLE_STRING   => 1,
    )
CLASS_UNIVERSAL
const CLASS_UNIVERSAL = 0
#+ Tag Classes
@access private http://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf#page=12
Referenced by ASN1\asn1map().
TYPE_BOOLEAN
const TYPE_BOOLEAN = 1
#- #+ Tag Classes
@access private http://www.obj-sys.com/asn1tutorial/node124.html
Referenced by X509\__construct(), ASN1\_decode_ber(), ASN1\_encode_der(), and ASN1\asn1map().
TYPE_CHOICE
const TYPE_CHOICE = -1
#- #+ Tag Aliases
These tags are kinda place holders for other tags.
@access private
Referenced by X509\__construct(), ASN1\_encode_der(), and ASN1\asn1map().
TYPE_NUMERIC_STRING
const TYPE_NUMERIC_STRING = 18
#- #+ More Tag Classes
@access private http://www.obj-sys.com/asn1tutorial/node10.html
Referenced by X509\__construct(), ASN1\_decode_ber(), ASN1\_encode_der(), and ASN1\asn1map().
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/File/ASN1.php