Utopszkij_db: Ethabi Class Reference
Ethabi Class Reference
Public Member Functions
__construct ($types=[])
__get ($name)
__set ($name, $value)
encodeFunctionSignature ($functionName)
encodeEventSignature ($functionName)
encodeParameter ($type, $param)
encodeParameters ($types, $params)
decodeParameter ($type, $param)
decodeParameters ($types, $param)
Static Public Member Functions
static __callStatic ($name, $arguments)
Protected Member Functions
getSolidityTypes ($types)
encodeWithOffset ($type, $solidityType, $encoded, $offset)
encodeMultiWithOffset ($types, $solidityTypes, $encodes, $dynamicOffset)
Protected Attributes
$types = []
Constructor & Destructor Documentation
__construct()
__construct ($types = [])
construct
Parameters
array $types
Returns
void
Member Function Documentation
__callStatic()
static __callStatic ($name, $arguments) static
callStatic
Parameters
string $name
array $arguments
Returns
void
__get()
__get ($name)
get
Parameters
string $name
Returns
mixed
__set()
__set ($name, $value)
set
Parameters
string $name
mixed $value
Returns
mixed
decodeParameter()
decodeParameter ($type, $param)
decodeParameter
Parameters
string $type
mixed $param
Returns
string
decodeParameters()
decodeParameters ($types, $param)
decodeParameters
Parameters
stdClass | array $type
string $param
Returns
string
Referenced by Ethabi\decodeParameter().
encodeEventSignature()
encodeEventSignature ($functionName)
encodeEventSignature TODO: Fix same event name with different params
Parameters
string | stdClass | array $functionName
Returns
string
encodeFunctionSignature()
encodeFunctionSignature ($functionName)
encodeFunctionSignature
Parameters
string | stdClass | array $functionName
Returns
string
encodeMultiWithOffset()
encodeMultiWithOffset ($types, $solidityTypes, $encodes, $dynamicOffset) protected
encodeMultiWithOffset
Parameters
array $types
array $solidityTypes
array $encodes
int $dynamicOffset
Returns
string
Referenced by Ethabi\encodeParameters().
encodeParameter()
encodeParameter ($type, $param)
encodeParameter
Parameters
string $type
mixed $param
Returns
string
encodeParameters()
encodeParameters ($types, $params)
encodeParameters
Parameters
stdClass | array $types
array $params
Returns
string
Referenced by Ethabi\encodeParameter().
encodeWithOffset()
encodeWithOffset ($type, $solidityType, $encoded, $offset) protected
encodeWithOffset
Parameters
string $type
\Web3\Contracts\SolidityType $solidityType
mixed $encode
int $offset
Returns
string
Referenced by Ethabi\encodeMultiWithOffset(), and Ethabi\encodeWithOffset().
getSolidityTypes()
getSolidityTypes ($types) protected
getSolidityTypes
Parameters
array $types
Returns
array
Referenced by Ethabi\decodeParameters(), and Ethabi\encodeParameters().
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/web3p/web3.php/src/Contracts/Ethabi.php