Utopszkij_db: Collection Class Reference
Collection Class Reference
Public Member Functions
__construct (string $collectionName)
hun (string $a)
create (array $indexNames)
insert (Document $document)
createIndex (string $indexName)
dropIndex (string $indexName)
updateById (string $id, Document $document)
deleteById (string $id)
getById (string $id)
getByFilter (string $indexFieldName, string $minValue, string $maxValue)
buildResultRow ($rec, string $prefix='')
offset (int $offset)
limit (int $limit)
where ($fieldName, $rel, $value)
orWhere ($fieldName, $rel, $value)
select (array $fieldNames)
all (string $prefix='')
Public Member Functions inherited from Where
whereClear ()
Public Attributes
string $collectionName
string $error
Public Attributes inherited from Where
$expression
Protected Member Functions
delIndexItem ($indexRoot, $value, $data)
Protected Member Functions inherited from Where
conditionsCheck ($conditions, $rec)
whereCheck ($rec)
addWhere (string $fieldName, string $rel, mixed $value)
addOrWhere (string $fieldName, string $rel, mixed $value)
Protected Attributes
$header
$dataRoot
$indexes
int $offset
int $limit
array $select
string $alias
Constructor & Destructor Documentation
__construct()
__construct (string $collectionName)
Ha már létezik a tábla nyilvántartásban akkor beolvassa onnan
Parameters
string $source név
string $alias
Member Function Documentation
all()
all (string $prefix = '')
dokumentumok olvasása a bállított were, select, orderBy, offset, limit paraméterek alapján
Parameters
string $prefix az outputban a mező nevek elé kerül
Returns
array [Document, Document,...]
buildResultRow()
buildResultRow ($rec, string $prefix = '')
document array -ból a select alapján document objectet alakít ki.
Parameters
object $rec
string $prefix a resultban az oszlopnevek elé kerül
Returns
Document
create()
create (array $indexNames)
CollectionRoot létrehozása a storage -ban
Parameters
array $indexNames ['fieldname',...]
createIndex()
createIndex (string $indexName)
Új index hozzáadása meglévő kollekcióhoz ha már sok dokumentum van akkor hosszú ideig is eltarthat és sok memóriát igényelhet!
Parameters
string $indexName
deleteById()
deleteById (string $id)
Document (logikai) törlése
Parameters
string $id
Returns
bool
delIndexItem()
delIndexItem ($indexRoot, $value, $data) protected
index item logikai törlése
dropIndex()
dropIndex (string $indexName)
index törlése valójában a további indexelést és az index szerinti keresést állítja le, a storage -ban megmaradnak az eddigi index adatok, de a továbbiakban nem lesznek használva.
Parameters
string $indexName
getByFilter()
getByFilter (string $indexFieldName, string $minValue, string $maxValue)
dokumentumok olvasása ha a megadott indexFieldname -hez nincs index az id szerinti soros keresés
Parameters
string $indexFieldName haszálandó index
string $minValue min.value az indexen
string $maxValue max.value az indexen lehet 'none' is
function(array $rec): bool filterFun
Returns
array [{fieldname:value,...},...]
getById()
getById (string $id)
Document elérés id alapján
Parameters
string $id
Returns
object $document , ha nincs ilyen akkor {}
hun()
hun (string $a)
string kodolás magyar ABC szerinti indexeléshez egyenlőre idő és gas kimélésből belenyugszunk, hogy az index szerinti keresés nem nagyar ABC sorrendet hoz ki, a Query sortBy oldja ezt meg
insert()
insert (Document $document)
Új document kiirása
Parameters
array $document
Returns
string Új ID
limit()
limit (int $limit)
Limit deiniálás
Parameters
int $limit
Returns
Table
Referenced by __construct().
offset()
offset (int $offset)
Offset deiniálás
Parameters
int $offset
Returns
Collection
Referenced by __construct().
orWhere()
orWhere ($fieldName, $rel, $value)
or-al kapcsolt where csoprt kezdése hozzáadása
Parameters
string $fieldName
string $rel '<'|'<=','=','<>','>','>='
$value '‘filedName’ is lehet
select()
select (array $fieldNames)
select definiálása
Parameters
array $fieldnames ['fieldName'...., ['SUM','fieldname'],....]
Referenced by __construct().
updateById()
updateById (string $id, Document $document)
Document modosítása
Parameters
string $id
array $document
Returns
bool
where()
where ($fieldName, $rel, $value)
és -el összekapcsolt where feltétel hozzáadása az aktuális csoporthoz
Parameters
string $fieldName
string $rel '<'|'<=','=','<>','>','>='
$value '‘filedName’ is lehet
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/collection.php