Utopszkij_db: Utils Class Reference
Utils Class Reference
Static Public Member Functions
static queue (TaskQueueInterface $assign=null)
static task (callable $task)
static inspect (PromiseInterface $promise)
static inspectAll ($promises)
static unwrap ($promises)
static all ($promises, $recursive=false)
static some ($count, $promises)
static any ($promises)
static settle ($promises)
Member Function Documentation
all()
static all ($promises, $recursive = false) static
Given an array of promises, return a promise that is fulfilled when all the items in the array are fulfilled.
The promise's fulfillment value is an array with fulfillment values at respective positions to the original array. If any promise in the array rejects, the returned promise is rejected with the rejection reason.
Parameters
mixed $promises Promises or values.
bool $recursive If true, resolves new promises that might have been added to the stack during its own resolution.
Returns
PromiseInterface
Referenced by Utils\all().
any()
static any ($promises) static
Like some(), with 1 as count. However, if the promise fulfills, the fulfillment value is not an array of 1 but the value directly.
Parameters
mixed $promises Promises or values.
Returns
PromiseInterface
inspect()
static inspect (PromiseInterface $promise) static
Synchronously waits on a promise to resolve and returns an inspection state array.
Returns a state associative array containing a "state" key mapping to a valid promise state. If the state of the promise is "fulfilled", the array will contain a "value" key mapping to the fulfilled value of the promise. If the promise is rejected, the array will contain a "reason" key mapping to the rejection reason of the promise.
Parameters
PromiseInterface $promise Promise or value.
Returns
array
Referenced by Utils\inspectAll().
inspectAll()
static inspectAll ($promises) static
Waits on all of the provided promises, but does not unwrap rejected promises as thrown exception.
Returns an array of inspection state arrays.
See also
inspect for the inspection state array format.
Parameters
PromiseInterface[] $promises Traversable of promises to wait upon.
Returns
array
queue()
static queue (TaskQueueInterface $assign = null) static
Get the global task queue used for promise resolution.
This task queue MUST be run in an event loop in order for promises to be settled asynchronously. It will be automatically run when synchronously waiting on a promise.
while ($eventLoop->isRunning()) { GuzzleHttp\Promise\Utils::queue()->run(); }
Parameters
TaskQueueInterface $assign Optionally specify a new queue instance.
Returns
TaskQueueInterface
Referenced by CurlMultiHandler\execute(), Utils\task(), FulfilledPromise\then(), RejectedPromise\then(), and CurlMultiHandler\tick().
settle()
static settle ($promises) static
Returns a promise that is fulfilled when all of the provided promises have been fulfilled or rejected.
The returned promise is fulfilled with an array of inspection state arrays.
See also
inspect for the inspection state array format.
Parameters
mixed $promises Promises or values.
Returns
PromiseInterface
some()
static some ($count, $promises) static
Initiate a competitive race between multiple promises or values (values will become immediately fulfilled promises).
When count amount of promises have been fulfilled, the returned promise is fulfilled with an array that contains the fulfillment values of the winners in order of resolution.
This promise is rejected with a {
See also
AggregateException} if the number of fulfilled promises is less than the desired $count.
Parameters
int $count Total number of promises.
mixed $promises Promises or values.
Returns
PromiseInterface
Referenced by Utils\any().
task()
static task (callable $task) static
Adds a function to run in the task queue when it is next run() and returns a promise that is fulfilled or rejected with the result.
Parameters
callable $task Task function to run.
Returns
PromiseInterface
unwrap()
static unwrap ($promises) static
Waits on all of the provided promises and returns the fulfilled values.
Returns an array that contains the value of each promise (in the same order the promises were provided). An exception is thrown if any of the promises are rejected.
Parameters
iterable<PromiseInterface> $promises Iterable of PromiseInterface objects to wait on.
Returns
array
Exceptions
Exception on error
Exceptions
Throwable on error in PHP >=7
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/guzzlehttp/promises/src/Utils.php