Utopszkij_db: TripleDES Class Reference
TripleDES Class Reference
Public Member Functions
__construct ($mode=Base::MODE_CBC)
isValidEngine ($engine)
setIV ($iv)
setKeyLength ($length)
setKey ($key)
encrypt ($plaintext)
decrypt ($ciphertext)
enableContinuousBuffer ()
disableContinuousBuffer ()
_setupKey ()
setPreferredEngine ($engine)
Public Member Functions inherited from DES
isValidEngine ($engine)
setKey ($key)
_encryptBlock ($in)
_decryptBlock ($in)
_processBlock ($block, $mode)
_setupKey ()
_setupInlineCrypt ()
Public Member Functions inherited from Base
__construct ($mode=self::MODE_CBC)
setIV ($iv)
setKeyLength ($length)
getKeyLength ()
getBlockLength ()
setKey ($key)
setPassword ($password, $method='pbkdf2')
encrypt ($plaintext)
decrypt ($ciphertext)
_openssl_ctr_process ($plaintext, &$encryptIV, &$buffer)
_openssl_ofb_process ($plaintext, &$encryptIV, &$buffer)
_openssl_translate_mode ()
enablePadding ()
disablePadding ()
enableContinuousBuffer ()
disableContinuousBuffer ()
isValidEngine ($engine)
setPreferredEngine ($engine)
getEngine ()
_setEngine ()
_encryptBlock ($in)
_decryptBlock ($in)
_setupKey ()
_setup ()
_setupMcrypt ()
_pad ($text)
_unpad ($text)
_clearBuffers ()
_string_shift (&$string, $index=1)
_string_pop (&$string, $index=1)
_increment_str (&$var)
_setupInlineCrypt ()
_createInlineCryptFunction ($cipher_code)
& _getLambdaFunctions ()
_hashInlineCryptFunction ($bytes)
safe_intval ($x)
safe_intval_inline ()
do_nothing ()
Public Attributes
const MODE_3CBC = -2
const MODE_CBC3 = Base::MODE_CBC
$key_length = 24
$password_default_salt = 'phpseclib'
$cipher_name_mcrypt = 'tripledes'
$cfb_init_len = 750
$key_length_max = 24
$mode_3cbc
$des
Public Attributes inherited from DES
const ENCRYPT = 0
const DECRYPT = 1
$block_size = 8
$key_length = 8
$cipher_name_mcrypt = 'des'
$openssl_mode_names
$cfb_init_len = 500
$des_rounds = 1
$key_length_max = 8
$keys
$shuffle
$ipmap
$invipmap
$sbox1
$sbox2
$sbox3
$sbox4
$sbox5
$sbox6
$sbox7
$sbox8
Public Attributes inherited from Base
const MODE_CTR = -1
const MODE_ECB = 1
const MODE_CBC = 2
const MODE_CFB = 3
const MODE_CFB8 = 6
const MODE_OFB8 = 7
const MODE_OFB = 4
const MODE_STREAM = 5
const ENGINE_INTERNAL = 1
const ENGINE_MCRYPT = 2
const ENGINE_OPENSSL = 3
$mode
$block_size = 16
$key = "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
$iv = ''
$encryptIV
$decryptIV
$continuousBuffer = false
$enbuffer
$debuffer
$enmcrypt
$demcrypt
$enchanged = true
$dechanged = true
$ecb
$cfb_init_len = 600
$changed = true
$padding = true
$paddable = false
$engine
$preferredEngine
$cipher_name_mcrypt
$cipher_name_openssl
$cipher_name_openssl_ecb
$password_default_salt = 'phpseclib/salt'
$inline_crypt
$use_inline_crypt = true
$openssl_emulate_ctr = false
$openssl_options
$explicit_key_length = false
$skip_key_adjustment = false
Additional Inherited Members
Static Public Attributes inherited from Base
static $WHIRLPOOL_AVAILABLE
Constructor & Destructor Documentation
__construct()
__construct ($mode = Base::MODE_CBC)
Default Constructor.
Determines whether or not the mcrypt extension should be used.
$mode could be:
\phpseclib\Crypt\Base::MODE_ECB
\phpseclib\Crypt\Base::MODE_CBC
\phpseclib\Crypt\Base::MODE_CTR
\phpseclib\Crypt\Base::MODE_CFB
\phpseclib\Crypt\Base::MODE_OFB
\phpseclib\Crypt\TripleDES::MODE_3CBC
If not explicitly set, \phpseclib\Crypt\Base::MODE_CBC will be used.
See also
\phpseclib\Crypt\DES::__construct()
\phpseclib\Crypt\Base::__construct()
Parameters
int $mode @access public
Reimplemented from Base.
Member Function Documentation
_setupKey()
_setupKey ()
Creates the key schedule
See also
\phpseclib\Crypt\DES::_setupKey()
\phpseclib\Crypt\Base::_setupKey() @access private
Reimplemented from DES.
decrypt()
decrypt ($ciphertext)
Decrypts a message.
See also
\phpseclib\Crypt\Base::decrypt() @access public
Parameters
string $ciphertext
Returns
string $plaintext
Reimplemented from Base.
Referenced by TripleDES\decrypt(), and TripleDES\encrypt().
disableContinuousBuffer()
disableContinuousBuffer ()
Treat consecutive packets as if they are a discontinuous buffer.
The default behavior.
See also
\phpseclib\Crypt\Base::disableContinuousBuffer()
self::enableContinuousBuffer() @access public
Reimplemented from Base.
enableContinuousBuffer()
enableContinuousBuffer ()
Treat consecutive "packets" as if they are a continuous buffer.
Say you have a 16-byte plaintext $plaintext. Using the default behavior, the two following code snippets will yield different outputs:
echo $des->encrypt(substr($plaintext, 0, 8)); echo $des->encrypt(substr($plaintext, 8, 8)); echo $des->encrypt($plaintext);
The solution is to enable the continuous buffer. Although this will resolve the above discrepancy, it creates another, as demonstrated with the following:
$des->encrypt(substr($plaintext, 0, 8)); echo $des->decrypt($des->encrypt(substr($plaintext, 8, 8))); echo $des->decrypt($des->encrypt(substr($plaintext, 8, 8)));
With the continuous buffer disabled, these would yield the same output. With it enabled, they yield different outputs. The reason is due to the fact that the initialization vector's change after every encryption / decryption round when the continuous buffer is enabled. When it's disabled, they remain constant.
Put another way, when the continuous buffer is enabled, the state of the \phpseclib\Crypt\DES() object changes after each encryption / decryption round, whereas otherwise, it'd remain constant. For this reason, it's recommended that continuous buffers not be used. They do offer better security and are, in fact, sometimes required (SSH uses them), however, they are also less intuitive and more likely to cause you problems.
See also
\phpseclib\Crypt\Base::enableContinuousBuffer()
self::disableContinuousBuffer() @access public
Reimplemented from Base.
encrypt()
encrypt ($plaintext)
Encrypts a message.
See also
\phpseclib\Crypt\Base::encrypt() @access public
Parameters
string $plaintext
Returns
string $cipertext
Reimplemented from Base.
Referenced by TripleDES\decrypt(), and TripleDES\encrypt().
isValidEngine()
isValidEngine ($engine)
Test for engine validity
This is mainly just a wrapper to set things up for \phpseclib\Crypt\Base::isValidEngine()
See also
\phpseclib\Crypt\Base::__construct()
Parameters
int $engine @access public
Returns
bool
Reimplemented from DES.
setIV()
setIV ($iv)
Sets the initialization vector. (optional)
SetIV is not required when \phpseclib\Crypt\Base::MODE_ECB is being used. If not explicitly set, it'll be assumed to be all zero's.
See also
\phpseclib\Crypt\Base::setIV() @access public
Parameters
string $iv
Reimplemented from Base.
setKey()
setKey ($key)
Sets the key.
Keys can be of any length. Triple DES, itself, can use 128-bit (eg. strlen($key) == 16) or 192-bit (eg. strlen($key) == 24) keys. This function pads and truncates $key as appropriate.
DES also requires that every eighth bit be a parity bit, however, we'll ignore that.
If the key is not explicitly set, it'll be assumed to be all null bytes.
@access public
See also
\phpseclib\Crypt\DES::setKey()
\phpseclib\Crypt\Base::setKey()
Parameters
string $key
Reimplemented from DES.
setKeyLength()
setKeyLength ($length)
Sets the key length.
Valid key lengths are 64, 128 and 192
See also
\phpseclib\Crypt\Base:setKeyLength() @access public
Parameters
int $length
Reimplemented from Base.
setPreferredEngine()
setPreferredEngine ($engine)
Sets the internal crypt engine
See also
\phpseclib\Crypt\Base::__construct()
\phpseclib\Crypt\Base::setPreferredEngine()
Parameters
int $engine @access public
Returns
int
Reimplemented from Base.
Member Data Documentation
MODE_3CBC
const MODE_3CBC = -2
Encrypt / decrypt using inner chaining
Inner chaining is used by SSH-1 and is generally considered to be less secure then outer chaining (self::MODE_CBC3).
Referenced by TripleDES\__construct(), and SSH1\_connect().
MODE_CBC3
const MODE_CBC3 = Base::MODE_CBC
Encrypt / decrypt using outer chaining
Outer chaining is used by SSH-2 and when the mode is set to \phpseclib\Crypt\Base::MODE_CBC.
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/Crypt/TripleDES.php