Utopszkij_db: SFTP Class Reference
SFTP Class Reference
Public Member Functions
__construct ($host, $port=22, $timeout=10)
_precheck ()
_partial_init_sftp_connection ()
_init_sftp_connection ()
disableStatCache ()
enableStatCache ()
clearStatCache ()
enablePathCanonicalization ()
disablePathCanonicalization ()
enableArbitraryLengthPackets ()
disableArbitraryLengthPackets ()
pwd ()
_logError ($response, $status=-1)
realpath ($path)
_realpath ($path)
chdir ($dir)
nlist ($dir='.', $recursive=false)
_nlist_helper ($dir, $recursive, $relativeDir)
rawlist ($dir='.', $recursive=false)
_list ($dir, $raw=true)
_comparator ($a, $b)
setListOrder ()
size ($filename)
_update_stat_cache ($path, $value)
_remove_from_stat_cache ($path)
_query_stat_cache ($path)
stat ($filename)
lstat ($filename)
_stat ($filename, $type)
truncate ($filename, $new_size)
touch ($filename, $time=null, $atime=null)
chown ($filename, $uid, $recursive=false)
chgrp ($filename, $gid, $recursive=false)
chmod ($mode, $filename, $recursive=false)
_setstat ($filename, $attr, $recursive)
_setstat_recursive ($path, $attr, &$i)
readlink ($link)
symlink ($target, $link)
mkdir ($dir, $mode=-1, $recursive=false)
_mkdir_helper ($dir, $mode)
rmdir ($dir)
put ($remote_file, $data, $mode=self::SOURCE_STRING, $start=-1, $local_start=-1, $progressCallback=null)
_read_put_responses ($i)
_close_handle ($handle)
get ($remote_file, $local_file=false, $offset=0, $length=-1, $progressCallback=null)
delete ($path, $recursive=true)
_delete_recursive ($path, &$i)
file_exists ($path)
is_dir ($path)
is_file ($path)
is_link ($path)
is_readable ($path)
is_writable ($path)
is_writeable ($path)
fileatime ($path)
filemtime ($path)
fileperms ($path)
fileowner ($path)
filegroup ($path)
filesize ($path)
filetype ($path)
_get_stat_cache_prop ($path, $prop)
_get_lstat_cache_prop ($path, $prop)
_get_xstat_cache_prop ($path, $prop, $type)
rename ($oldname, $newname)
_parseTime ($key, $flags, &$response)
_parseAttributes (&$response)
_parseMode ($mode)
_parseLongname ($longname)
_send_sftp_packet ($type, $data, $request_id=1)
_reset_connection ($reason)
_get_sftp_packet ($request_id=null)
getSFTPLog ()
getSFTPErrors ()
getLastSFTPError ()
getSupportedVersions ()
getNegotiatedVersion ()
setPreferredVersion ($version)
_disconnect ($reason)
enableDatePreservation ()
disableDatePreservation ()
Public Member Functions inherited from SSH2
__construct ($host, $port=22, $timeout=10)
setCryptoEngine ($engine)
sendIdentificationStringFirst ()
sendIdentificationStringLast ()
sendKEXINITFirst ()
sendKEXINITLast ()
_connect ()
_generate_identifier ()
_key_exchange ($kexinit_payload_server=false)
_encryption_algorithm_to_key_size ($algorithm)
_encryption_algorithm_to_crypt_instance ($algorithm)
_bad_algorithm_candidate ($algorithm)
login ($username)
_login ($username)
_login_helper ($username, $password=null)
_keyboard_interactive_login ($username, $password)
_keyboard_interactive_process ()
_ssh_agent_login ($username, $agent)
_privatekey_login ($username, $privatekey)
setTimeout ($timeout)
setKeepAlive ($interval)
getStdError ()
exec ($command, $callback=null)
_initShell ()
_get_interactive_channel ()
_get_open_channel ()
read ($expect='', $mode=self::READ_SIMPLE)
write ($cmd)
startSubsystem ($subsystem)
stopSubsystem ()
reset ()
isTimeout ()
disconnect ()
__destruct ()
isConnected ()
isAuthenticated ()
ping ()
_reconnect ()
_reset_connection ($reason)
_get_binary_packet ($skip_channel_filter=false)
_filter ($payload, $skip_channel_filter)
enableQuietMode ()
disableQuietMode ()
isQuietModeEnabled ()
enablePTY ()
disablePTY ()
isPTYEnabled ()
_get_channel_packet ($client_channel, $skip_extended=false)
_send_binary_packet ($data, $logged=null)
_append_log ($message_number, $message)
_send_channel_packet ($client_channel, $data)
_close_channel ($client_channel, $want_reply=false)
_disconnect ($reason)
_string_shift (&$string, $index=1)
_define_array ()
getLog ()
_format_log ($message_log, $message_number_log)
_format_log_helper ($matches)
_on_channel_open ()
_array_intersect_first ($array1, $array2)
getErrors ()
getLastError ()
getServerIdentification ()
getKexAlgorithms ()
getServerHostKeyAlgorithms ()
getEncryptionAlgorithmsClient2Server ()
getEncryptionAlgorithmsServer2Client ()
getMACAlgorithmsClient2Server ()
getMACAlgorithmsServer2Client ()
getCompressionAlgorithmsClient2Server ()
getCompressionAlgorithmsServer2Client ()
getLanguagesServer2Client ()
getLanguagesClient2Server ()
getServerAlgorithms ()
getSupportedKEXAlgorithms ()
getSupportedHostKeyAlgorithms ()
getSupportedEncryptionAlgorithms ()
getSupportedMACAlgorithms ()
getSupportedCompressionAlgorithms ()
getAlgorithmsNegotiated ()
setPreferredAlgorithms ($methods)
getBannerMessage ()
getServerPublicHostKey ()
getExitStatus ()
getWindowColumns ()
getWindowRows ()
setWindowColumns ($value)
setWindowRows ($value)
setWindowSize ($columns=80, $rows=24)
_updateLogHistory ($old, $new)
getAuthMethodsToContinue ()
enableSmartMFA ()
disableSmartMFA ()
Public Attributes
const CHANNEL = 0x100
const SOURCE_LOCAL_FILE = 1
const SOURCE_STRING = 2
const SOURCE_CALLBACK = 16
const RESUME = 4
const RESUME_START = 8
$packet_types = array()
$status_codes = array()
$use_request_id = false
$packet_type = -1
$packet_buffer = ''
$extensions = array()
$version
$defaultVersion
$preferredVersion = 3
$pwd = false
$packet_type_log = array()
$packet_log = array()
$sftp_errors = array()
$stat_cache = array()
$max_sftp_packet
$use_stat_cache = true
$sortOptions = array()
$canonicalize_paths = true
$requestBuffer = array()
$preserveTime = false
$allow_arbitrary_length_packets = false
$channel_close = false
$partial_init = false
Public Attributes inherited from SSH2
const NET_SSH2_COMPRESSION_NONE = 1
const NET_SSH2_COMPRESSION_ZLIB = 2
const NET_SSH2_COMPRESSION_ZLIB_AT_OPENSSH = 3
const MASK_CONSTRUCTOR = 0x00000001
const MASK_CONNECTED = 0x00000002
const MASK_LOGIN_REQ = 0x00000004
const MASK_LOGIN = 0x00000008
const MASK_SHELL = 0x00000010
const MASK_WINDOW_ADJUST = 0x00000020
const CHANNEL_EXEC = 1
const CHANNEL_SHELL = 2
const CHANNEL_SUBSYSTEM = 3
const CHANNEL_AGENT_FORWARD = 4
const CHANNEL_KEEP_ALIVE = 5
const LOG_SIMPLE = 1
const LOG_COMPLEX = 2
const LOG_REALTIME = 3
const LOG_REALTIME_FILE = 4
const LOG_MAX_SIZE = 1048576
const READ_SIMPLE = 1
const READ_REGEX = 2
const READ_NEXT = 3
$identifier
$fsock
$bitmap = 0
$errors = array()
$server_identifier = false
$kex_algorithms = false
$kex_algorithm = false
$kex_dh_group_size_min = 1536
$kex_dh_group_size_preferred = 2048
$kex_dh_group_size_max = 4096
$server_host_key_algorithms = false
$encryption_algorithms_client_to_server = false
$encryption_algorithms_server_to_client = false
$mac_algorithms_client_to_server = false
$mac_algorithms_server_to_client = false
$compression_algorithms_client_to_server = false
$compression_algorithms_server_to_client = false
$languages_server_to_client = false
$languages_client_to_server = false
$preferred = array()
$encrypt_block_size = 8
$decrypt_block_size = 8
$decrypt = false
$encrypt = false
$hmac_create = false
$hmac_check = false
$hmac_size = false
$server_public_host_key
$session_id = false
$exchange_hash = false
$message_numbers = array()
$disconnect_reasons = array()
$channel_open_failure_reasons = array()
$terminal_modes = array()
$channel_extended_data_type_codes = array()
$send_seq_no = 0
$get_seq_no = 0
$server_channels = array()
$channel_buffers = array()
$channel_status = array()
$packet_size_client_to_server = array()
$message_number_log = array()
$message_log = array()
$window_size = 0x7FFFFFFF
$window_resize = 0x40000000
$window_size_server_to_client = array()
$window_size_client_to_server = array()
$signature = ''
$signature_format = ''
$interactiveBuffer = ''
$log_size
$timeout
$curTimeout
$keepAlive
$realtime_log_file
$realtime_log_size
$signature_validated = false
$realtime_log_wrap
$quiet_mode = false
$last_packet
$exit_status
$request_pty = false
$in_request_pty_exec = false
$in_subsystem
$stdErrorLog
$last_interactive_response = ''
$keyboard_requests_responses = array()
$banner_message = ''
$is_timeout = false
$log_boundary = ':'
$log_long_width = 65
$log_short_width = 16
$host
$port
$windowColumns = 80
$windowRows = 24
$crypto_engine = false
$agent
$send_id_string_first = true
$send_kex_first = true
$bad_key_size_fix = false
$retry_connect = false
$binary_packet_buffer = false
$preferred_signature_format = false
$auth = array()
$auth_methods_to_continue = null
$compress = self::NET_SSH2_COMPRESSION_NONE
$decompress = self::NET_SSH2_COMPRESSION_NONE
$compress_context
$decompress_context
$regenerate_compression_context = false
$regenerate_decompression_context = false
$smartMFA = true
Constructor & Destructor Documentation
__construct()
__construct ($host, $port = 22, $timeout = 10)
Default Constructor.
Connects to an SFTP server
Parameters
string $host
int $port
int $timeout
Returns
\phpseclib\Net\SFTP @access public
Reimplemented from SSH2.
Member Function Documentation
_close_handle()
_close_handle ($handle)
Close handle
Parameters
string $handle
Returns
bool @access private
Referenced by SFTP\_list(), SFTP\chdir(), SFTP\get(), SFTP\put(), and SFTP\touch().
_comparator()
_comparator ($a, $b)
Compares two rawlist entries using parameters set by setListOrder()
Intended for use with uasort()
Parameters
array $a
array $b
Returns
int @access private
_delete_recursive()
_delete_recursive ($path, & $i)
Recursively deletes directories on the SFTP server
Minimizes directory lookups and SSH_FXP_STATUS requests for speed.
Parameters
string $path
int $i
Returns
bool @access private
Referenced by SFTP\_delete_recursive(), and SFTP\delete().
_disconnect()
_disconnect ($reason)
Disconnect
Parameters
int $reason
Returns
bool @access private
Reimplemented from SSH2.
_get_lstat_cache_prop()
_get_lstat_cache_prop ($path, $prop)
Return an lstat properity
Uses cache if appropriate.
Parameters
string $path
string $prop
Returns
mixed @access private
Referenced by SFTP\is_link().
_get_sftp_packet()
_get_sftp_packet ($request_id = null)
Receives SFTP Packets
See '6. General Packet Format' of draft-ietf-secsh-filexfer-13 for more info.
Incidentally, the number of SSH_MSG_CHANNEL_DATA messages has no bearing on the number of SFTP packets present. There can be one SSH_MSG_CHANNEL_DATA messages containing two SFTP packets or there can be two SSH_MSG_CHANNEL_DATA messages containing one SFTP packet.
See also
self::_send_sftp_packet()
Returns
string @access private
Referenced by SFTP\_close_handle(), SFTP\_init_sftp_connection(), SFTP\_list(), SFTP\_mkdir_helper(), SFTP\_partial_init_sftp_connection(), SFTP\_read_put_responses(), SFTP\_realpath(), SFTP\_setstat(), SFTP\_stat(), SFTP\chdir(), SFTP\chmod(), SFTP\delete(), SFTP\get(), SFTP\is_readable(), SFTP\is_writable(), SFTP\put(), SFTP\readlink(), SFTP\rmdir(), SFTP\symlink(), and SFTP\touch().
_get_stat_cache_prop()
_get_stat_cache_prop ($path, $prop)
Return a stat properity
Uses cache if appropriate.
Parameters
string $path
string $prop
Returns
mixed @access private
Referenced by SFTP\fileatime(), SFTP\filegroup(), SFTP\filemtime(), SFTP\fileowner(), SFTP\fileperms(), SFTP\filesize(), SFTP\filetype(), SFTP\is_dir(), and SFTP\is_file().
_get_xstat_cache_prop()
_get_xstat_cache_prop ($path, $prop, $type)
Return a stat or lstat properity
Uses cache if appropriate.
Parameters
string $path
string $prop
mixed $type
Returns
mixed @access private
Referenced by SFTP\_get_lstat_cache_prop(), and SFTP\_get_stat_cache_prop().
_init_sftp_connection()
_init_sftp_connection ()
(Re)initializes the SFTP channel
Returns
bool @access private
Referenced by SFTP\_precheck(), and SFTP\get().
_list()
_list ($dir, $raw = true)
Reads a list, be it detailed or not, of files in the given directory
Parameters
string $dir
bool $raw
Returns
mixed @access private
Referenced by SFTP\_delete_recursive(), SFTP\_nlist_helper(), SFTP\_setstat_recursive(), and SFTP\rawlist().
_logError()
_logError ($response, $status = -1)
Logs errors
Parameters
string $response
int $status @access public
Referenced by SFTP\_close_handle(), SFTP\_init_sftp_connection(), SFTP\_list(), SFTP\_mkdir_helper(), SFTP\_read_put_responses(), SFTP\_realpath(), SFTP\_setstat(), SFTP\_stat(), SFTP\chdir(), SFTP\chmod(), SFTP\delete(), SFTP\get(), SFTP\put(), SFTP\readlink(), SFTP\rmdir(), SFTP\symlink(), and SFTP\touch().
_mkdir_helper()
_mkdir_helper ($dir, $mode)
Helper function for directory creation
Parameters
string $dir
int $mode
Returns
bool @access private
Referenced by SFTP\mkdir().
_nlist_helper()
_nlist_helper ($dir, $recursive, $relativeDir)
Helper method for nlist
Parameters
string $dir
bool $recursive
string $relativeDir
Returns
mixed @access private
Referenced by SFTP\_nlist_helper(), and SFTP\nlist().
_parseAttributes()
_parseAttributes (& $response)
Parse Attributes
See '7. File Attributes' of draft-ietf-secsh-filexfer-13 for more info.
Parameters
string $response
Returns
array @access private
Referenced by SFTP\_list(), SFTP\_stat(), and SFTP\chmod().
_parseLongname()
_parseLongname ($longname)
Parse Longname
SFTPv3 doesn't provide any easy way of identifying a file type. You could try to open a file as a directory and see if an error is returned or you could try to parse the SFTPv3-specific longname field of the SSH_FXP_NAME packet. That's what this function does. The result is returned using the SFTPv4 type constants.
If the longname is in an unrecognized format bool(false) is returned.
Parameters
string $longname
Returns
mixed @access private
Referenced by SFTP\_list().
_parseMode()
_parseMode ($mode)
Attempt to identify the file type
Quoting the SFTP RFC, "Implementations MUST NOT send bits that are not defined" but they seem to anyway
Parameters
int $mode
Returns
int @access private
_parseTime()
_parseTime ($key, $flags, & $response)
Parse Time
See '7.7. Times' of draft-ietf-secsh-filexfer-13 for more info.
Parameters
string $key
int $flags
string $response
Returns
array @access private
_partial_init_sftp_connection()
_partial_init_sftp_connection ()
Partially initialize an SFTP connection
Returns
bool @access public
Referenced by SFTP\_init_sftp_connection().
_precheck()
_precheck ()
Check a few things before SFTP functions are called
Returns
bool @access public
Referenced by SFTP\_get_xstat_cache_prop(), SFTP\_list(), SFTP\_setstat(), SFTP\chdir(), SFTP\delete(), SFTP\file_exists(), SFTP\get(), SFTP\is_readable(), SFTP\is_writable(), SFTP\lstat(), SFTP\mkdir(), SFTP\put(), SFTP\pwd(), SFTP\readlink(), SFTP\realpath(), SFTP\rmdir(), SFTP\stat(), SFTP\symlink(), and SFTP\touch().
_query_stat_cache()
_query_stat_cache ($path)
Checks cache for path
Mainly used by file_exists
Parameters
string $path
Returns
mixed @access private
Referenced by SFTP\_get_xstat_cache_prop(), SFTP\_nlist_helper(), SFTP\chdir(), SFTP\file_exists(), SFTP\lstat(), SFTP\rawlist(), and SFTP\stat().
_read_put_responses()
_read_put_responses ($i)
Reads multiple successive SSH_FXP_WRITE responses
Sending an SSH_FXP_WRITE packet and immediately reading its response isn't as efficient as blindly sending out $i SSH_FXP_WRITEs, in succession, and then reading $i responses.
Parameters
int $i
Returns
bool @access private
Referenced by SFTP\_delete_recursive(), SFTP\_setstat(), SFTP\_setstat_recursive(), SFTP\delete(), and SFTP\put().
_realpath()
_realpath ($path)
Canonicalize the Server-Side Path Name
SFTP doesn't provide a mechanism by which the current working directory can be changed, so we'll emulate it. Returns the absolute (canonicalized) path.
If canonicalize_paths has been disabled using disablePathCanonicalization(), $path is returned as-is.
See also
self::chdir()
self::disablePathCanonicalization()
Parameters
string $path
Returns
mixed @access private
Referenced by SFTP\_get_xstat_cache_prop(), SFTP\_init_sftp_connection(), SFTP\_list(), SFTP\_nlist_helper(), SFTP\_setstat(), SFTP\chdir(), SFTP\delete(), SFTP\file_exists(), SFTP\get(), SFTP\is_readable(), SFTP\is_writable(), SFTP\lstat(), SFTP\mkdir(), SFTP\put(), SFTP\rawlist(), SFTP\readlink(), SFTP\realpath(), SFTP\rmdir(), SFTP\stat(), SFTP\symlink(), and SFTP\touch().
_remove_from_stat_cache()
_remove_from_stat_cache ($path)
Remove files / directories from cache
Parameters
string $path
Returns
bool @access private
Referenced by SFTP\_delete_recursive(), SFTP\_setstat(), SFTP\delete(), SFTP\lstat(), SFTP\put(), SFTP\rmdir(), and SFTP\stat().
_reset_connection()
_reset_connection ($reason)
Resets a connection for re-use
Parameters
int $reason @access private
Reimplemented from SSH2.
_send_sftp_packet()
_send_sftp_packet ($type, $data, $request_id = 1)
Sends SFTP Packets
See '6. General Packet Format' of draft-ietf-secsh-filexfer-13 for more info.
Parameters
int $type
string $data
int $request_id
See also
self::_get_sftp_packet()
self::_send_channel_packet()
Returns
bool @access private
Referenced by SFTP\_close_handle(), SFTP\_delete_recursive(), SFTP\_init_sftp_connection(), SFTP\_list(), SFTP\_mkdir_helper(), SFTP\_partial_init_sftp_connection(), SFTP\_realpath(), SFTP\_setstat(), SFTP\_setstat_recursive(), SFTP\_stat(), SFTP\chdir(), SFTP\chmod(), SFTP\delete(), SFTP\get(), SFTP\is_readable(), SFTP\is_writable(), SFTP\put(), SFTP\readlink(), SFTP\rmdir(), SFTP\symlink(), and SFTP\touch().
_setstat()
_setstat ($filename, $attr, $recursive)
Sets information about a file
Parameters
string $filename
string $attr
bool $recursive
Returns
bool @access private
Referenced by SFTP\_setstat_recursive(), SFTP\chgrp(), SFTP\chmod(), SFTP\chown(), SFTP\put(), SFTP\touch(), and SFTP\truncate().
_setstat_recursive()
_setstat_recursive ($path, $attr, & $i)
Recursively sets information on directories on the SFTP server
Minimizes directory lookups and SSH_FXP_STATUS requests for speed.
Parameters
string $path
string $attr
int $i
Returns
bool @access private
Referenced by SFTP\_setstat(), and SFTP\_setstat_recursive().
_stat()
_stat ($filename, $type)
Returns general information about a file or symbolic link
Determines information without calling \phpseclib\Net\SFTP::realpath(). The second parameter can be either NET_SFTP_STAT or NET_SFTP_LSTAT.
Parameters
string $filename
int $type
Returns
mixed @access private
Referenced by SFTP\lstat(), and SFTP\stat().
_update_stat_cache()
_update_stat_cache ($path, $value)
Save files / directories to cache
Parameters
string $path
mixed $value @access private
Referenced by SFTP\_init_sftp_connection(), SFTP\_list(), SFTP\chdir(), SFTP\lstat(), and SFTP\stat().
chdir()
chdir ($dir)
Changes the current directory
Parameters
string $dir
Returns
bool @access public
Referenced by SFTP\lstat(), and SFTP\stat().
chgrp()
chgrp ($filename, $gid, $recursive = false)
Changes file or directory group
$gid should be an int for SFTPv3 and a string for SFTPv4+. Ideally the string would be of the form "user@dns_domain" but it does not need to be. ‘$sftp->getSupportedVersions()['version’]` will return the specific version that's being used.
Returns true on success or false on error.
Parameters
string $filename
int | string $gid
bool $recursive
Returns
bool @access public
chmod()
chmod ($mode, $filename, $recursive = false)
Set permissions on a file.
Returns the new file permissions on success or false on error. If $recursive is true than this just returns true or false.
Parameters
int $mode
string $filename
bool $recursive
Returns
mixed @access public
Referenced by SFTP\_mkdir_helper().
chown()
chown ($filename, $uid, $recursive = false)
Changes file or directory owner
$uid should be an int for SFTPv3 and a string for SFTPv4+. Ideally the string would be of the form "user@dns_domain" but it does not need to be. ‘$sftp->getSupportedVersions()['version’]` will return the specific version that's being used.
Returns true on success or false on error.
Parameters
string $filename
int | string $uid
bool $recursive
Returns
bool @access public
clearStatCache()
clearStatCache ()
Clear the stat cache
@access public
delete()
delete ($path, $recursive = true)
Deletes a file on the SFTP server.
Parameters
string $path
bool $recursive
Returns
bool @access public
disableArbitraryLengthPackets()
disableArbitraryLengthPackets ()
Disable arbitrary length packets
@access public
disableDatePreservation()
disableDatePreservation ()
Disable Date Preservation
@access public
disablePathCanonicalization()
disablePathCanonicalization ()
Enable path canonicalization
@access public
disableStatCache()
disableStatCache ()
Disable the stat cache
@access public
enableArbitraryLengthPackets()
enableArbitraryLengthPackets ()
Enable arbitrary length packets
@access public
enableDatePreservation()
enableDatePreservation ()
Enable Date Preservation
@access public
enablePathCanonicalization()
enablePathCanonicalization ()
Enable path canonicalization
@access public
enableStatCache()
enableStatCache ()
Enable the stat cache
@access public
file_exists()
file_exists ($path)
Checks whether a file or directory exists
Parameters
string $path
Returns
bool @access public
fileatime()
fileatime ($path)
Gets last access time of file
Parameters
string $path
Returns
mixed @access public
filegroup()
filegroup ($path)
Gets file group
Parameters
string $path
Returns
mixed @access public
filemtime()
filemtime ($path)
Gets file modification time
Parameters
string $path
Returns
mixed @access public
fileowner()
fileowner ($path)
Gets file owner
Parameters
string $path
Returns
mixed @access public
fileperms()
fileperms ($path)
Gets file permissions
Parameters
string $path
Returns
mixed @access public
filesize()
filesize ($path)
Gets file size
Parameters
string $path
Returns
mixed @access public
filetype()
filetype ($path)
Gets file type
Parameters
string $path
Returns
mixed @access public
get()
get ($remote_file, $local_file = false, $offset = 0, $length = -1, $progressCallback = null)
Downloads a file from the SFTP server.
Returns a string containing the contents of $remote_file if $local_file is left undefined or a boolean false if the operation was unsuccessful. If $local_file is defined, returns true or false depending on the success of the operation.
$offset and $length can be used to download files in chunks.
Parameters
string $remote_file
string $local_file
int $offset
int $length
callable | null $progressCallback
Returns
mixed @access public
getLastSFTPError()
getLastSFTPError ()
Returns the last error
Returns
string @access public
getNegotiatedVersion()
getNegotiatedVersion ()
Get supported SFTP versions
Returns
array @access public
getSFTPErrors()
getSFTPErrors ()
Returns all errors
Returns
array @access public
getSFTPLog()
getSFTPLog ()
Returns a log of the packets that have been sent and received.
Returns a string if NET_SFTP_LOGGING == NET_SFTP_LOG_COMPLEX, an array if NET_SFTP_LOGGING == NET_SFTP_LOG_SIMPLE and false if !defined('NET_SFTP_LOGGING')
@access public
Returns
string or Array
getSupportedVersions()
getSupportedVersions ()
Get supported SFTP versions
Returns
array @access public
is_dir()
is_dir ($path)
Tells whether the filename is a directory
Parameters
string $path
Returns
bool @access public
is_file()
is_file ($path)
Tells whether the filename is a regular file
Parameters
string $path
Returns
bool @access public
Referenced by SFTP\put().
is_link()
is_link ($path)
Tells whether the filename is a symbolic link
Parameters
string $path
Returns
bool @access public
is_readable()
is_readable ($path)
Tells whether a file exists and is readable
Parameters
string $path
Returns
bool @access public
is_writable()
is_writable ($path)
Tells whether the filename is writable
Parameters
string $path
Returns
bool @access public
Referenced by SFTP\is_writeable().
is_writeable()
is_writeable ($path)
Tells whether the filename is writeable
Alias of is_writable
Parameters
string $path
Returns
bool @access public
lstat()
lstat ($filename)
Returns general information about a file or symbolic link.
Returns an array on success and false otherwise.
Parameters
string $filename
Returns
mixed @access public
Referenced by SFTP\_update_stat_cache(), SFTP\lstat(), and SFTP\rawlist().
mkdir()
mkdir ($dir, $mode = -1, $recursive = false)
Creates a directory.
Parameters
string $dir
int $mode
bool $recursive
Returns
bool @access public
nlist()
nlist ($dir = '.', $recursive = false)
Returns a list of files in the given directory
Parameters
string $dir
bool $recursive
Returns
mixed @access public
put()
put ($remote_file, $data, $mode = self::SOURCE_STRING, $start = -1, $local_start = -1, $progressCallback = null)
Uploads a file to the SFTP server.
By default, \phpseclib\Net\SFTP::put() does not read from the local filesystem. $data is dumped directly into $remote_file. So, for example, if you set $data to 'filename.ext' and then do \phpseclib\Net\SFTP::get(), you will get a file, twelve bytes long, containing 'filename.ext' as its contents.
Setting $mode to self::SOURCE_LOCAL_FILE will change the above behavior. With self::SOURCE_LOCAL_FILE, $remote_file will contain as many bytes as filename.ext does on your local filesystem. If your filename.ext is 1MB then that is how large $remote_file will be, as well.
Setting $mode to self::SOURCE_CALLBACK will use $data as callback function, which gets only one parameter – number of bytes to return, and returns a string if there is some data or null if there is no more data
If $data is a resource then it'll be used as a resource instead.
Currently, only binary mode is supported. As such, if the line endings need to be adjusted, you will need to take care of that, yourself.
$mode can take an additional two parameters - self::RESUME and self::RESUME_START. These are bitwise AND'd with $mode. So if you want to resume upload of a 300mb file on the local file system you'd set $mode to the following:
self::SOURCE_LOCAL_FILE | self::RESUME
If you wanted to simply append the full contents of a local file to the full contents of a remote file you'd replace self::RESUME with self::RESUME_START.
If $mode & (self::RESUME | self::RESUME_START) then self::RESUME_START will be assumed.
$start and $local_start give you more fine grained control over this process and take precident over self::RESUME when they're non-negative. ie. $start could let you write at the end of a file (like self::RESUME) or in the middle of one. $local_start could let you start your reading from the end of a file (like self::RESUME_START) or in the middle of one.
Setting $local_start to > 0 or $mode | self::RESUME_START doesn't do anything unless $mode | self::SOURCE_LOCAL_FILE.
Parameters
string $remote_file
string | resource $data
int $mode
int $start
int $local_start
callable | null $progressCallback
Returns
bool @access public
pwd()
pwd ()
Returns the current directory name
Returns
mixed @access public
Referenced by SFTP\_init_sftp_connection(), SFTP\_precheck(), SFTP\_realpath(), SFTP\chdir(), SFTP\lstat(), and SFTP\stat().
rawlist()
rawlist ($dir = '.', $recursive = false)
Returns a detailed list of files in the given directory
Parameters
string $dir
bool $recursive
Returns
mixed @access public
Referenced by SFTP\rawlist().
readlink()
readlink ($link)
Return the target of a symbolic link
Parameters
string $link
Returns
mixed @access public
realpath()
realpath ($path)
Returns canonicalized absolute pathname
realpath() expands all symbolic links and resolves references to '/./', '/../' and extra '/' characters in the input path and returns the canonicalized absolute pathname.
Parameters
string $path
Returns
mixed @access public
Referenced by SFTP\chmod().
rename()
rename ($oldname, $newname)
Renames a file or a directory on the SFTP server.
If the file already exists this will return false
Parameters
string $oldname
string $newname
Returns
bool @access public
rmdir()
rmdir ($dir)
Removes a directory.
Parameters
string $dir
Returns
bool @access public
setListOrder()
setListOrder ()
Defines how nlist() and rawlist() will be sorted - if at all.
If sorting is enabled directories and files will be sorted independently with directories appearing before files in the resultant array that is returned.
Any parameter returned by stat is a valid sort parameter for this function. Filename comparisons are case insensitive.
Examples:
$sftp->setListOrder('filename', SORT_ASC); $sftp->setListOrder('size', SORT_DESC, 'filename', SORT_ASC); $sftp->setListOrder(true); Separates directories from files but doesn't do any sorting beyond that $sftp->setListOrder(); Don't do any sort of sorting
@access public
setPreferredVersion()
setPreferredVersion ($version)
Set preferred version
If you're preferred version isn't supported then the highest supported version of SFTP will be utilized. Set to null or false or int(0) to unset the preferred version
Parameters
int $version @access public
size()
size ($filename)
Returns the file size, in bytes, or false, on failure
Files larger than 4GB will show up as being exactly 4GB.
Parameters
string $filename
Returns
mixed @access public
Referenced by Stream\_stream_open(), Stream\_stream_read(), Stream\_stream_truncate(), Stream\_stream_write(), and SFTP\put().
stat()
stat ($filename)
Returns general information about a file.
Returns an array on success and false otherwise.
Parameters
string $filename
Returns
mixed @access public
Referenced by SFTP\_update_stat_cache(), SFTP\file_exists(), SFTP\get(), SFTP\put(), SFTP\size(), and SFTP\stat().
symlink()
symlink ($target, $link)
Create a symlink
symlink() creates a symbolic link to the existing target with the specified name link.
Parameters
string $target
string $link
Returns
bool @access public
touch()
touch ($filename, $time = null, $atime = null)
Sets access and modification time of file.
If the file does not exist, it will be created.
Parameters
string $filename
int $time
int $atime
Returns
bool @access public
Referenced by SFTP\get().
truncate()
truncate ($filename, $new_size)
Truncates a file to a given length
Parameters
string $filename
int $new_size
Returns
bool @access public
Member Data Documentation
CHANNEL
const CHANNEL = 0x100
SFTP channel constant
\phpseclib\Net\SSH2::exec() uses 0 and \phpseclib\Net\SSH2::read() / \phpseclib\Net\SSH2::write() use 1.
See also
\phpseclib\Net\SSH2::_send_channel_packet()
\phpseclib\Net\SSH2::_get_channel_packet() @access private
Referenced by SFTP\_partial_init_sftp_connection().
RESUME
const RESUME = 4
Resumes an upload
RESUME_START
const RESUME_START = 8
Append a local file to an already existing remote file
SOURCE_CALLBACK
const SOURCE_CALLBACK = 16
Reads data from callback: function callback($length) returns string to proceed, null for EOF
Referenced by SFTP\put().
SOURCE_LOCAL_FILE
const SOURCE_LOCAL_FILE = 1
#+ @access public
See also
\phpseclib\Net\SFTP::put() Reads data from a local file.
Referenced by SFTP\put().
SOURCE_STRING
const SOURCE_STRING = 2
Reads data from a string.
Referenced by Stream\_stream_write().
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php