Utopszkij_db: SolidityType Class Reference
SolidityType Class Reference
Public Member Functions
__get ($name)
__set ($name, $value)
nestedTypes ($name)
nestedName ($name)
isDynamicArray ($name)
isStaticArray ($name)
staticArrayLength ($name)
staticPartLength ($name)
isDynamicType ()
encode ($value, $name)
decode ($value, $offset, $name)
Member Function Documentation
__get()
__get ($name)
construct
Returns
void get
Parameters
string $name
Returns
mixed
__set()
__set ($name, $value)
set
Parameters
string $name
mixed $value
Returns
mixed;
decode()
decode ($value, $offset, $name)
decode
Parameters
mixed $value
string $offset
string $name
Returns
array
Referenced by SolidityType\decode().
encode()
encode ($value, $name)
encode
Parameters
mixed $value
string $name
Returns
string
Referenced by SolidityType\encode().
isDynamicArray()
isDynamicArray ($name)
isDynamicArray
Parameters
string $name
Returns
bool
Referenced by SolidityType\decode(), and SolidityType\encode().
isDynamicType()
isDynamicType ()
isDynamicType
Returns
bool
Reimplemented in Address, Boolean, Bytes, DynamicBytes, Integer, Str, and Uinteger.
Referenced by SolidityType\decode().
isStaticArray()
isStaticArray ($name)
isStaticArray
Parameters
string $name
Returns
bool
Referenced by SolidityType\decode(), and SolidityType\encode().
nestedName()
nestedName ($name)
nestedName
Parameters
string $name
Returns
string
Referenced by SolidityType\decode(), and SolidityType\encode().
nestedTypes()
nestedTypes ($name)
callStatic
Parameters
string $name
array $arguments
Returns
void nestedTypes
Parameters
string $name
Returns
mixed
Referenced by SolidityType\isDynamicArray(), SolidityType\isStaticArray(), SolidityType\nestedName(), SolidityType\staticArrayLength(), and SolidityType\staticPartLength().
staticArrayLength()
staticArrayLength ($name)
staticArrayLength
Parameters
string $name
Returns
int
Referenced by SolidityType\decode(), and SolidityType\encode().
staticPartLength()
staticPartLength ($name)
staticPartLength
Parameters
string $name
Returns
int
Referenced by SolidityType\decode().
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/web3p/web3.php/src/Contracts/SolidityType.php