Utopszkij_db: BigInteger Class Reference
BigInteger Class Reference
Public Member Functions
__construct ($x=0, $base=10)
toBytes ($twos_compliment=false)
toHex ($twos_compliment=false)
toBits ($twos_compliment=false)
toString ()
copy ()
__toString ()
__clone ()
__sleep ()
__wakeup ()
__debugInfo ()
add ($y)
_add ($x_value, $x_negative, $y_value, $y_negative)
subtract ($y)
_subtract ($x_value, $x_negative, $y_value, $y_negative)
multiply ($x)
_multiply ($x_value, $x_negative, $y_value, $y_negative)
_regularMultiply ($x_value, $y_value)
_karatsuba ($x_value, $y_value)
_square ($x=false)
_baseSquare ($value)
_karatsubaSquare ($value)
divide ($y)
_divide_digit ($dividend, $divisor)
modPow ($e, $n)
powMod ($e, $n)
_slidingWindow ($e, $n, $mode)
_reduce ($x, $n, $mode)
_prepareReduce ($x, $n, $mode)
_multiplyReduce ($x, $y, $n, $mode)
_squareReduce ($x, $n, $mode)
_mod2 ($n)
_barrett ($n, $m)
_regularBarrett ($x, $n)
_multiplyLower ($x_value, $x_negative, $y_value, $y_negative, $stop)
_montgomery ($x, $n)
_montgomeryMultiply ($x, $y, $m)
_prepMontgomery ($x, $n)
_modInverse67108864 ($x)
modInverse ($n)
extendedGCD ($n)
gcd ($n)
abs ()
compare ($y)
_compare ($x_value, $x_negative, $y_value, $y_negative)
equals ($x)
setPrecision ($bits)
bitwise_and ($x)
bitwise_or ($x)
bitwise_xor ($x)
bitwise_not ()
bitwise_rightShift ($shift)
bitwise_leftShift ($shift)
bitwise_leftRotate ($shift)
bitwise_rightRotate ($shift)
_random_number_helper ($size)
random ($arg1, $arg2=false)
randomPrime ($arg1, $arg2=false, $timeout=false)
_make_odd ()
isPrime ($t=false)
_lshift ($shift)
_rshift ($shift)
_normalize ($result)
_trim ($value)
_array_repeat ($input, $multiplier)
_base256_lshift (&$x, $shift)
_base256_rshift (&$x, $shift)
_int2bytes ($x)
_bytes2int ($x)
_encodeASN1Length ($length)
_safe_divide ($x, $y)
Public Attributes
const MONTGOMERY = 0
const BARRETT = 1
const POWEROF2 = 2
const CLASSIC = 3
const NONE = 4
const VALUE = 0
const SIGN = 1
const VARIABLE = 0
const DATA = 1
const MODE_INTERNAL = 1
const MODE_BCMATH = 2
const MODE_GMP = 3
const KARATSUBA_CUTOFF = 25
$value
$is_negative = false
$precision = -1
$bitmask = false
$hex
Static Protected Attributes
static $base
static $baseFull
static $maxDigit
static $msb
static $max10
static $max10Len
static $maxDigit2
Constructor & Destructor Documentation
__construct()
__construct ($x = 0, $base = 10)
Converts base-2, base-10, base-16, and binary strings (base-256) to BigIntegers.
If the second parameter - $base - is negative, then it will be assumed that the number's are encoded using two's compliment. The sole exception to this is -10, which is treated the same as 10 is.
Here's an example: <?php $a = new \phpseclib\Math\BigInteger('0x32', 16); // 50 in base-16
echo $a->toString(); // outputs 50 ?>
Parameters
int | string | resource $x base-10 number or base-$base number if $base set.
int $base
Returns
\phpseclib\Math\BigInteger @access public
Member Function Documentation
__clone()
__clone ()
__clone() magic method
Although you can call BigInteger::__toString() directly in PHP5, you cannot call BigInteger::__clone() directly in PHP5. You can in PHP4 since it's not a magic method, but in PHP5, you have to call it by using the PHP5 only syntax of $y = clone $x. As such, if you're trying to write an application that works on both PHP4 and PHP5, call BigInteger::copy(), instead.
@access public
See also
self::copy()
Returns
\phpseclib\Math\BigInteger
__debugInfo()
__debugInfo ()
__debugInfo() magic method
Will be called, automatically, when print_r() or var_dump() are called
@access public
__sleep()
__sleep ()
__sleep() magic method
Will be called, automatically, when serialize() is called on a BigInteger object.
See also
self::__wakeup() @access public
__toString()
__toString ()
__toString() magic method
Will be called, automatically, if you're supporting just PHP5. If you're supporting PHP4, you'll need to call toString().
@access public
__wakeup()
__wakeup ()
__wakeup() magic method
Will be called, automatically, when unserialize() is called on a BigInteger object.
See also
self::__sleep() @access public
_add()
_add ($x_value, $x_negative, $y_value, $y_negative)
Performs addition.
Parameters
array $x_value
bool $x_negative
array $y_value
bool $y_negative
Returns
array @access private
Referenced by BigInteger\_barrett(), BigInteger\_karatsuba(), BigInteger\_karatsubaSquare(), BigInteger\_montgomery(), BigInteger\_montgomeryMultiply(), BigInteger\_regularBarrett(), BigInteger\_subtract(), and BigInteger\add().
_array_repeat()
_array_repeat ($input, $multiplier)
Array Repeat
Parameters
array $input
mixed $multiplier
Returns
array @access private
Referenced by BigInteger\_barrett(), BigInteger\_baseSquare(), BigInteger\_montgomery(), BigInteger\_montgomeryMultiply(), BigInteger\_multiplyLower(), BigInteger\_prepMontgomery(), BigInteger\_regularBarrett(), BigInteger\_regularMultiply(), and BigInteger\divide().
_barrett()
_barrett ($n, $m)
Barrett Modular Reduction
See HAC 14.3.3 / MPM 6.2.5 for more information. Modified slightly, so as not to require negative numbers (initially, this script didn't support negative numbers).
Employs "folding", as described at thesis-149.pdf#page=66. To quote from it, "the idea [behind folding] is to find a value x' such that x (mod m) = x' (mod m), with x' being smaller than x."
Unfortunately, the "Barrett Reduction with Folding" algorithm described in thesis-149.pdf is not, as written, all that usable on account of (1) its not using reasonable radix points as discussed in MPM 6.2.2 and (2) the fact that, even with reasonable radix points, it only works when there are an even number of digits in the denominator. The reason for (2) is that (x >> 1) + (x >> 1) != x / 2 + x / 2. If x is even, they're the same, but if x is odd, they're not. See the in-line comments for details.
See also
self::_slidingWindow() @access private
Parameters
array $n
array $m
Returns
array
Referenced by BigInteger\_reduce().
_base256_lshift()
_base256_lshift (& $x, $shift)
Logical Left Shift
Shifts binary strings $shift bits, essentially multiplying by 2**$shift.
Parameters
string $x (by reference)
int $shift
Returns
string @access private
Referenced by BigInteger\bitwise_not().
_base256_rshift()
_base256_rshift (& $x, $shift)
Logical Right Shift
Shifts binary strings $shift bits, essentially dividing by 2**$shift and returning the remainder.
Parameters
string $x (by referenc)
int $shift
Returns
string @access private
Referenced by BigInteger\__construct().
_baseSquare()
_baseSquare ($value)
Performs traditional squaring on two BigIntegers
Squaring can be done faster than multiplying a number by itself can be. See HAC 14.2.4 / MPM 5.3 for more information.
Parameters
array $value
Returns
array @access private
Referenced by BigInteger\_karatsubaSquare(), and BigInteger\_square().
_bytes2int()
_bytes2int ($x)
Converts bytes to 32-bit integers
Parameters
string $x
Returns
int @access private
Referenced by BigInteger\__construct().
_compare()
_compare ($x_value, $x_negative, $y_value, $y_negative)
Compares two numbers.
Parameters
array $x_value
bool $x_negative
array $y_value
bool $y_negative
Returns
int
See also
self::compare() @access private
Referenced by BigInteger\_add(), BigInteger\_barrett(), BigInteger\_montgomery(), BigInteger\_montgomeryMultiply(), BigInteger\_regularBarrett(), BigInteger\_subtract(), and BigInteger\compare().
_divide_digit()
_divide_digit ($dividend, $divisor)
Divides a BigInteger by a regular integer
abc / x = a00 / x + b0 / x + c / x
Parameters
array $dividend
array $divisor
Returns
array @access private
Referenced by BigInteger\divide(), and BigInteger\isPrime().
_encodeASN1Length()
_encodeASN1Length ($length)
DER-encode an integer
The ability to DER-encode integers is needed to create RSA public keys for use with OpenSSL
See also
self::modPow() @access private
Parameters
int $length
Returns
string
Referenced by BigInteger\modPow().
_int2bytes()
_int2bytes ($x)
Converts 32-bit integers to bytes.
Parameters
int $x
Returns
string @access private
Referenced by BigInteger\__construct(), and BigInteger\toBytes().
_karatsuba()
_karatsuba ($x_value, $y_value)
Performs Karatsuba multiplication on two BigIntegers
See Karatsuba algorithm and MPM 5.2.3.
Parameters
array $x_value
array $y_value
Returns
array @access private
Referenced by BigInteger\_karatsuba(), and BigInteger\_multiply().
_karatsubaSquare()
_karatsubaSquare ($value)
Performs Karatsuba "squaring" on two BigIntegers
See Karatsuba algorithm and MPM 5.3.4.
Parameters
array $value
Returns
array @access private
Referenced by BigInteger\_karatsubaSquare(), and BigInteger\_square().
_lshift()
_lshift ($shift)
Logical Left Shift
Shifts BigInteger's by $shift bits.
Parameters
int $shift @access private
_make_odd()
_make_odd ()
Make the current number odd
If the current number is odd it'll be unchanged. If it's even, one will be added to it.
See also
self::randomPrime() @access private
_mod2()
_mod2 ($n)
Modulos for Powers of Two
Calculates $x$n, where $n = 2**$e, for some $e. Since this is basically the same as doing $x & ($n-1), we'll just use this function as a wrapper for doing that.
See also
self::_slidingWindow() @access private
Parameters
\phpseclib\Math\BigInteger $n
Returns
\phpseclib\Math\BigInteger
_modInverse67108864()
_modInverse67108864 ($x)
Modular Inverse of a number mod 2**26 (eg. 67108864)
Based off of the bnpInvDigit function implemented and justified in the following URL:
http://www-cs-students.stanford.edu/~tjw/jsbn/jsbn.js
The following URL provides more info:
http://groups.google.com/group/sci.crypt/msg/7a137205c1be7d85
As for why we do all the bitmasking... strange things can happen when converting from floats to ints. For instance, on some computers, var_dump((int) -4294967297) yields int(-1) and on others, it yields int(-2147483648). To avoid problems stemming from this, we use bitmasks to guarantee that ints aren't auto-converted to floats. The outermost bitmask is present because without it, there's no guarantee that the "residue" returned would be the so-called "common residue". We use fmod, in the last step, because the maximum possible $x is 26 bits and the maximum $result is 16 bits. Thus, we have to be able to handle up to 40 bits, which only 64-bit floating points will support.
Thanks to Pedro Gimeno Fortea for input!
See also
self::_montgomery() @access private
Parameters
array $x
Returns
int
Referenced by BigInteger\_montgomery(), and BigInteger\_montgomeryMultiply().
_montgomery()
_montgomery ($x, $n)
Montgomery Modular Reduction
($x->_prepMontgomery($n))->_montgomery($n) yields $x % $n. MPM 6.3 provides insights on how this can be improved upon (basically, by using the comba method). gcd($n, 2) must be equal to one for this function to work correctly.
See also
self::_prepMontgomery()
self::_slidingWindow() @access private
Parameters
array $x
array $n
Returns
array
Referenced by BigInteger\_montgomeryMultiply(), and BigInteger\_reduce().
_montgomeryMultiply()
_montgomeryMultiply ($x, $y, $m)
Montgomery Multiply
Interleaves the montgomery reduction and long multiplication algorithms together as described in HAC 14.36
See also
self::_prepMontgomery()
self::_montgomery() @access private
Parameters
array $x
array $y
array $m
Returns
array
Referenced by BigInteger\_multiplyReduce(), and BigInteger\_squareReduce().
_multiply()
_multiply ($x_value, $x_negative, $y_value, $y_negative)
Performs multiplication.
Parameters
array $x_value
bool $x_negative
array $y_value
bool $y_negative
Returns
array @access private
Referenced by BigInteger\_barrett(), BigInteger\_montgomeryMultiply(), BigInteger\_multiplyReduce(), BigInteger\_regularBarrett(), and BigInteger\multiply().
_multiplyLower()
_multiplyLower ($x_value, $x_negative, $y_value, $y_negative, $stop)
Performs long multiplication up to $stop digits
If you're going to be doing array_slice($product->value, 0, $stop), some cycles can be saved.
See also
self::_regularBarrett()
Parameters
array $x_value
bool $x_negative
array $y_value
bool $y_negative
int $stop
Returns
array @access private
Referenced by BigInteger\_regularBarrett().
_multiplyReduce()
_multiplyReduce ($x, $y, $n, $mode)
Modular multiply
See also
self::_slidingWindow() @access private
Parameters
array $x
array $y
array $n
int $mode
Returns
array
Referenced by BigInteger\_slidingWindow().
_normalize()
_normalize ($result)
Normalize
Removes leading zeros and truncates (if necessary) to maintain the appropriate precision
Parameters
\phpseclib\Math\BigInteger $result
Returns
\phpseclib\Math\BigInteger
See also
self::_trim() @access private
Referenced by BigInteger\add(), BigInteger\bitwise_and(), BigInteger\bitwise_leftRotate(), BigInteger\bitwise_leftShift(), BigInteger\bitwise_not(), BigInteger\bitwise_or(), BigInteger\bitwise_rightShift(), BigInteger\bitwise_xor(), BigInteger\divide(), BigInteger\extendedGCD(), BigInteger\modInverse(), BigInteger\modPow(), BigInteger\multiply(), BigInteger\random(), BigInteger\setPrecision(), and BigInteger\subtract().
_prepareReduce()
_prepareReduce ($x, $n, $mode)
Modular reduction preperation
See also
self::_slidingWindow() @access private
Parameters
array $x
array $n
int $mode
Returns
array
Referenced by BigInteger\_slidingWindow().
_prepMontgomery()
_prepMontgomery ($x, $n)
Prepare a number for use in Montgomery Modular Reductions
See also
self::_montgomery()
self::_slidingWindow() @access private
Parameters
array $x
array $n
Returns
array
Referenced by BigInteger\_prepareReduce().
_random_number_helper()
_random_number_helper ($size)
Generates a random BigInteger
Byte length is equal to $length. Uses \phpseclib\Crypt\Random if it's loaded and mt_rand if it's not.
Parameters
int $size
Returns
\phpseclib\Math\BigInteger @access private
Referenced by BigInteger\random().
_reduce()
_reduce ($x, $n, $mode)
Modular reduction
For most $modes this will return the remainder.
See also
self::_slidingWindow() @access private
Parameters
array $x
array $n
int $mode
Returns
array
Referenced by BigInteger\_multiplyReduce(), BigInteger\_prepareReduce(), BigInteger\_slidingWindow(), and BigInteger\_squareReduce().
_regularBarrett()
_regularBarrett ($x, $n)
(Regular) Barrett Modular Reduction
For numbers with more than four digits BigInteger::_barrett() is faster. The difference between that and this is that this function does not fold the denominator into a smaller form.
See also
self::_slidingWindow() @access private
Parameters
array $x
array $n
Returns
array
Referenced by BigInteger\_barrett().
_regularMultiply()
_regularMultiply ($x_value, $y_value)
Performs long multiplication on two BigIntegers
Modeled after 'multiply' in MutableBigInteger.java.
Parameters
array $x_value
array $y_value
Returns
array @access private
Referenced by BigInteger\_karatsuba(), BigInteger\_montgomery(), BigInteger\_montgomeryMultiply(), and BigInteger\_multiply().
_rshift()
_rshift ($shift)
Logical Right Shift
Shifts BigInteger's by $shift bits.
Parameters
int $shift @access private
_safe_divide()
_safe_divide ($x, $y)
Single digit division
Even if int64 is being used the division operator will return a float64 value if the dividend is not evenly divisible by the divisor. Since a float64 doesn't have the precision of int64 this is a problem so, when int64 is being used, we'll guarantee that the dividend is divisible by first subtracting the remainder.
@access private
Parameters
int $x
int $y
Returns
int
Referenced by BigInteger\_divide_digit(), and BigInteger\divide().
_slidingWindow()
_slidingWindow ($e, $n, $mode)
Sliding Window k-ary Modular Exponentiation
Based on HAC 14.85 / MPM 7.7. In a departure from those algorithims, however, this function performs a modular reduction after every multiplication and squaring operation. As such, this function has the same preconditions that the reductions being used do.
Parameters
\phpseclib\Math\BigInteger $e
\phpseclib\Math\BigInteger $n
int $mode
Returns
\phpseclib\Math\BigInteger @access private
Referenced by BigInteger\modPow().
_square()
_square ($x = false)
Performs squaring
Parameters
array $x
Returns
array @access private
Referenced by BigInteger\_squareReduce(), and BigInteger\modPow().
_squareReduce()
_squareReduce ($x, $n, $mode)
Modular square
See also
self::_slidingWindow() @access private
Parameters
array $x
array $n
int $mode
Returns
array
Referenced by BigInteger\_slidingWindow().
_subtract()
_subtract ($x_value, $x_negative, $y_value, $y_negative)
Performs subtraction.
Parameters
array $x_value
bool $x_negative
array $y_value
bool $y_negative
Returns
array @access private
Referenced by BigInteger\_add(), BigInteger\_barrett(), BigInteger\_karatsuba(), BigInteger\_karatsubaSquare(), BigInteger\_montgomery(), BigInteger\_montgomeryMultiply(), BigInteger\_regularBarrett(), and BigInteger\subtract().
_trim()
_trim ($value)
Trim
Removes leading zeros
Parameters
array $value
Returns
\phpseclib\Math\BigInteger @access private
Referenced by BigInteger\_add(), BigInteger\_barrett(), BigInteger\_multiply(), BigInteger\_multiplyLower(), BigInteger\_normalize(), BigInteger\_rshift(), BigInteger\_square(), and BigInteger\_subtract().
abs()
abs ()
Absolute value.
Returns
\phpseclib\Math\BigInteger @access public
Referenced by BigInteger\__construct(), and BigInteger\modInverse().
add()
add ($y)
Adds two BigIntegers.
Here's an example: <?php $a = new \phpseclib\Math\BigInteger('10'); $b = new \phpseclib\Math\BigInteger('20');
$c = $a->add($b);
echo $c->toString(); // outputs 30 ?>
Parameters
\phpseclib\Math\BigInteger $y
Returns
\phpseclib\Math\BigInteger @access public
Referenced by BigInteger\__construct(), and BigInteger\toBytes().
bitwise_and()
bitwise_and ($x)
Logical And
Parameters
\phpseclib\Math\BigInteger $x @access public
Referenced by BigInteger\_mod2().
bitwise_leftRotate()
bitwise_leftRotate ($shift)
Logical Left Rotate
Instead of the top x bits being dropped they're appended to the shifted bit string.
Parameters
int $shift
Returns
\phpseclib\Math\BigInteger @access public
Referenced by BigInteger\bitwise_rightRotate().
bitwise_leftShift()
bitwise_leftShift ($shift)
Logical Left Shift
Shifts BigInteger's by $shift bits, effectively multiplying by 2**$shift.
Parameters
int $shift
Returns
\phpseclib\Math\BigInteger @access public
Referenced by BigInteger\bitwise_leftRotate().
bitwise_not()
bitwise_not ()
Logical Not
@access public
bitwise_or()
bitwise_or ($x)
Logical Or
Parameters
\phpseclib\Math\BigInteger $x @access public
bitwise_rightRotate()
bitwise_rightRotate ($shift)
Logical Right Rotate
Instead of the bottom x bits being dropped they're prepended to the shifted bit string.
Parameters
int $shift
Returns
\phpseclib\Math\BigInteger @access public
bitwise_rightShift()
bitwise_rightShift ($shift)
Logical Right Shift
Shifts BigInteger's by $shift bits, effectively dividing by 2**$shift.
Parameters
int $shift
Returns
\phpseclib\Math\BigInteger @access public
Referenced by BigInteger\bitwise_leftRotate().
bitwise_xor()
bitwise_xor ($x)
Logical Exclusive-Or
Parameters
\phpseclib\Math\BigInteger $x @access public
compare()
compare ($y)
Compares two numbers.
Although one might think !$x->compare($y) means $x != $y, it, in fact, means the opposite. The reason for this is demonstrated thusly:
$x > $y: $x->compare($y) > 0 $x < $y: $x->compare($y) < 0 $x == $y: $x->compare($y) == 0
Note how the same comparison operator is used. If you want to test for equality, use $x->equals($y).
Parameters
\phpseclib\Math\BigInteger $y
Returns
int that is < 0 if $this is less than $y; > 0 if $this is greater than $y, and 0 if they are equal. @access public
See also
self::equals()
Referenced by BigInteger\modInverse(), BigInteger\modPow(), BigInteger\toBits(), and BigInteger\toBytes().
copy()
copy ()
Copy an object
PHP5 passes objects by reference while PHP4 passes by value. As such, we need a function to guarantee that all objects are passed by value, when appropriate. More information can be found here:
http://php.net/language.oop5.basic#51624
@access public
See also
self::__clone()
Returns
\phpseclib\Math\BigInteger
Referenced by BigInteger\__clone(), BigInteger\bitwise_and(), BigInteger\bitwise_leftRotate(), BigInteger\bitwise_or(), BigInteger\bitwise_xor(), BigInteger\divide(), BigInteger\extendedGCD(), BigInteger\isPrime(), BigInteger\toBytes(), and BigInteger\toString().
divide()
divide ($y)
Divides two BigIntegers.
Returns an array whose first element contains the quotient and whose second element contains the "common residue". If the remainder would be positive, the "common residue" and the remainder are the same. If the remainder would be negative, the "common residue" is equal to the sum of the remainder and the divisor (basically, the "common residue" is the first positive modulo).
Here's an example: <?php $a = new \phpseclib\Math\BigInteger('10'); $b = new \phpseclib\Math\BigInteger('20');
list($quotient, $remainder) = $a->divide($b);
echo $quotient->toString(); // outputs 0 echo "\r\n"; echo $remainder->toString(); // outputs 10 ?>
Parameters
\phpseclib\Math\BigInteger $y
Returns
array @access public
Referenced by BigInteger\isPrime(), and BigInteger\modPow().
equals()
equals ($x)
Tests the equality of two numbers.
If you need to see if one number is greater than or less than another number, use BigInteger::compare()
Parameters
\phpseclib\Math\BigInteger $x
Returns
bool @access public
See also
self::compare()
Referenced by BigInteger\isPrime().
extendedGCD()
extendedGCD ($n)
Calculates the greatest common divisor and Bezout's identity.
Say you have 693 and 609. The GCD is 21. Bezout's identity states that there exist integers x and y such that 693*x + 609*y == 21. In point of fact, there are actually an infinite number of x and y combinations and which combination is returned is dependent upon which mode is in use. See Bezout's identity - Wikipedia for more information.
Here's an example: <?php $a = new \phpseclib\Math\BigInteger(693); $b = new \phpseclib\Math\BigInteger(609);
extract($a->extendedGCD($b));
echo $gcd->toString() . "\r\n"; // outputs 21 echo $a->toString() * $x->toString() + $b->toString() * $y->toString(); // outputs 21 ?>
Parameters
\phpseclib\Math\BigInteger $n
Returns
\phpseclib\Math\BigInteger @access public
Referenced by BigInteger\gcd(), and BigInteger\modInverse().
gcd()
gcd ($n)
Calculates the greatest common divisor
Say you have 693 and 609. The GCD is 21.
Here's an example: <?php $a = new \phpseclib\Math\BigInteger(693); $b = new \phpseclib\Math\BigInteger(609);
$gcd = a->extendedGCD($b);
echo $gcd->toString() . "\r\n"; // outputs 21 ?>
Parameters
\phpseclib\Math\BigInteger $n
Returns
\phpseclib\Math\BigInteger @access public
isPrime()
isPrime ($t = false)
Checks a numer to see if it's prime
Assuming the $t parameter is not set, this function has an error rate of 2**-80. The main motivation for the $t parameter is distributability. BigInteger::randomPrime() can be distributed across multiple pageloads on a website instead of just one.
Parameters
\phpseclib\Math\BigInteger $t
Returns
bool @access public
modInverse()
modInverse ($n)
Calculates modular inverses.
Say you have (30 mod 17 * x mod 17) mod 17 == 1. x can be found using modular inverses.
Here's an example: <?php $a = new \phpseclib\Math\BigInteger(30); $b = new \phpseclib\Math\BigInteger(17);
$c = $a->modInverse($b); echo $c->toString(); // outputs 4
echo "\r\n";
$d = $a->multiply($c); list(, $d) = $d->divide($b); echo $d; // outputs 1 (as per the definition of modular inverse) ?>
Parameters
\phpseclib\Math\BigInteger $n
Returns
\phpseclib\Math\BigInteger|false @access public
Referenced by BigInteger\modPow().
modPow()
modPow ($e, $n)
Performs modular exponentiation.
Here's an example: <?php $a = new \phpseclib\Math\BigInteger('10'); $b = new \phpseclib\Math\BigInteger('20'); $c = new \phpseclib\Math\BigInteger('30');
$c = $a->modPow($b, $c);
echo $c->toString(); // outputs 10 ?>
Parameters
\phpseclib\Math\BigInteger $e
\phpseclib\Math\BigInteger $n
Returns
\phpseclib\Math\BigInteger @access public
Referenced by BigInteger\powMod().
multiply()
multiply ($x)
Multiplies two BigIntegers
Here's an example: <?php $a = new \phpseclib\Math\BigInteger('10'); $b = new \phpseclib\Math\BigInteger('20');
$c = $a->multiply($b);
echo $c->toString(); // outputs 200 ?>
Parameters
\phpseclib\Math\BigInteger $x
Returns
\phpseclib\Math\BigInteger @access public
powMod()
powMod ($e, $n)
Performs modular exponentiation.
Alias for modPow().
Parameters
\phpseclib\Math\BigInteger $e
\phpseclib\Math\BigInteger $n
Returns
\phpseclib\Math\BigInteger @access public
random()
random ($arg1, $arg2 = false)
Generate a random number
Returns a random number between $min and $max where $min and $max can be defined using one of the two methods:
$min->random($max) $max->random($min)
Parameters
\phpseclib\Math\BigInteger $arg1
\phpseclib\Math\BigInteger $arg2
Returns
\phpseclib\Math\BigInteger @access public
Referenced by BigInteger\isPrime(), and BigInteger\randomPrime().
randomPrime()
randomPrime ($arg1, $arg2 = false, $timeout = false)
Generate a random prime number.
If there's not a prime within the given range, false will be returned. If more than $timeout seconds have elapsed, give up and return false.
Parameters
\phpseclib\Math\BigInteger $arg1
\phpseclib\Math\BigInteger $arg2
int $timeout
Returns
Math_BigInteger|false @access public
setPrecision()
setPrecision ($bits)
Set Precision
Some bitwise operations give different results depending on the precision being used. Examples include left shift, not, and rotates.
Parameters
int $bits @access public
Referenced by BigInteger\__wakeup().
subtract()
subtract ($y)
Subtracts two BigIntegers.
Here's an example: <?php $a = new \phpseclib\Math\BigInteger('10'); $b = new \phpseclib\Math\BigInteger('20');
$c = $a->subtract($b);
echo $c->toString(); // outputs -10 ?>
Parameters
\phpseclib\Math\BigInteger $y
Returns
\phpseclib\Math\BigInteger @access public
toBits()
toBits ($twos_compliment = false)
Converts a BigInteger to a bit string (eg. base-2).
Negative numbers are saved as positive numbers, unless $twos_compliment is set to true, at which point, they're saved as two's compliment.
Here's an example: <?php $a = new \phpseclib\Math\BigInteger('65');
echo $a->toBits(); // outputs '1000001' ?>
Parameters
bool $twos_compliment
Returns
string @access public
toBytes()
toBytes ($twos_compliment = false)
Converts a BigInteger to a byte string (eg. base-256).
Negative numbers are saved as positive numbers, unless $twos_compliment is set to true, at which point, they're saved as two's compliment.
Here's an example: <?php $a = new \phpseclib\Math\BigInteger('65');
echo $a->toBytes(); // outputs chr(65) ?>
Parameters
bool $twos_compliment
Returns
string @access public
Referenced by BigInteger\bitwise_and(), BigInteger\bitwise_leftRotate(), BigInteger\bitwise_not(), BigInteger\bitwise_or(), BigInteger\bitwise_xor(), BigInteger\isPrime(), BigInteger\modPow(), and BigInteger\toHex().
toHex()
toHex ($twos_compliment = false)
Converts a BigInteger to a hex string (eg. base-16)).
Negative numbers are saved as positive numbers, unless $twos_compliment is set to true, at which point, they're saved as two's compliment.
Here's an example: <?php $a = new \phpseclib\Math\BigInteger('65');
echo $a->toHex(); // outputs '41' ?>
Parameters
bool $twos_compliment
Returns
string @access public
Referenced by BigInteger\__debugInfo(), BigInteger\__sleep(), and BigInteger\toBits().
toString()
toString ()
Converts a BigInteger to a base-10 number.
Here's an example: <?php $a = new \phpseclib\Math\BigInteger('50');
echo $a->toString(); // outputs 50 ?>
Returns
string @access public
Referenced by BigInteger\__toString().
Member Data Documentation
$base
$base static protected
#+ Static properties used by the pure-PHP implementation.
See also
__construct()
Referenced by BigInteger\__construct(), BigInteger\_lshift(), and BigInteger\_rshift().
$bitmask
$bitmask = false
Precision Bitmask
See also
self::setPrecision() @access private
Referenced by BigInteger\_normalize(), and BigInteger\copy().
$max10
$max10 static protected
$max10 in greatest $max10Len satisfying $max10 = 10**$max10Len <= 2**$base.
$max10Len
$max10Len static protected
$max10Len in greatest $max10Len satisfying $max10 = 10**$max10Len <= 2**$base.
$precision
$precision = -1
Precision
See also
self::setPrecision() @access private
Referenced by BigInteger\_normalize(), BigInteger\bitwise_leftRotate(), and BigInteger\copy().
BARRETT
const BARRETT = 1
See also
BigInteger::_barrett()
Referenced by BigInteger\_reduce().
CLASSIC
const CLASSIC = 3
See also
BigInteger::_remainder()
Referenced by BigInteger\_reduce().
DATA
const DATA = 1
$cache[self::DATA] contains the cached data.
Referenced by BigInteger\_barrett(), BigInteger\_montgomery(), BigInteger\_montgomeryMultiply(), and BigInteger\_regularBarrett().
KARATSUBA_CUTOFF
const KARATSUBA_CUTOFF = 25
#- Karatsuba Cutoff
At what point do we switch between Karatsuba multiplication and schoolbook long multiplication?
@access private
MODE_BCMATH
const MODE_BCMATH = 2
To use the BCMath library
(if enabled; otherwise, the internal implementation will be used)
Referenced by BigInteger\__construct(), BigInteger\__debugInfo(), BigInteger\_make_odd(), BigInteger\_normalize(), BigInteger\abs(), BigInteger\add(), BigInteger\bitwise_and(), BigInteger\bitwise_leftShift(), BigInteger\bitwise_or(), BigInteger\bitwise_rightShift(), BigInteger\bitwise_xor(), BigInteger\compare(), BigInteger\divide(), BigInteger\extendedGCD(), BigInteger\isPrime(), BigInteger\multiply(), BigInteger\subtract(), BigInteger\toBytes(), and BigInteger\toString().
MODE_GMP
const MODE_GMP = 3
To use the GMP library
(if present; otherwise, either the BCMath or the internal implementation will be used)
Referenced by BigInteger\__construct(), BigInteger\__debugInfo(), BigInteger\_make_odd(), BigInteger\_normalize(), BigInteger\abs(), BigInteger\add(), BigInteger\bitwise_and(), BigInteger\bitwise_leftShift(), BigInteger\bitwise_or(), BigInteger\bitwise_rightShift(), BigInteger\bitwise_xor(), BigInteger\compare(), BigInteger\divide(), BigInteger\equals(), BigInteger\extendedGCD(), BigInteger\isPrime(), BigInteger\modInverse(), BigInteger\multiply(), BigInteger\subtract(), BigInteger\toBytes(), and BigInteger\toString().
MODE_INTERNAL
const MODE_INTERNAL = 1
#- #+ Mode constants.
@access private
See also
BigInteger::__construct() To use the pure-PHP implementation
Referenced by BigInteger\__debugInfo().
MONTGOMERY
const MONTGOMERY = 0
#+ Reduction constants
@access private
See also
BigInteger::_reduce()
BigInteger::_montgomery()
BigInteger::_prepMontgomery()
Referenced by BigInteger\_reduce().
NONE
const NONE = 4
See also
BigInteger::__clone()
Referenced by BigInteger\_reduce().
POWEROF2
const POWEROF2 = 2
See also
BigInteger::_mod2()
Referenced by BigInteger\_reduce().
SIGN
const SIGN = 1
$result[self::SIGN] contains the sign.
Referenced by BigInteger\_add(), BigInteger\_subtract(), BigInteger\add(), BigInteger\multiply(), and BigInteger\subtract().
VALUE
const VALUE = 0
#- #+ Array constants
Rather than create a thousands and thousands of new BigInteger objects in repeated function calls to add() and multiply() or whatever, we'll just work directly on arrays, taking them in as parameters and returning them.
@access private $result[self::VALUE] contains the value.
Referenced by BigInteger\_barrett(), BigInteger\_karatsuba(), BigInteger\_karatsubaSquare(), BigInteger\_montgomery(), BigInteger\_montgomeryMultiply(), BigInteger\_regularBarrett(), BigInteger\add(), BigInteger\multiply(), and BigInteger\subtract().
VARIABLE
const VARIABLE = 0
#- #+ @access private
See also
BigInteger::_montgomery()
BigInteger::_barrett() Cache constants
$cache[self::VARIABLE] tells us whether or not the cached data is still valid.
Referenced by BigInteger\_barrett(), BigInteger\_montgomery(), BigInteger\_montgomeryMultiply(), and BigInteger\_regularBarrett().
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/Math/BigInteger.php