Utopszkij_db: X509 Class Reference
X509 Class Reference
Public Member Functions
__construct ()
loadX509 ($cert, $mode=self::FORMAT_AUTO_DETECT)
saveX509 ($cert, $format=self::FORMAT_PEM)
_mapInExtensions (&$root, $path, $asn1)
_mapOutExtensions (&$root, $path, $asn1)
_mapInAttributes (&$root, $path, $asn1)
_mapOutAttributes (&$root, $path, $asn1)
_mapInDNs (&$root, $path, $asn1)
_mapOutDNs (&$root, $path, $asn1)
_getMapping ($extnId)
loadCA ($cert)
validateURL ($url)
validateDate ($date=null)
_testForIntermediate ($caonly, $count)
validateSignature ($caonly=true)
_validateSignatureCountable ($caonly, $count)
_validateSignature ($publicKeyAlgorithm, $publicKey, $signatureAlgorithm, $signature, $signatureSubject)
_reformatKey ($algorithm, $key)
_decodeIP ($ip)
_decodeNameConstraintIP ($ip)
_encodeIP ($ip)
_translateDNProp ($propName)
setDNProp ($propName, $propValue, $type='utf8String')
removeDNProp ($propName)
getDNProp ($propName, $dn=null, $withType=false)
setDN ($dn, $merge=false, $type='utf8String')
getDN ($format=self::DN_ARRAY, $dn=null)
getIssuerDN ($format=self::DN_ARRAY)
getSubjectDN ($format=self::DN_ARRAY)
getIssuerDNProp ($propName, $withType=false)
getSubjectDNProp ($propName, $withType=false)
getChain ()
setPublicKey ($key)
setPrivateKey ($key)
setChallenge ($challenge)
getPublicKey ()
loadCSR ($csr, $mode=self::FORMAT_AUTO_DETECT)
saveCSR ($csr, $format=self::FORMAT_PEM)
loadSPKAC ($spkac)
saveSPKAC ($spkac, $format=self::FORMAT_PEM)
loadCRL ($crl, $mode=self::FORMAT_AUTO_DETECT)
saveCRL ($crl, $format=self::FORMAT_PEM)
_timeField ($date)
sign ($issuer, $subject, $signatureAlgorithm='sha1WithRSAEncryption')
signCSR ($signatureAlgorithm='sha1WithRSAEncryption')
signSPKAC ($signatureAlgorithm='sha1WithRSAEncryption')
signCRL ($issuer, $crl, $signatureAlgorithm='sha1WithRSAEncryption')
_sign ($key, $signatureAlgorithm)
setStartDate ($date)
setEndDate ($date)
setSerialNumber ($serial, $base=-256)
makeCA ()
_isSubArrayValid ($root, $path)
& _subArrayUnchecked (&$root, $path, $create=false)
& _subArray (&$root, $path, $create=false)
& _extensions (&$root, $path=null, $create=false)
_removeExtension ($id, $path=null)
_getExtension ($id, $cert=null, $path=null)
_getExtensions ($cert=null, $path=null)
_setExtension ($id, $value, $critical=false, $replace=true, $path=null)
removeExtension ($id)
getExtension ($id, $cert=null)
getExtensions ($cert=null)
setExtension ($id, $value, $critical=false, $replace=true)
removeAttribute ($id, $disposition=self::ATTR_ALL)
getAttribute ($id, $disposition=self::ATTR_ALL, $csr=null)
getAttributes ($csr=null)
setAttribute ($id, $value, $disposition=self::ATTR_ALL)
setKeyIdentifier ($value)
computeKeyIdentifier ($key=null, $method=1)
_formatSubjectPublicKey ()
setDomain ()
setIPAddress ()
_dnsName ($domain)
_iPAddress ($address)
_revokedCertificate (&$rclist, $serial, $create=false)
revoke ($serial, $date=null)
unrevoke ($serial)
getRevoked ($serial)
listRevoked ($crl=null)
removeRevokedCertificateExtension ($serial, $id)
getRevokedCertificateExtension ($serial, $id, $crl=null)
getRevokedCertificateExtensions ($serial, $crl=null)
setRevokedCertificateExtension ($serial, $id, $value, $critical=false, $replace=true)
_extractBER ($str)
getOID ($name)
Static Public Member Functions
static _fetchURL ($url)
static setRecurLimit ($count)
static disableURLFetch ()
static enableURLFetch ()
Public Attributes
const VALIDATE_SIGNATURE_BY_CA = 1
const DN_ARRAY = 0
const DN_STRING = 1
const DN_ASN1 = 2
const DN_OPENSSL = 3
const DN_CANON = 4
const DN_HASH = 5
const FORMAT_PEM = 0
const FORMAT_DER = 1
const FORMAT_SPKAC = 2
const FORMAT_AUTO_DETECT = 3
const ATTR_ALL = -1
const ATTR_APPEND = -2
const ATTR_REPLACE = -3
$Certificate
$DirectoryString
$PKCS9String
$AttributeValue
$Extensions
$KeyUsage
$ExtKeyUsageSyntax
$BasicConstraints
$KeyIdentifier
$CRLDistributionPoints
$AuthorityKeyIdentifier
$CertificatePolicies
$AuthorityInfoAccessSyntax
$SubjectAltName
$SubjectDirectoryAttributes
$PrivateKeyUsagePeriod
$IssuerAltName
$PolicyMappings
$NameConstraints
$CPSuri
$UserNotice
$netscape_cert_type
$netscape_comment
$netscape_ca_policy_url
$Name
$RelativeDistinguishedName
$CRLNumber
$CRLReason
$IssuingDistributionPoint
$InvalidityDate
$CertificateIssuer
$HoldInstructionCode
$SignedPublicKeyAndChallenge
$PostalAddress
$CertificationRequest
$CertificateList
$dn
$publicKey
$privateKey
$oids
$CAs
$currentCert
$signatureSubject
$startDate
$endDate
$serialNumber
$currentKeyIdentifier
$caFlag = false
$challenge
Static Public Attributes
static $recur_limit = 5
static $disable_url_fetch = false
Constructor & Destructor Documentation
__construct()
__construct ()
Default Constructor.
Returns
\phpseclib\File\X509 @access public
Member Function Documentation
_decodeIP()
_decodeIP ($ip)
Decodes an IP address
Takes in a base64 encoded "blob" and returns a human readable IP address
Parameters
string $ip @access private
Returns
string
_decodeNameConstraintIP()
_decodeNameConstraintIP ($ip)
Decodes an IP address in a name constraints extension
Takes in a base64 encoded "blob" and returns a human readable IP address / mask
Parameters
string $ip @access private
Returns
array
_dnsName()
_dnsName ($domain)
Helper function to build domain array
@access private
Parameters
string $domain
Returns
array
_encodeIP()
_encodeIP ($ip)
Encodes an IP address
Takes a human readable IP address into a base64-encoded "blob"
Parameters
string | array $ip @access private
Returns
string
_extensions()
& _extensions (& $root, $path = null, $create = false)
Get a reference to an extension subarray
Parameters
array $root
string $path optional absolute path with / as component separator
bool $create optional @access private
Returns
array|false
Referenced by X509\_getExtension(), X509\_getExtensions(), X509\_removeExtension(), and X509\_setExtension().
_extractBER()
_extractBER ($str)
Extract raw BER from Base64 encoding
@access private
Parameters
string $str
Returns
string
Referenced by X509\computeKeyIdentifier(), X509\loadCRL(), X509\loadCSR(), and X509\loadX509().
_fetchURL()
static _fetchURL ($url) static
Fetches a URL
Parameters
string $url @access private
Returns
bool|string
_formatSubjectPublicKey()
_formatSubjectPublicKey ()
Format a public key as appropriate
@access private
Returns
array
Referenced by X509\signCSR(), and X509\signSPKAC().
_getExtension()
_getExtension ($id, $cert = null, $path = null)
Get an Extension
Returns the extension if it exists and false if not
Parameters
string $id
array $cert optional
string $path optional @access private
Returns
mixed
Referenced by X509\getExtension(), and X509\getRevokedCertificateExtension().
_getExtensions()
_getExtensions ($cert = null, $path = null)
Returns a list of all extensions in use
Parameters
array $cert optional
string $path optional @access private
Returns
array
Referenced by X509\getExtensions(), and X509\getRevokedCertificateExtensions().
_getMapping()
_getMapping ($extnId)
Associate an extension ID to an extension mapping
Parameters
string $extnId @access private
Returns
mixed
Referenced by X509\_mapInAttributes(), X509\_mapInDNs(), X509\_mapInExtensions(), X509\_mapOutAttributes(), X509\_mapOutDNs(), X509\_mapOutExtensions(), and X509\getDNProp().
_iPAddress()
_iPAddress ($address)
Helper function to build IP Address array
(IPv6 is not currently supported)
@access private
Parameters
string $address
Returns
array
_isSubArrayValid()
_isSubArrayValid ($root, $path)
Check for validity of subarray
This is intended for use in conjunction with _subArrayUnchecked(), implementing the checks included in _subArray() but without copying a potentially large array by passing its reference by-value to is_array().
Parameters
array $root
string $path
Returns
boolean @access private
Referenced by X509\_mapInAttributes(), X509\loadCRL(), and X509\loadX509().
_mapInAttributes()
_mapInAttributes (& $root, $path, $asn1)
Map attribute values from ANY type to attribute-specific internal format.
Parameters
array $root (by reference)
string $path
object $asn1 @access private
Referenced by X509\loadCSR().
_mapInDNs()
_mapInDNs (& $root, $path, $asn1)
Map DN values from ANY type to DN-specific internal format.
Parameters
array $root (by reference)
string $path
object $asn1 @access private
Referenced by X509\loadCRL(), X509\loadCSR(), and X509\loadX509().
_mapInExtensions()
_mapInExtensions (& $root, $path, $asn1)
Map extension values from octet string to extension-specific internal format.
Parameters
array $root (by reference)
string $path
object $asn1 @access private
Referenced by X509\_mapInAttributes(), X509\loadCRL(), and X509\loadX509().
_mapOutAttributes()
_mapOutAttributes (& $root, $path, $asn1)
Map attribute values from attribute-specific internal format to ANY type.
Parameters
array $root (by reference)
string $path
object $asn1 @access private
Referenced by X509\saveCSR().
_mapOutDNs()
_mapOutDNs (& $root, $path, $asn1)
Map DN values from DN-specific internal format to ANY type.
Parameters
array $root (by reference)
string $path
object $asn1 @access private
Referenced by X509\getDN(), X509\getDNProp(), X509\saveCRL(), X509\saveCSR(), and X509\saveX509().
_mapOutExtensions()
_mapOutExtensions (& $root, $path, $asn1)
Map extension values from extension-specific internal format to octet string.
Parameters
array $root (by reference)
string $path
object $asn1 @access private
Referenced by X509\_mapOutAttributes(), X509\saveCRL(), and X509\saveX509().
_reformatKey()
_reformatKey ($algorithm, $key)
Reformat public keys
Reformats a public key to a format supported by phpseclib (if applicable)
Parameters
string $algorithm
string $key @access private
Returns
string
Referenced by X509\loadCSR(), X509\loadSPKAC(), and X509\loadX509().
_removeExtension()
_removeExtension ($id, $path = null)
Remove an Extension
Parameters
string $id
string $path optional @access private
Returns
bool
Referenced by X509\removeExtension(), and X509\removeRevokedCertificateExtension().
_revokedCertificate()
_revokedCertificate (& $rclist, $serial, $create = false)
Get the index of a revoked certificate.
Parameters
array $rclist
string $serial
bool $create optional @access private
Returns
int|false
Referenced by X509\getRevoked(), X509\getRevokedCertificateExtension(), X509\getRevokedCertificateExtensions(), X509\removeRevokedCertificateExtension(), X509\revoke(), X509\setRevokedCertificateExtension(), and X509\unrevoke().
_setExtension()
_setExtension ($id, $value, $critical = false, $replace = true, $path = null)
Set an Extension
Parameters
string $id
mixed $value
bool $critical optional
bool $replace optional
string $path optional @access private
Returns
bool
Referenced by X509\setExtension(), and X509\setRevokedCertificateExtension().
_sign()
_sign ($key, $signatureAlgorithm)
X.509 certificate signing helper function.
Parameters
\phpseclib\File\X509 $key
string $signatureAlgorithm @access public
Returns
mixed
Referenced by X509\sign(), X509\signCRL(), X509\signCSR(), and X509\signSPKAC().
_subArray()
& _subArray (& $root, $path, $create = false)
Get a reference to a subarray
Parameters
array $root
string $path absolute path with / as component separator
bool $create optional @access private
Returns
array|false
Referenced by X509\_extensions(), X509\_mapInAttributes(), X509\_mapInDNs(), X509\_mapOutAttributes(), X509\_mapOutDNs(), X509\_mapOutExtensions(), X509\getAttribute(), X509\getAttributes(), X509\getPublicKey(), X509\getRevoked(), X509\getRevokedCertificateExtension(), X509\getRevokedCertificateExtensions(), X509\listRevoked(), X509\removeAttribute(), X509\removeRevokedCertificateExtension(), X509\revoke(), X509\saveCRL(), X509\saveCSR(), X509\saveSPKAC(), X509\saveX509(), X509\setAttribute(), X509\setRevokedCertificateExtension(), and X509\unrevoke().
_subArrayUnchecked()
& _subArrayUnchecked (& $root, $path, $create = false)
Get a reference to a subarray
This variant of _subArray() does no is_array() checking, so $root should be checked with _isSubArrayValid() first.
This is here for performance reasons: Passing a reference (i.e. $root) by-value (i.e. to is_array()) creates a copy. If $root is an especially large array, this is expensive.
Parameters
array $root
string $path absolute path with / as component separator
bool $create optional @access private
Returns
array|false
Referenced by X509\_mapInExtensions(), and X509\loadCRL().
_testForIntermediate()
_testForIntermediate ($caonly, $count)
Validates an intermediate cert as identified via authority info access extension
See https://tools.ietf.org/html/rfc4325 for more info
Parameters
bool $caonly
int $count @access private
Returns
bool
Referenced by X509\_validateSignatureCountable().
_timeField()
_timeField ($date)
Helper function to build a time field according to RFC 3280 section
4.1.2.5 Validity
5.1.2.4 This Update
5.1.2.5 Next Update
5.1.2.6 Revoked Certificates by choosing utcTime iff year of date given is before 2050 and generalTime else.
Parameters
string $date in format date('D, d M Y H:i:s O') @access private
Returns
array
Referenced by X509\_revokedCertificate(), X509\revoke(), X509\sign(), and X509\signCRL().
_translateDNProp()
_translateDNProp ($propName)
"Normalizes" a Distinguished Name property
Parameters
string $propName @access private
Returns
mixed
Referenced by X509\getDNProp(), X509\removeDNProp(), and X509\setDNProp().
_validateSignature()
_validateSignature ($publicKeyAlgorithm, $publicKey, $signatureAlgorithm, $signature, $signatureSubject)
Validates a signature
Returns true if the signature is verified, false if it is not correct or null on error
Parameters
string $publicKeyAlgorithm
string $publicKey
string $signatureAlgorithm
string $signature
string $signatureSubject @access private
Returns
int
Referenced by X509\_validateSignatureCountable().
_validateSignatureCountable()
_validateSignatureCountable ($caonly, $count)
Validate a signature
Performs said validation whilst keeping track of how many times validation method is called
Parameters
bool $caonly
int $count @access private
Returns
mixed
Referenced by X509\validateSignature().
computeKeyIdentifier()
computeKeyIdentifier ($key = null, $method = 1)
Compute a public key identifier.
Although key identifiers may be set to any unique value, this function computes key identifiers from public key according to the two recommended methods (4.2.1.2 RFC 3280). Highly polymorphic: try to accept all possible forms of key:
Key object
\phpseclib\File\X509 object with public or private key defined
Certificate or CSR array
\phpseclib\File\ASN1\Element object
PEM or DER string
Parameters
mixed $key optional
int $method optional @access public
Returns
string binary key identifier
Referenced by X509\computeKeyIdentifier(), and X509\sign().
disableURLFetch()
static disableURLFetch () static
Prevents URIs from being automatically retrieved
@access public
enableURLFetch()
static enableURLFetch () static
Allows URIs to be automatically retrieved
@access public
getAttribute()
getAttribute ($id, $disposition = self::ATTR_ALL, $csr = null)
Get a CSR attribute
Returns the attribute if it exists and false if not
Parameters
string $id
int $disposition optional
array $csr optional @access public
Returns
mixed
getAttributes()
getAttributes ($csr = null)
Returns a list of all CSR attributes in use
Parameters
array $csr optional @access public
Returns
array
getChain()
getChain ()
Get the certificate chain for the current cert
@access public
Returns
mixed
getDN()
getDN ($format = self::DN_ARRAY, $dn = null)
Get the Distinguished Name for a certificates subject
Parameters
mixed $format optional
array $dn optional @access public
Returns
bool
Referenced by X509\_validateSignatureCountable(), X509\getDN(), X509\getIssuerDN(), and X509\getSubjectDN().
getDNProp()
getDNProp ($propName, $dn = null, $withType = false)
Get Distinguished Name properties
Parameters
string $propName
array $dn optional
bool $withType optional
Returns
mixed @access public
Referenced by X509\getIssuerDNProp(), X509\getSubjectDNProp(), and X509\validateURL().
getExtension()
getExtension ($id, $cert = null)
Get a certificate, CSR or CRL Extension
Returns the extension if it exists and false if not
Parameters
string $id
array $cert optional @access public
Returns
mixed
Referenced by X509\_testForIntermediate(), X509\_validateSignatureCountable(), X509\getChain(), X509\loadX509(), X509\sign(), X509\signCRL(), and X509\validateURL().
getExtensions()
getExtensions ($cert = null)
Returns a list of all extensions in use in certificate, CSR or CRL
Parameters
array $cert optional @access public
Returns
array
getIssuerDN()
getIssuerDN ($format = self::DN_ARRAY)
Get the Distinguished Name for a certificate/crl issuer
Parameters
int $format optional @access public
Returns
mixed
Referenced by X509\_validateSignatureCountable().
getIssuerDNProp()
getIssuerDNProp ($propName, $withType = false)
Get an individual Distinguished Name property for a certificate/crl issuer
Parameters
string $propName
bool $withType optional @access public
Returns
mixed
getOID()
getOID ($name)
Returns the OID corresponding to a name
What's returned in the associative array returned by loadX509() (or load*()) is either a name or an OID if no OID to name mapping is available. The problem with this is that what may be an unmapped OID in one version of phpseclib may not be unmapped in the next version, so apps that are looking at this OID may not be able to work from version to version.
This method will return the OID if a name is passed to it and if no mapping is avialable it'll assume that what's being passed to it already is an OID and return that instead. A few examples.
getOID('2.16.840.1.101.3.4.2.1') == '2.16.840.1.101.3.4.2.1' getOID('id-sha256') == '2.16.840.1.101.3.4.2.1' getOID('zzz') == 'zzz'
@access public
Returns
string
getPublicKey()
getPublicKey ()
Gets the public key
Returns a \phpseclib\Crypt\RSA object or a false.
@access public
Returns
mixed
getRevoked()
getRevoked ($serial)
Get a revoked certificate.
Parameters
string $serial @access public
Returns
mixed
getRevokedCertificateExtension()
getRevokedCertificateExtension ($serial, $id, $crl = null)
Get a Revoked Certificate Extension
Returns the extension if it exists and false if not
Parameters
string $serial
string $id
array $crl optional @access public
Returns
mixed
getRevokedCertificateExtensions()
getRevokedCertificateExtensions ($serial, $crl = null)
Returns a list of all extensions in use for a given revoked certificate
Parameters
string $serial
array $crl optional @access public
Returns
array
getSubjectDN()
getSubjectDN ($format = self::DN_ARRAY)
Get the Distinguished Name for a certificate/csr subject Alias of getDN()
Parameters
int $format optional @access public
Returns
mixed
getSubjectDNProp()
getSubjectDNProp ($propName, $withType = false)
Get an individual Distinguished Name property for a certificate/csr subject
Parameters
string $propName
bool $withType optional @access public
Returns
mixed
listRevoked()
listRevoked ($crl = null)
List revoked certificates
Parameters
array $crl optional @access public
Returns
array
loadCA()
loadCA ($cert)
Load an X.509 certificate as a certificate authority
Parameters
string $cert @access public
Returns
bool
loadCRL()
loadCRL ($crl, $mode = self::FORMAT_AUTO_DETECT)
Load a Certificate Revocation List
Parameters
string $crl
int $mode @access public
Returns
mixed
Referenced by X509\signCRL().
loadCSR()
loadCSR ($csr, $mode = self::FORMAT_AUTO_DETECT)
Load a Certificate Signing Request
Parameters
string | array $csr
int $mode @access public
Returns
mixed
Referenced by X509\signCSR().
loadSPKAC()
loadSPKAC ($spkac)
Load a SPKAC CSR
SPKAC's are produced by the HTML5 keygen element:
https://developer.mozilla.org/en-US/docs/HTML/Element/keygen
Parameters
string | array $spkac @access public
Returns
mixed
Referenced by X509\signSPKAC().
loadX509()
loadX509 ($cert, $mode = self::FORMAT_AUTO_DETECT)
Load X.509 certificate
Returns an associative array describing the X.509 cert or a false if the cert failed to load
Parameters
string $cert
int $mode @access public
Returns
mixed
Referenced by X509\loadCA(), and X509\sign().
makeCA()
makeCA ()
Turns the certificate into a certificate authority
@access public
removeAttribute()
removeAttribute ($id, $disposition = self::ATTR_ALL)
Remove a CSR attribute.
Parameters
string $id
int $disposition optional @access public
Returns
bool
Referenced by X509\setAttribute().
removeDNProp()
removeDNProp ($propName)
Remove Distinguished Name properties
Parameters
string $propName @access public
Referenced by X509\setDomain().
removeExtension()
removeExtension ($id)
Remove a certificate, CSR or CRL Extension
Parameters
string $id @access public
Returns
bool
Referenced by X509\sign(), and X509\signCRL().
removeRevokedCertificateExtension()
removeRevokedCertificateExtension ($serial, $id)
Remove a Revoked Certificate Extension
Parameters
string $serial
string $id @access public
Returns
bool
revoke()
revoke ($serial, $date = null)
Revoke a certificate.
Parameters
string $serial
string $date optional @access public
Returns
bool
saveCRL()
saveCRL ($crl, $format = self::FORMAT_PEM)
Save Certificate Revocation List.
Parameters
array $crl
int $format optional @access public
Returns
string
Referenced by X509\signCRL().
saveCSR()
saveCSR ($csr, $format = self::FORMAT_PEM)
Save CSR request
Parameters
array $csr
int $format optional @access public
Returns
string
Referenced by X509\signCSR().
saveSPKAC()
saveSPKAC ($spkac, $format = self::FORMAT_PEM)
Save a SPKAC CSR request
Parameters
string | array $spkac
int $format optional @access public
Returns
string
Referenced by X509\signSPKAC().
saveX509()
saveX509 ($cert, $format = self::FORMAT_PEM)
Save X.509 certificate
Parameters
array $cert
int $format optional @access public
Returns
string
Referenced by X509\sign().
setAttribute()
setAttribute ($id, $value, $disposition = self::ATTR_ALL)
Set a CSR attribute
Parameters
string $id
mixed $value
bool $disposition optional @access public
Returns
bool
setChallenge()
setChallenge ($challenge)
Set challenge
Used for SPKAC CSR's
Parameters
string $challenge @access public
setDN()
setDN ($dn, $merge = false, $type = 'utf8String')
Set a Distinguished Name
Parameters
mixed $dn
bool $merge optional
string $type optional @access public
Returns
bool
setDNProp()
setDNProp ($propName, $propValue, $type = 'utf8String')
Set a Distinguished Name property
Parameters
string $propName
mixed $propValue
string $type optional @access public
Returns
bool
Referenced by X509\setDN(), and X509\setDomain().
setDomain()
setDomain ()
Set the domain name's which the cert is to be valid for
@access public
Returns
array
setEndDate()
setEndDate ($date)
Set certificate end date
Parameters
string $date @access public
setExtension()
setExtension ($id, $value, $critical = false, $replace = true)
Set a certificate, CSR or CRL Extension
Parameters
string $id
mixed $value
bool $critical optional
bool $replace optional @access public
Returns
bool
Referenced by X509\sign(), and X509\signCRL().
setIPAddress()
setIPAddress ()
Set the IP Addresses's which the cert is to be valid for
@access public
setKeyIdentifier()
setKeyIdentifier ($value)
Sets the subject key identifier
This is used by the id-ce-authorityKeyIdentifier and the id-ce-subjectKeyIdentifier extensions.
Parameters
string $value @access public
setPrivateKey()
setPrivateKey ($key)
Set private key
Key needs to be a \phpseclib\Crypt\RSA object
Parameters
object $key @access public
setPublicKey()
setPublicKey ($key)
Set public key
Key needs to be a \phpseclib\Crypt\RSA object
Parameters
object $key @access public
Returns
bool
setRecurLimit()
static setRecurLimit ($count) static
Sets the recursion limit
When validating a signature it may be necessary to download intermediate certs from URI's. An intermediate cert that linked to itself would result in an infinite loop so to prevent that we set a recursion limit. A negative number means that there is no recursion limit.
Parameters
int $count @access public
setRevokedCertificateExtension()
setRevokedCertificateExtension ($serial, $id, $value, $critical = false, $replace = true)
Set a Revoked Certificate Extension
Parameters
string $serial
string $id
mixed $value
bool $critical optional
bool $replace optional @access public
Returns
bool
setSerialNumber()
setSerialNumber ($serial, $base = -256)
Set Serial Number
Parameters
string $serial
int $base optional @access public
setStartDate()
setStartDate ($date)
Set certificate start date
Parameters
string $date @access public
sign()
sign ($issuer, $subject, $signatureAlgorithm = 'sha1WithRSAEncryption')
Sign an X.509 certificate
$issuer's private key needs to be loaded. $subject can be either an existing X.509 cert (if you want to resign it), a CSR or something with the DN and public key explicitly set.
Parameters
\phpseclib\File\X509 $issuer
\phpseclib\File\X509 $subject
string $signatureAlgorithm optional @access public
Returns
mixed
signCRL()
signCRL ($issuer, $crl, $signatureAlgorithm = 'sha1WithRSAEncryption')
Sign a CRL
$issuer's private key needs to be loaded.
Parameters
\phpseclib\File\X509 $issuer
\phpseclib\File\X509 $crl
string $signatureAlgorithm optional @access public
Returns
mixed
signCSR()
signCSR ($signatureAlgorithm = 'sha1WithRSAEncryption')
Sign a CSR
@access public
Returns
mixed
signSPKAC()
signSPKAC ($signatureAlgorithm = 'sha1WithRSAEncryption')
Sign a SPKAC
@access public
Returns
mixed
unrevoke()
unrevoke ($serial)
Unrevoke a certificate.
Parameters
string $serial @access public
Returns
bool
validateDate()
validateDate ($date = null)
Validate a date
If $date isn't defined it is assumed to be the current date.
Parameters
\DateTime | string $date optional @access public
validateSignature()
validateSignature ($caonly = true)
Validate a signature
Works on X.509 certs, CSR's and CRL's. Returns true if the signature is verified, false if it is not correct or null on error
By default returns false for self-signed certs. Call validateSignature(false) to make this support self-signed.
The behavior of this function is inspired by openssl_verify.
Parameters
bool $caonly optional @access public
Returns
mixed
Referenced by X509\_validateSignatureCountable().
validateURL()
validateURL ($url)
Validate an X.509 certificate against a URL
From RFC2818 "HTTP over TLS":
Matching is performed using the matching rules specified by [RFC2459]. If more than one identity of a given type is present in the certificate (e.g., more than one dNSName name, a match in any one of the set is considered acceptable.) Names may contain the wildcard character * which is considered to match any single domain name component or component fragment. E.g., *.a.com matches foo.a.com but not bar.foo.a.com. f*.com matches foo.com but not bar.com.
Parameters
string $url @access public
Returns
bool
Member Data Documentation
$DirectoryString
$DirectoryString
#+ ASN.1 syntax for various extensions
@access private
Referenced by X509\_getMapping().
$PostalAddress
$PostalAddress
#- #+ ASN.1 syntax for various DN attributes
@access private
Referenced by X509\_getMapping().
ATTR_ALL
const ATTR_ALL = -1
#- Attribute value disposition. If disposition is >= 0, this is the index of the target value.
Referenced by X509\getAttribute(), X509\removeAttribute(), and X509\setAttribute().
DN_ARRAY
const DN_ARRAY = 0
#+ @access public
See also
\phpseclib\File\X509::getDN() Return internal array representation
Referenced by X509\getDN().
DN_ASN1
const DN_ASN1 = 2
Return ASN.1 name string
Referenced by X509\getDN().
DN_CANON
const DN_CANON = 4
Return canonical ASN.1 RDNs string
Referenced by X509\getDN().
DN_HASH
const DN_HASH = 5
Return name hash for file indexing
Referenced by X509\getDN().
DN_OPENSSL
const DN_OPENSSL = 3
Return OpenSSL compatible array
DN_STRING
const DN_STRING = 1
Return string
FORMAT_AUTO_DETECT
const FORMAT_AUTO_DETECT = 3
Auto-detect the format
Used only by the load*() functions
FORMAT_DER
const FORMAT_DER = 1
Save as DER
Referenced by X509\saveCRL(), X509\saveCSR(), X509\saveSPKAC(), and X509\saveX509().
FORMAT_PEM
const FORMAT_PEM = 0
#- #+ @access public
See also
\phpseclib\File\X509::saveX509()
\phpseclib\File\X509::saveCSR()
\phpseclib\File\X509::saveCRL() Save as PEM
ie. a base64-encoded PEM with a header and a footer
FORMAT_SPKAC
const FORMAT_SPKAC = 2
Save as a SPKAC
Only works on CSRs. Not currently supported.
VALIDATE_SIGNATURE_BY_CA
const VALIDATE_SIGNATURE_BY_CA = 1
Flag to only accept signatures signed by certificate authorities
Not really used anymore but retained all the same to suppress E_NOTICEs from old installs
@access public
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/File/X509.php