Utopszkij_db: Utils Class Reference
Utils Class Reference
Static Public Member Functions
static caselessRemove (array $keys, array $data)
static copyToStream (StreamInterface $source, StreamInterface $dest, int $maxLen=-1)
static copyToString (StreamInterface $stream, int $maxLen=-1)
static hash (StreamInterface $stream, string $algo, bool $rawOutput=false)
static modifyRequest (RequestInterface $request, array $changes)
static readLine (StreamInterface $stream, ?int $maxLength=null)
static uriFor ($uri)
Member Function Documentation
caselessRemove()
static caselessRemove (array $keys, array $data) static
Remove the items given by the keys, case insensitively from the data.
Parameters
string[] $keys
Referenced by Utils\modifyRequest().
copyToStream()
static copyToStream (StreamInterface $source, StreamInterface $dest, int $maxLen = -1) static
Copy the contents of a stream into another stream until the given number of bytes have been read.
Parameters
StreamInterface $source Stream to read from
StreamInterface $dest Stream to write to
int $maxLen Maximum number of bytes to read. Pass -1 to read the entire stream.
Exceptions
RuntimeException on error.
Referenced by UploadedFile\moveTo().
copyToString()
static copyToString (StreamInterface $stream, int $maxLen = -1) static
Copy the contents of a stream into a string until the given number of bytes have been read.
Parameters
StreamInterface $stream Stream to read
int $maxLen Maximum number of bytes to read. Pass -1 to read the entire stream.
Exceptions
RuntimeException on error.
Referenced by PumpStream\__toString(), and AppendStream\getContents().
hash()
static hash (StreamInterface $stream, string $algo, bool $rawOutput = false) static
Calculate a hash of a stream.
This method reads the entire stream to calculate a rolling hash, based on PHP's hash_init functions.
Parameters
StreamInterface $stream Stream to calculate the hash for
string $algo Hash algorithm (e.g. md5, crc32, etc)
bool $rawOutput Whether or not to use raw output
Exceptions
RuntimeException on error.
modifyRequest()
static modifyRequest (RequestInterface $request, array $changes) static
Clone and modify a request with the given changes.
This method is useful for reducing the number of clones needed to mutate a message.
The changes can be one of:
method: (string) Changes the HTTP method.
set_headers: (array) Sets the given headers.
remove_headers: (array) Remove the given headers.
body: (mixed) Sets the given body.
uri: (UriInterface) Set the URI.
query: (string) Set the query string value of the URI.
version: (string) Set the protocol version.
Parameters
RequestInterface $request Request to clone and modify.
array $changes Changes to apply.
readLine()
static readLine (StreamInterface $stream, ?int $maxLength = null) static
Read a line from the stream up to the maximum allowed buffer length.
Parameters
StreamInterface $stream Stream to read from
int | null $maxLength Maximum buffer length
uriFor()
static uriFor ($uri) static
Returns a UriInterface for the given value.
This function accepts a string or UriInterface and returns a UriInterface for the given value. If the value is already a UriInterface, it is returned as-is.
Parameters
string | UriInterface $uri
Exceptions
InvalidArgumentException
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/guzzlehttp/psr7/src/Utils.php