Utopszkij_db: BtreeNode Class Reference
BtreeNode Class Reference
Public Member Functions
__construct (string $value, $data)
saveToDB ()
insertChild (string $value, $data)
getFirstChild ()
getLastChild ()
find (string $value)
getNext ()
getPrevious ()
Static Public Member Functions
static readFromDB (string $id)
Static Public Member Functions inherited from Storage
static write ($record)
static update (string $id, $record)
static read (string $id)
static write ($record)
static update ($id, $record)
static read (string $id)
Public Attributes
string $left
string $right
string $parent
string $id
string $value
$data
Detailed Description
Btree kezelő törlés ezen a szinet nincs kmegvalósítva
Member Function Documentation
find()
find (string $value)
kerresés ha több van az elsőt adja vissza
Parameters
string $value
Returns
BtreeNode ha nem talált {id: '', ...}
getFirstChild()
getFirstChild ()
legkisebb child elérése,
Returns
BtreeNode ha nincs ilyen akkor {id:"",....}
getLastChild()
getLastChild ()
legnagyobb child elérése
Returns
BtreeNode ha nincs ilyen akkor {id:"",....}
getNext()
getNext ()
Következő node elérése
Returns
BtreeNode ha nincs return {id:''}
getPrevious()
getPrevious ()
elöző node elérése, ha nincs return {id:''}
Returns
BtreeNode ha nincs return {id:''}
insertChild()
insertChild (string $value, $data)
Új child node beillesztése
Parameters
string $value
string $data
Returns
BtreeNode
readFromDB()
static readFromDB (string $id) static
node olvasás a $storgae -ból
Parameters
string $id
Returns
BtreeNode
Referenced by Collection\__construct(), Collection\create(), Collection\deleteById(), Collection\getByFilter(), Collection\getById(), and Collection\updateById().
saveToDB()
saveToDB ()
node tárolása a $storage -ba
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/btree.php