Utopszkij_db: Uri Class Reference
Uri Class Reference
Public Member Functions
__construct (string $uri='')
__toString ()
getScheme ()
getAuthority ()
getUserInfo ()
getHost ()
getPort ()
getPath ()
getQuery ()
getFragment ()
withScheme ($scheme)
withUserInfo ($user, $password=null)
withHost ($host)
withPort ($port)
withPath ($path)
withQuery ($query)
withFragment ($fragment)
jsonSerialize ()
getScheme ()
getAuthority ()
getUserInfo ()
getHost ()
getPort ()
getPath ()
getQuery ()
getFragment ()
withScheme ($scheme)
withUserInfo ($user, $password=null)
withHost ($host)
withPort ($port)
withPath ($path)
withQuery ($query)
withFragment ($fragment)
__toString ()
Static Public Member Functions
static composeComponents (?string $scheme, ?string $authority, string $path, ?string $query, ?string $fragment)
static isDefaultPort (UriInterface $uri)
static isAbsolute (UriInterface $uri)
static isNetworkPathReference (UriInterface $uri)
static isAbsolutePathReference (UriInterface $uri)
static isRelativePathReference (UriInterface $uri)
static isSameDocumentReference (UriInterface $uri, UriInterface $base=null)
static withoutQueryValue (UriInterface $uri, string $key)
static withQueryValue (UriInterface $uri, string $key, ?string $value)
static withQueryValues (UriInterface $uri, array $keyValueArray)
static fromParts (array $parts)
Detailed Description
PSR-7 URI implementation.
Author
Michael Dowling
Tobias Schultze
Matthew Weier O'Phinney
Member Function Documentation
__toString()
__toString ()
Return the string representation as a URI reference.
Depending on which components of the URI are present, the resulting string is either a full URI or relative reference according to RFC 3986, Section 4.1. The method concatenates the various components of the URI, using the appropriate delimiters:
If a scheme is present, it MUST be suffixed by ":".
If an authority is present, it MUST be prefixed by "//".
The path can be concatenated without delimiters. But there are two cases where the path has to be adjusted to make the URI reference valid as PHP does not allow to throw an exception in __toString():
If the path is rootless and an authority is present, the path MUST be prefixed by "/".
If the path is starting with more than one "/" and no authority is present, the starting slashes MUST be reduced to one.
If a query is present, it MUST be prefixed by "?".
If a fragment is present, it MUST be prefixed by "#".
See also
http://tools.ietf.org/html/rfc3986#section-4.1
Returns
string
Implements UriInterface.
composeComponents()
static composeComponents (?string $scheme, ?string $authority, string $path, ?string $query, ?string $fragment) static
Composes a URI reference string from its various components.
Usually this method does not need to be called manually but instead is used indirectly via Psr\Http\Message\UriInterface::__toString.
PSR-7 UriInterface treats an empty component the same as a missing component as getQuery(), getFragment() etc. always return a string. This explains the slight difference to RFC 3986 Section 5.3.
Another adjustment is that the authority separator is added even when the authority is missing/empty for the "file" scheme. This is because PHP stream functions like file_get_contents only work with file:///myfile but not with file:/myfile although they are equivalent according to RFC 3986. But file:/// is the more common syntax for the file scheme anyway (Chrome for example redirects to that format).
https://tools.ietf.org/html/rfc3986#section-5.3
Referenced by Uri\__toString(), and UriResolver\resolve().
fromParts()
static fromParts (array $parts) static
Creates a URI from a hash of parse_url components.
MalformedUriException If the components do not form a valid URI.
getAuthority()
getAuthority ()
Retrieve the authority component of the URI.
If no authority information is present, this method MUST return an empty string.
The authority syntax of the URI is:
[user-info@]host[:port]
If the port component is not set or is the standard port for the current scheme, it SHOULD NOT be included.
See also
https://tools.ietf.org/html/rfc3986#section-3.2
Returns
string The URI authority, in "[user-info@]host[:port]" format.
Implements UriInterface.
Referenced by Uri\__toString().
getFragment()
getFragment ()
Retrieve the fragment component of the URI.
If no fragment is present, this method MUST return an empty string.
The leading "#" character is not part of the fragment and MUST NOT be added.
The value returned MUST be percent-encoded, but MUST NOT double-encode any characters. To determine what characters to encode, please refer to RFC 3986, Sections 2 and 3.5.
See also
https://tools.ietf.org/html/rfc3986#section-2
https://tools.ietf.org/html/rfc3986#section-3.5
Returns
string The URI fragment.
Implements UriInterface.
getHost()
getHost ()
Retrieve the host component of the URI.
If no host is present, this method MUST return an empty string.
The value returned MUST be normalized to lowercase, per RFC 3986 Section 3.2.2.
See also
http://tools.ietf.org/html/rfc3986#section-3.2.2
Returns
string The URI host.
Implements UriInterface.
getPath()
getPath ()
Retrieve the path component of the URI.
The path can either be empty or absolute (starting with a slash) or rootless (not starting with a slash). Implementations MUST support all three syntaxes.
Normally, the empty path "" and absolute path "/" are considered equal as defined in RFC 7230 Section 2.7.3. But this method MUST NOT automatically do this normalization because in contexts with a trimmed base path, e.g. the front controller, this difference becomes significant. It's the task of the user to handle both "" and "/".
The value returned MUST be percent-encoded, but MUST NOT double-encode any characters. To determine what characters to encode, please refer to RFC 3986, Sections 2 and 3.3.
As an example, if the value should include a slash ("/") not intended as delimiter between path segments, that value MUST be passed in encoded form (e.g., "%2F") to the instance.
See also
https://tools.ietf.org/html/rfc3986#section-2
https://tools.ietf.org/html/rfc3986#section-3.3
Returns
string The URI path.
Implements UriInterface.
getPort()
getPort ()
Retrieve the port component of the URI.
If a port is present, and it is non-standard for the current scheme, this method MUST return it as an integer. If the port is the standard port used with the current scheme, this method SHOULD return null.
If no port is present, and no scheme is present, this method MUST return a null value.
If no port is present, but a scheme is present, this method MAY return the standard port for that scheme, but SHOULD return null.
Returns
null|int The URI port.
Implements UriInterface.
getQuery()
getQuery ()
Retrieve the query string of the URI.
If no query string is present, this method MUST return an empty string.
The leading "?" character is not part of the query and MUST NOT be added.
The value returned MUST be percent-encoded, but MUST NOT double-encode any characters. To determine what characters to encode, please refer to RFC 3986, Sections 2 and 3.4.
As an example, if a value in a key/value pair of the query string should include an ampersand ("&") not intended as a delimiter between values, that value MUST be passed in encoded form (e.g., "%26") to the instance.
See also
https://tools.ietf.org/html/rfc3986#section-2
https://tools.ietf.org/html/rfc3986#section-3.4
Returns
string The URI query string.
Implements UriInterface.
getScheme()
getScheme ()
Retrieve the scheme component of the URI.
If no scheme is present, this method MUST return an empty string.
The value returned MUST be normalized to lowercase, per RFC 3986 Section 3.1.
The trailing ":" character is not part of the scheme and MUST NOT be added.
See also
https://tools.ietf.org/html/rfc3986#section-3.1
Returns
string The URI scheme.
Implements UriInterface.
getUserInfo()
getUserInfo ()
Retrieve the user information component of the URI.
If no user information is present, this method MUST return an empty string.
If a user is present in the URI, this will return that value; additionally, if the password is also present, it will be appended to the user value, with a colon (":") separating the values.
The trailing "@" character is not part of the user information and MUST NOT be added.
Returns
string The URI user information, in "username[:password]" format.
Implements UriInterface.
isAbsolute()
static isAbsolute (UriInterface $uri) static
Whether the URI is absolute, i.e. it has a scheme.
An instance of UriInterface can either be an absolute URI or a relative reference. This method returns true if it is the former. An absolute URI has a scheme. A relative reference is used to express a URI relative to another URI, the base URI. Relative references can be divided into several forms:
network-path references, e.g. '//example.com/path'
absolute-path references, e.g. '/path'
relative-path references, e.g. 'subpath'
See also
Uri::isNetworkPathReference
Uri::isAbsolutePathReference
Uri::isRelativePathReference https://tools.ietf.org/html/rfc3986#section-4
isAbsolutePathReference()
static isAbsolutePathReference (UriInterface $uri) static
Whether the URI is a absolute-path reference.
A relative reference that begins with a single slash character is termed an absolute-path reference.
https://tools.ietf.org/html/rfc3986#section-4.2
isDefaultPort()
static isDefaultPort (UriInterface $uri) static
Whether the URI has the default port of the current scheme.
Psr\Http\Message\UriInterface::getPort may return null or the standard port. This method can be used independently of the implementation.
Referenced by UriNormalizer\normalize().
isNetworkPathReference()
static isNetworkPathReference (UriInterface $uri) static
Whether the URI is a network-path reference.
A relative reference that begins with two slash characters is termed an network-path reference.
https://tools.ietf.org/html/rfc3986#section-4.2
isRelativePathReference()
static isRelativePathReference (UriInterface $uri) static
Whether the URI is a relative-path reference.
A relative reference that does not begin with a slash character is termed a relative-path reference.
https://tools.ietf.org/html/rfc3986#section-4.2
Referenced by UriNormalizer\normalize().
isSameDocumentReference()
static isSameDocumentReference (UriInterface $uri, UriInterface $base = null) static
Whether the URI is a same-document reference.
A same-document reference refers to a URI that is, aside from its fragment component, identical to the base URI. When no base URI is given, only an empty URI reference (apart from its fragment) is considered a same-document reference.
Parameters
UriInterface $uri The URI to check
UriInterface | null $base An optional base URI to compare against
https://tools.ietf.org/html/rfc3986#section-4.4
withFragment()
withFragment ($fragment)
Return an instance with the specified URI fragment.
This method MUST retain the state of the current instance, and return an instance that contains the specified URI fragment.
Users can provide both encoded and decoded fragment characters. Implementations ensure the correct encoding as outlined in getFragment().
An empty fragment value is equivalent to removing the fragment.
Parameters
string $fragment The fragment to use with the new instance.
Returns
static A new instance with the specified fragment.
Implements UriInterface.
withHost()
withHost ($host)
Return an instance with the specified host.
This method MUST retain the state of the current instance, and return an instance that contains the specified host.
An empty host value is equivalent to removing the host.
Parameters
string $host The hostname to use with the new instance.
Returns
static A new instance with the specified host.
Exceptions
InvalidArgumentException for invalid hostnames.
Implements UriInterface.
withoutQueryValue()
static withoutQueryValue (UriInterface $uri, string $key) static
Creates a new URI with a specific query string value removed.
Any existing query string values that exactly match the provided key are removed.
Parameters
UriInterface $uri URI to use as a base.
string $key Query string key to remove.
withPath()
withPath ($path)
Return an instance with the specified path.
This method MUST retain the state of the current instance, and return an instance that contains the specified path.
The path can either be empty or absolute (starting with a slash) or rootless (not starting with a slash). Implementations MUST support all three syntaxes.
If the path is intended to be domain-relative rather than path relative then it must begin with a slash ("/"). Paths not starting with a slash ("/") are assumed to be relative to some base path known to the application or consumer.
Users can provide both encoded and decoded path characters. Implementations ensure the correct encoding as outlined in getPath().
Parameters
string $path The path to use with the new instance.
Returns
static A new instance with the specified path.
Exceptions
InvalidArgumentException for invalid paths.
Implements UriInterface.
withPort()
withPort ($port)
Return an instance with the specified port.
This method MUST retain the state of the current instance, and return an instance that contains the specified port.
Implementations MUST raise an exception for ports outside the established TCP and UDP port ranges.
A null value provided for the port is equivalent to removing the port information.
Parameters
null | int $port The port to use with the new instance; a null value removes the port information.
Returns
static A new instance with the specified port.
Exceptions
InvalidArgumentException for invalid ports.
Implements UriInterface.
withQuery()
withQuery ($query)
Return an instance with the specified query string.
This method MUST retain the state of the current instance, and return an instance that contains the specified query string.
Users can provide both encoded and decoded query characters. Implementations ensure the correct encoding as outlined in getQuery().
An empty query string value is equivalent to removing the query string.
Parameters
string $query The query string to use with the new instance.
Returns
static A new instance with the specified query string.
Exceptions
InvalidArgumentException for invalid query strings.
Implements UriInterface.
withQueryValue()
static withQueryValue (UriInterface $uri, string $key, ?string $value) static
Creates a new URI with a specific query string value.
Any existing query string values that exactly match the provided key are removed and replaced with the given key value pair.
A value of null will set the query string key without a value, e.g. "key" instead of "key=value".
Parameters
UriInterface $uri URI to use as a base.
string $key Key to set.
string | null $value Value to set
withQueryValues()
static withQueryValues (UriInterface $uri, array $keyValueArray) static
Creates a new URI with multiple specific query string values.
It has the same behavior as withQueryValue() but for an associative array of key => value.
Parameters
UriInterface $uri URI to use as a base.
array<string,string|null> $keyValueArray Associative array of key and values
withScheme()
withScheme ($scheme)
Return an instance with the specified scheme.
This method MUST retain the state of the current instance, and return an instance that contains the specified scheme.
Implementations MUST support the schemes "http" and "https" case insensitively, and MAY accommodate other schemes if required.
An empty scheme is equivalent to removing the scheme.
Parameters
string $scheme The scheme to use with the new instance.
Returns
static A new instance with the specified scheme.
Exceptions
InvalidArgumentException for invalid or unsupported schemes.
Implements UriInterface.
withUserInfo()
withUserInfo ($user, $password = null)
Return an instance with the specified user information.
This method MUST retain the state of the current instance, and return an instance that contains the specified user information.
Password is optional, but the user information MUST include the user; an empty string for the user is equivalent to removing user information.
Parameters
string $user The user name to use for authority.
null | string $password The password associated with $user.
Returns
static A new instance with the specified user information.
Implements UriInterface.
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/guzzlehttp/psr7/src/Uri.php