Utopszkij_db: ANSI Class Reference
ANSI Class Reference
Public Member Functions
__construct ()
setDimensions ($x, $y)
setHistory ($history)
loadString ($source)
appendString ($source)
_newLine ()
_processCoordinate ($last_attr, $cur_attr, $char)
_getScreen ()
getScreen ()
getHistory ()
Public Attributes
$max_x
$max_y
$max_history
$history
$history_attrs
$x
$y
$old_x
$old_y
$base_attr_cell
$attr_cell
$attr_row
$screen
$attrs
$ansi
$tokenization
Constructor & Destructor Documentation
__construct()
__construct ()
Default Constructor.
Returns
\phpseclib\File\ANSI @access public
Member Function Documentation
_getScreen()
_getScreen ()
Returns the current screen without preformating
@access private
Returns
string
_newLine()
_newLine ()
Add a new line
Also update the $this->screen and $this->history buffers
@access private
Referenced by ANSI\appendString().
_processCoordinate()
_processCoordinate ($last_attr, $cur_attr, $char)
Returns the current coordinate without preformating
@access private
Returns
string
appendString()
appendString ($source)
Appdend a string
Parameters
string $source @access public
Referenced by ANSI\loadString().
getHistory()
getHistory ()
Returns the current screen and the x previous lines
@access public
Returns
string
getScreen()
getScreen ()
Returns the current screen
@access public
Returns
string
loadString()
loadString ($source)
Load a string
Parameters
string $source @access public
setDimensions()
setDimensions ($x, $y)
Set terminal width and height
Resets the screen as well
Parameters
int $x
int $y @access public
Referenced by ANSI\__construct(), and ANSI\loadString().
setHistory()
setHistory ($history)
Set the number of lines that should be logged past the terminal height
Parameters
int $history @access public
Referenced by ANSI\__construct().
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/File/ANSI.php