Utopszkij_db: BufferStream Class Reference
BufferStream Class Reference
Public Member Functions
__construct (int $hwm=16384)
__toString ()
getContents ()
close ()
detach ()
getSize ()
isReadable ()
isWritable ()
isSeekable ()
rewind ()
seek ($offset, $whence=SEEK_SET)
eof ()
tell ()
read ($length)
write ($string)
getMetadata ($key=null)
__toString ()
close ()
detach ()
getSize ()
tell ()
eof ()
isSeekable ()
seek ($offset, $whence=SEEK_SET)
rewind ()
isWritable ()
write ($string)
isReadable ()
read ($length)
getContents ()
getMetadata ($key=null)
Detailed Description
Provides a buffer stream that can be written to to fill a buffer, and read from to remove bytes from the buffer.
This stream returns a "hwm" metadata value that tells upstream consumers what the configured high water mark of the stream is, or the maximum preferred size of the buffer.
Constructor & Destructor Documentation
__construct()
__construct (int $hwm = 16384)
Parameters
int $hwm High water mark, representing the preferred maximum buffer size. If the size of the buffer exceeds the high water mark, then calls to write will continue to succeed but will return 0 to inform writers to slow down until the buffer has been drained by reading from it.
Member Function Documentation
__toString()
__toString ()
Reads all data from the stream into a string, from the beginning to end.
This method MUST attempt to seek to the beginning of the stream before reading data and read the stream until the end is reached.
Warning: This could attempt to load a large amount of data into memory.
This method MUST NOT raise an exception in order to conform with PHP's string casting operations.
See also
http://php.net/manual/en/language.oop5.magic.php#object.tostring
Returns
string
Implements StreamInterface.
close()
close ()
Closes the stream and any underlying resources.
Returns
void
Implements StreamInterface.
Referenced by BufferStream\detach().
detach()
detach ()
Separates any underlying resources from the stream.
After the stream has been detached, the stream is in an unusable state.
Returns
resource|null Underlying PHP stream, if any
Implements StreamInterface.
eof()
eof ()
Returns true if the stream is at the end of the stream.
Returns
bool
Implements StreamInterface.
getContents()
getContents ()
Returns the remaining contents in a string
Returns
string
Exceptions
RuntimeException if unable to read or an error occurs while reading.
Implements StreamInterface.
Referenced by BufferStream\__toString().
getMetadata()
getMetadata ($key = null)
{Get stream metadata as an associative array or retrieve a specific key.The keys returned are identical to the keys returned from PHP's stream_get_meta_data() function.string $key Specific metadata to retrieve. array|mixed|null Returns an associative array if no key is provided. Returns a specific key value if a key is provided and the value is found, or null if the key is not found.}
Returns
mixed
Implements StreamInterface.
getSize()
getSize ()
Get the size of the stream if known.
Returns
int|null Returns the size in bytes if known, or null if unknown.
Implements StreamInterface.
isReadable()
isReadable ()
Returns whether or not the stream is readable.
Returns
bool
Implements StreamInterface.
isSeekable()
isSeekable ()
Returns whether or not the stream is seekable.
Returns
bool
Implements StreamInterface.
isWritable()
isWritable ()
Returns whether or not the stream is writable.
Returns
bool
Implements StreamInterface.
read()
read ($length)
Reads data from the buffer.
Implements StreamInterface.
rewind()
rewind ()
Seek to the beginning of the stream.
If the stream is not seekable, this method will raise an exception; otherwise, it will perform a seek(0).
See also
seek() on failure.
Implements StreamInterface.
seek()
seek ($offset, $whence = SEEK_SET)
Seek to a position in the stream.
int $offset Stream offset int $whence Specifies how the cursor position will be calculated based on the seek offset. Valid values are identical to the built-in PHP $whence values for fseek(). SEEK_SET: Set position equal to offset bytes SEEK_CUR: Set position to current location plus offset SEEK_END: Set position to end-of-stream plus offset. on failure.
Implements StreamInterface.
Referenced by BufferStream\rewind().
tell()
tell ()
Returns the current position of the file read/write pointer
Returns
int Position of the file pointer
Exceptions
RuntimeException on error.
Implements StreamInterface.
write()
write ($string)
Writes data to the buffer.
Implements StreamInterface.
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/guzzlehttp/psr7/src/BufferStream.php