Utopszkij_db: CookieJar Class Reference
CookieJar Class Reference
Public Member Functions
__construct (bool $strictMode=false, array $cookieArray=[])
getCookieByName (string $name)
toArray ()
clear (?string $domain=null, ?string $path=null, ?string $name=null)
clearSessionCookies ()
setCookie (SetCookie $cookie)
count ()
getIterator ()
extractCookies (RequestInterface $request, ResponseInterface $response)
withCookieHeader (RequestInterface $request)
withCookieHeader (RequestInterface $request)
extractCookies (RequestInterface $request, ResponseInterface $response)
setCookie (SetCookie $cookie)
clear (?string $domain=null, ?string $path=null, ?string $name=null)
clearSessionCookies ()
toArray ()
Static Public Member Functions
static fromArray (array $cookies, string $domain)
static shouldPersist (SetCookie $cookie, bool $allowSessionCookies=false)
Detailed Description
Cookie jar that stores cookies as an array
Constructor & Destructor Documentation
__construct()
__construct (bool $strictMode = false, array $cookieArray = [])
Parameters
bool $strictMode Set to true to throw exceptions when invalid cookies are added to the cookie jar.
array $cookieArray Array of SetCookie objects or a hash of arrays that can be used with the SetCookie constructor
Member Function Documentation
clear()
clear (?string $domain = null, ?string $path = null, ?string $name = null)
@inheritDoc
Implements CookieJarInterface.
clearSessionCookies()
clearSessionCookies ()
@inheritDoc
Implements CookieJarInterface.
extractCookies()
extractCookies (RequestInterface $request, ResponseInterface $response)
Extract cookies from an HTTP response and store them in the CookieJar.
Parameters
RequestInterface $request Request that was sent
ResponseInterface $response Response that was received
Implements CookieJarInterface.
fromArray()
static fromArray (array $cookies, string $domain) static
Create a new Cookie jar from an associative array and domain.
Parameters
array $cookies Cookies to create the jar from
string $domain Domain to set the cookies to
getCookieByName()
getCookieByName (string $name)
Finds and returns the cookie based on the name
Parameters
string $name cookie name to search for
Returns
SetCookie|null cookie that was found or null if not found
getIterator()
getIterator ()
Returns
\ArrayIterator<int, SetCookie>
Referenced by CookieJar\toArray().
setCookie()
setCookie (SetCookie $cookie)
@inheritDoc
Implements CookieJarInterface.
Referenced by CookieJar\__construct(), CookieJar\extractCookies(), SessionCookieJar\load(), and FileCookieJar\load().
shouldPersist()
static shouldPersist (SetCookie $cookie, bool $allowSessionCookies = false) static
Evaluate if this cookie should be persisted to storage that survives between requests.
Parameters
SetCookie $cookie Being evaluated.
bool $allowSessionCookies If we should persist session cookies
toArray()
toArray ()
@inheritDoc
Implements CookieJarInterface.
withCookieHeader()
withCookieHeader (RequestInterface $request)
Create a request with added cookie headers.
If no matching cookies are found in the cookie jar, then no Cookie header is added to the request and the same request is returned.
Parameters
RequestInterface $request Request object to modify.
Returns
RequestInterface returns the modified request.
Implements CookieJarInterface.
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/guzzlehttp/guzzle/src/Cookie/CookieJar.php