Utopszkij_db: Utils Class Reference
Utils Class Reference
Static Public Member Functions
static toHex ($value, $isPrefix=false)
static hexToBin ($value)
static isZeroPrefixed ($value)
static stripZero ($value)
static isNegative ($value)
static isAddress ($value)
static isAddressChecksum ($value)
static toChecksumAddress ($value)
static isHex ($value)
static sha3 ($value)
static toString ($value)
static toWei ($number, $unit)
static toEther ($number, $unit)
static fromWei ($number, $unit)
static jsonMethodToString ($json)
static jsonToArray ($json)
static toBn ($number)
Public Attributes
const SHA3_NULL_HASH = 'c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'
const UNITS
Member Function Documentation
fromWei()
static fromWei ($number, $unit) static
fromWei Change number from wei to unit. For example: list($bnq, $bnr) = Utils::fromWei('1000', 'kwei'); $bnq->toString(); // 1
Parameters
BigNumber | string | int $number
string $unit
Returns
\phpseclib\Math\BigInteger
Referenced by UtilsTest\testFromWei().
hexToBin()
static hexToBin ($value) static
hexToBin
Parameters
string
Returns
string
Referenced by Str\outputFormat(), and UtilsTest\testHexToBin().
isAddress()
static isAddress ($value) static
isAddress
Parameters
string $value
Returns
bool
Referenced by AddressFormatter\format(), Address\inputFormat(), and UtilsTest\testIsAddress().
isAddressChecksum()
static isAddressChecksum ($value) static
isAddressChecksum
Parameters
string $value
Returns
bool
Referenced by UtilsTest\testIsAddressChecksum().
isHex()
static isHex ($value) static
isHex
Parameters
string $value
Returns
bool
Referenced by Bytes\inputFormat(), DynamicBytes\inputFormat(), UtilsTest\testIsHex(), and ContractTest\testIssue85().
isNegative()
static isNegative ($value) static
isNegative
Parameters
string
Returns
bool
Referenced by UtilsTest\testIsNegative().
isZeroPrefixed()
static isZeroPrefixed ($value) static
isZeroPrefixed
Parameters
string
Returns
bool
Referenced by AddressFormatter\format(), HexFormatter\format(), QuantityFormatter\format(), Address\inputFormat(), and UtilsTest\testIsZeroPrefixed().
jsonMethodToString()
static jsonMethodToString ($json) static
jsonMethodToString
Parameters
stdClass | array $json
Returns
string
Referenced by Ethabi\encodeEventSignature(), Ethabi\encodeFunctionSignature(), and UtilsTest\testJsonMethodToString().
jsonToArray()
static jsonToArray ($json) static
jsonToArray
Parameters
stdClass | array $json
Returns
array
Referenced by Ethabi\decodeParameters(), Ethabi\encodeParameters(), and UtilsTest\testJsonToArray().
sha3()
static sha3 ($value) static
sha3 keccak256
Parameters
string $value
Returns
string
Referenced by Ethabi\encodeEventSignature(), Ethabi\encodeFunctionSignature(), and UtilsTest\testSha3().
stripZero()
static stripZero ($value) static
stripZero
Parameters
string $value
Returns
string
Referenced by Ethabi\decodeParameters(), Address\inputFormat(), Bytes\inputFormat(), DynamicBytes\inputFormat(), ContractTest\testGetData(), and UtilsTest\testStripZero().
toBn()
static toBn ($number) static
toBn Change number or number string to bignumber.
Parameters
BigNumber | string | int $number
Returns
array|\phpseclib\Math\BigInteger
Referenced by SolidityType\decode(), BigNumberFormatter\format(), IntegerFormatter\format(), NumberFormatter\format(), QuantityFormatter\format(), DynamicBytes\inputFormat(), DynamicBytes\outputFormat(), ContractTest\testIssue134(), and UtilsTest\testToBn().
toChecksumAddress()
static toChecksumAddress ($value) static
toChecksumAddress
Parameters
string $value
Returns
string
Referenced by UtilsTest\testToChecksumAddress().
toEther()
static toEther ($number, $unit) static
toEther Change number from unit to ether. For example: list($bnq, $bnr) = Utils::toEther('1', 'kether'); $bnq->toString(); // 1000
Parameters
BigNumber | string | int $number
string $unit
Returns
array
Referenced by UtilsTest\testToEther().
toHex()
static toHex ($value, $isPrefix = false) static
NEGATIVE1 Cannot work, see: http://php.net/manual/en/language.constants.syntax.php
@const construct
Returns
void toHex Encoding string or integer or numeric string(is not zero prefixed) or big number to hex.
Parameters
string | int | BigNumber $value
bool $isPrefix
Returns
string
Referenced by HexFormatter\format(), Str\inputFormat(), ContractTest\testIssue134(), and UtilsTest\testToHex().
toString()
static toString ($value) static
toString
Parameters
mixed $value
Returns
string
Referenced by BigNumberFormatter\format(), HexFormatter\format(), NumberFormatter\format(), QuantityFormatter\format(), StringFormatter\format(), and TagValidator\validate().
toWei()
static toWei ($number, $unit) static
toWei Change number from unit to wei. For example: $wei = Utils::toWei('1', 'kwei'); $wei->toString(); // 1000
Parameters
BigNumber | string $number
string $unit
Returns
\phpseclib\Math\BigInteger
Referenced by UtilsTest\testToWei().
Member Data Documentation
SHA3_NULL_HASH
const SHA3_NULL_HASH = 'c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'
SHA3_NULL_HASH
@const string
UNITS
const UNITS
Initial value:
= [
        'noether' => '0',
        'wei' => '1',
        'kwei' => '1000',
        'Kwei' => '1000',
        'babbage' => '1000',
        'femtoether' => '1000',
        'mwei' => '1000000',
        'Mwei' => '1000000',
        'lovelace' => '1000000',
        'picoether' => '1000000',
        'gwei' => '1000000000',
        'Gwei' => '1000000000',
        'shannon' => '1000000000',
        'nanoether' => '1000000000',
        'nano' => '1000000000',
        'szabo' => '1000000000000',
        'microether' => '1000000000000',
        'micro' => '1000000000000',
        'finney' => '1000000000000000',
        'milliether' => '1000000000000000',
        'milli' => '1000000000000000',
        'ether' => '1000000000000000000',
        'kether' => '1000000000000000000000',
        'grand' => '1000000000000000000000',
        'mether' => '1000000000000000000000000',
        'gether' => '1000000000000000000000000000',
        'tether' => '1000000000000000000000000000000'
    ]
UNITS from ethjs-unit
@const array
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/web3p/web3.php/src/Utils.php