Utopszkij_db: SetCookie Class Reference
SetCookie Class Reference
Public Member Functions
__toString ()
toArray ()
getName ()
setName ($name)
getValue ()
setValue ($value)
getDomain ()
setDomain ($domain)
getPath ()
setPath ($path)
getMaxAge ()
setMaxAge ($maxAge)
getExpires ()
setExpires ($timestamp)
getSecure ()
setSecure ($secure)
getDiscard ()
setDiscard ($discard)
getHttpOnly ()
setHttpOnly ($httpOnly)
matchesPath (string $requestPath)
matchesDomain (string $domain)
isExpired ()
validate ()
Static Public Member Functions
static fromString (string $cookie)
Detailed Description
Set-Cookie object
Member Function Documentation
fromString()
static fromString (string $cookie) static
Create a new SetCookie object from a string.
Parameters
string $cookie Set-Cookie header string
Referenced by CookieJar\extractCookies().
getDiscard()
getDiscard ()
Get whether or not this is a session cookie.
Returns
bool|null
Referenced by CookieJar\clearSessionCookies(), CookieJar\setCookie(), and CookieJar\shouldPersist().
getDomain()
getDomain ()
Get the domain.
Returns
string|null
Referenced by SetCookie\matchesDomain(), CookieJar\setCookie(), and SetCookie\validate().
getExpires()
getExpires ()
The UNIX timestamp when the cookie Expires.
Returns
string|int|null
Referenced by CookieJar\clearSessionCookies(), SetCookie\isExpired(), CookieJar\setCookie(), and CookieJar\shouldPersist().
getHttpOnly()
getHttpOnly ()
Get whether or not this is an HTTP only cookie.
Returns
bool
getMaxAge()
getMaxAge ()
Maximum lifetime of the cookie in seconds.
Returns
int|null
getName()
getName ()
Get the cookie name.
Returns
string
Referenced by CookieJar\clear(), CookieJar\setCookie(), and SetCookie\validate().
getPath()
getPath ()
Get the path.
Returns
string
Referenced by SetCookie\matchesPath(), and CookieJar\setCookie().
getSecure()
getSecure ()
Get whether or not this is a secure cookie.
Returns
bool
getValue()
getValue ()
Get the cookie value.
Returns
string|null
Referenced by CookieJar\setCookie(), and SetCookie\validate().
isExpired()
isExpired ()
Check if the cookie is expired.
matchesDomain()
matchesDomain (string $domain)
Check if the cookie matches a domain value.
Parameters
string $domain Domain to check against
Referenced by CookieJar\clear().
matchesPath()
matchesPath (string $requestPath)
Check if the cookie matches a path value.
A request-path path-matches a given cookie-path if at least one of the following conditions holds:
The cookie-path and the request-path are identical.
The cookie-path is a prefix of the request-path, and the last character of the cookie-path is x2F ("/").
The cookie-path is a prefix of the request-path, and the first character of the request-path that is not included in the cookie- path is a x2F ("/") character.
Parameters
string $requestPath Path to check against
Referenced by CookieJar\clear().
setDiscard()
setDiscard ($discard)
Set whether or not this is a session cookie.
Parameters
bool $discard Set to true or false if this is a session cookie
setDomain()
setDomain ($domain)
Set the domain of the cookie.
Parameters
string | null $domain
setExpires()
setExpires ($timestamp)
Set the unix timestamp for which the cookie will expire.
Parameters
int | string | null $timestamp Unix timestamp or any English textual datetime description.
setHttpOnly()
setHttpOnly ($httpOnly)
Set whether or not this is an HTTP only cookie.
Parameters
bool $httpOnly Set to true or false if this is HTTP only
setMaxAge()
setMaxAge ($maxAge)
Set the max-age of the cookie.
Parameters
int | null $maxAge Max age of the cookie in seconds
setName()
setName ($name)
Set the cookie name.
Parameters
string $name Cookie name
setPath()
setPath ($path)
Set the path of the cookie.
Parameters
string $path Path of the cookie
setSecure()
setSecure ($secure)
Set whether or not the cookie is secure.
Parameters
bool $secure Set to true or false if secure
setValue()
setValue ($value)
Set the cookie value.
Parameters
string $value Cookie value
validate()
validate ()
Check if the cookie is valid according to RFC 6265.
Returns
bool|string Returns true if valid or an error message if invalid
Referenced by CookieJar\setCookie().
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/guzzlehttp/guzzle/src/Cookie/SetCookie.php