Utopszkij_db: Each Class Reference
Each Class Reference
Static Public Member Functions
static of ($iterable, callable $onFulfilled=null, callable $onRejected=null)
static ofLimit ($iterable, $concurrency, callable $onFulfilled=null, callable $onRejected=null)
static ofLimitAll ($iterable, $concurrency, callable $onFulfilled=null)
Member Function Documentation
of()
static of ($iterable, callable $onFulfilled = null, callable $onRejected = null) static
Given an iterator that yields promises or values, returns a promise that is fulfilled with a null value when the iterator has been consumed or the aggregate promise has been fulfilled or rejected.
$onFulfilled is a function that accepts the fulfilled value, iterator index, and the aggregate promise. The callback can invoke any necessary side effects and choose to resolve or reject the aggregate if needed.
$onRejected is a function that accepts the rejection reason, iterator index, and the aggregate promise. The callback can invoke any necessary side effects and choose to resolve or reject the aggregate if needed.
Parameters
mixed $iterable Iterator or array to iterate over.
callable $onFulfilled
callable $onRejected
Returns
PromiseInterface
Referenced by Utils\all(), Utils\settle(), and Utils\some().
ofLimit()
static ofLimit ($iterable, $concurrency, callable $onFulfilled = null, callable $onRejected = null) static
Like of, but only allows a certain number of outstanding promises at any given time.
$concurrency may be an integer or a function that accepts the number of pending promises and returns a numeric concurrency limit value to allow for dynamic a concurrency size.
Parameters
mixed $iterable
int | callable $concurrency
callable $onFulfilled
callable $onRejected
Returns
PromiseInterface
ofLimitAll()
static ofLimitAll ($iterable, $concurrency, callable $onFulfilled = null) static
Like limit, but ensures that no promise in the given $iterable argument is rejected. If any promise is rejected, then the aggregate promise is rejected with the encountered rejection.
Parameters
mixed $iterable
int | callable $concurrency
callable $onFulfilled
Returns
PromiseInterface
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/guzzlehttp/promises/src/Each.php