Utopszkij_db: SSH2 Class Reference
SSH2 Class Reference
Public Member Functions
__construct ($host, $port=22, $timeout=10)
setCryptoEngine ($engine)
sendIdentificationStringFirst ()
sendIdentificationStringLast ()
sendKEXINITFirst ()
sendKEXINITLast ()
_connect ()
_generate_identifier ()
_key_exchange ($kexinit_payload_server=false)
_encryption_algorithm_to_key_size ($algorithm)
_encryption_algorithm_to_crypt_instance ($algorithm)
_bad_algorithm_candidate ($algorithm)
login ($username)
_login ($username)
_login_helper ($username, $password=null)
_keyboard_interactive_login ($username, $password)
_keyboard_interactive_process ()
_ssh_agent_login ($username, $agent)
_privatekey_login ($username, $privatekey)
setTimeout ($timeout)
setKeepAlive ($interval)
getStdError ()
exec ($command, $callback=null)
_initShell ()
_get_interactive_channel ()
_get_open_channel ()
read ($expect='', $mode=self::READ_SIMPLE)
write ($cmd)
startSubsystem ($subsystem)
stopSubsystem ()
reset ()
isTimeout ()
disconnect ()
__destruct ()
isConnected ()
isAuthenticated ()
ping ()
_reconnect ()
_reset_connection ($reason)
_get_binary_packet ($skip_channel_filter=false)
_filter ($payload, $skip_channel_filter)
enableQuietMode ()
disableQuietMode ()
isQuietModeEnabled ()
enablePTY ()
disablePTY ()
isPTYEnabled ()
_get_channel_packet ($client_channel, $skip_extended=false)
_send_binary_packet ($data, $logged=null)
_append_log ($message_number, $message)
_send_channel_packet ($client_channel, $data)
_close_channel ($client_channel, $want_reply=false)
_disconnect ($reason)
_string_shift (&$string, $index=1)
_define_array ()
getLog ()
_format_log ($message_log, $message_number_log)
_format_log_helper ($matches)
_on_channel_open ()
_array_intersect_first ($array1, $array2)
getErrors ()
getLastError ()
getServerIdentification ()
getKexAlgorithms ()
getServerHostKeyAlgorithms ()
getEncryptionAlgorithmsClient2Server ()
getEncryptionAlgorithmsServer2Client ()
getMACAlgorithmsClient2Server ()
getMACAlgorithmsServer2Client ()
getCompressionAlgorithmsClient2Server ()
getCompressionAlgorithmsServer2Client ()
getLanguagesServer2Client ()
getLanguagesClient2Server ()
getServerAlgorithms ()
getSupportedKEXAlgorithms ()
getSupportedHostKeyAlgorithms ()
getSupportedEncryptionAlgorithms ()
getSupportedMACAlgorithms ()
getSupportedCompressionAlgorithms ()
getAlgorithmsNegotiated ()
setPreferredAlgorithms ($methods)
getBannerMessage ()
getServerPublicHostKey ()
getExitStatus ()
getWindowColumns ()
getWindowRows ()
setWindowColumns ($value)
setWindowRows ($value)
setWindowSize ($columns=80, $rows=24)
_updateLogHistory ($old, $new)
getAuthMethodsToContinue ()
enableSmartMFA ()
disableSmartMFA ()
Public Attributes
const NET_SSH2_COMPRESSION_NONE = 1
const NET_SSH2_COMPRESSION_ZLIB = 2
const NET_SSH2_COMPRESSION_ZLIB_AT_OPENSSH = 3
const MASK_CONSTRUCTOR = 0x00000001
const MASK_CONNECTED = 0x00000002
const MASK_LOGIN_REQ = 0x00000004
const MASK_LOGIN = 0x00000008
const MASK_SHELL = 0x00000010
const MASK_WINDOW_ADJUST = 0x00000020
const CHANNEL_EXEC = 1
const CHANNEL_SHELL = 2
const CHANNEL_SUBSYSTEM = 3
const CHANNEL_AGENT_FORWARD = 4
const CHANNEL_KEEP_ALIVE = 5
const LOG_SIMPLE = 1
const LOG_COMPLEX = 2
const LOG_REALTIME = 3
const LOG_REALTIME_FILE = 4
const LOG_MAX_SIZE = 1048576
const READ_SIMPLE = 1
const READ_REGEX = 2
const READ_NEXT = 3
$identifier
$fsock
$bitmap = 0
$errors = array()
$server_identifier = false
$kex_algorithms = false
$kex_algorithm = false
$kex_dh_group_size_min = 1536
$kex_dh_group_size_preferred = 2048
$kex_dh_group_size_max = 4096
$server_host_key_algorithms = false
$encryption_algorithms_client_to_server = false
$encryption_algorithms_server_to_client = false
$mac_algorithms_client_to_server = false
$mac_algorithms_server_to_client = false
$compression_algorithms_client_to_server = false
$compression_algorithms_server_to_client = false
$languages_server_to_client = false
$languages_client_to_server = false
$preferred = array()
$encrypt_block_size = 8
$decrypt_block_size = 8
$decrypt = false
$encrypt = false
$hmac_create = false
$hmac_check = false
$hmac_size = false
$server_public_host_key
$session_id = false
$exchange_hash = false
$message_numbers = array()
$disconnect_reasons = array()
$channel_open_failure_reasons = array()
$terminal_modes = array()
$channel_extended_data_type_codes = array()
$send_seq_no = 0
$get_seq_no = 0
$server_channels = array()
$channel_buffers = array()
$channel_status = array()
$packet_size_client_to_server = array()
$message_number_log = array()
$message_log = array()
$window_size = 0x7FFFFFFF
$window_resize = 0x40000000
$window_size_server_to_client = array()
$window_size_client_to_server = array()
$signature = ''
$signature_format = ''
$interactiveBuffer = ''
$log_size
$timeout
$curTimeout
$keepAlive
$realtime_log_file
$realtime_log_size
$signature_validated = false
$realtime_log_wrap
$quiet_mode = false
$last_packet
$exit_status
$request_pty = false
$in_request_pty_exec = false
$in_subsystem
$stdErrorLog
$last_interactive_response = ''
$keyboard_requests_responses = array()
$banner_message = ''
$is_timeout = false
$log_boundary = ':'
$log_long_width = 65
$log_short_width = 16
$host
$port
$windowColumns = 80
$windowRows = 24
$crypto_engine = false
$agent
$send_id_string_first = true
$send_kex_first = true
$bad_key_size_fix = false
$retry_connect = false
$binary_packet_buffer = false
$preferred_signature_format = false
$auth = array()
$auth_methods_to_continue = null
$compress = self::NET_SSH2_COMPRESSION_NONE
$decompress = self::NET_SSH2_COMPRESSION_NONE
$compress_context
$decompress_context
$regenerate_compression_context = false
$regenerate_decompression_context = false
$smartMFA = true
Constructor & Destructor Documentation
__construct()
__construct ($host, $port = 22, $timeout = 10)
Default Constructor.
$host can either be a string, representing the host, or a stream resource.
Parameters
mixed $host
int $port
int $timeout
See also
self::login()
Returns
\phpseclib\Net\SSH2 @access public
Reimplemented in SFTP.
__destruct()
__destruct ()
Destructor.
Will be called, automatically, if you're supporting just PHP5. If you're supporting PHP4, you'll need to call disconnect().
@access public
Member Function Documentation
_append_log()
_append_log ($message_number, $message)
Logs data packets
Makes sure that only the last 1MB worth of packets will be logged
Parameters
string $message_number
string $message @access private
Referenced by SSH2\_connect(), SSH2\_get_binary_packet(), and SSH2\_send_binary_packet().
_array_intersect_first()
_array_intersect_first ($array1, $array2)
Returns the first value of the intersection of two arrays or false if the intersection is empty. The order is defined by the first parameter.
Parameters
array $array1
array $array2
Returns
mixed False if intersection is empty, else intersected value. @access private
Referenced by SSH2\_key_exchange().
_bad_algorithm_candidate()
_bad_algorithm_candidate ($algorithm)
Tests whether or not proposed algorithm has a potential for issues
https://bugzilla.mindrot.org/show_bug.cgi?id=1291 string $algorithm Name of the encryption algorithm bool private
Referenced by SSH2\_encryption_algorithm_to_key_size(), and SSH2\_get_binary_packet().
_close_channel()
_close_channel ($client_channel, $want_reply = false)
Closes and flushes a channel
\phpseclib\Net\SSH2 doesn't properly close most channels. For exec() channels are normally closed by the server and for SFTP channels are presumably closed when the client disconnects. This functions is intended for SCP more than anything.
Parameters
int $client_channel
bool $want_reply
Returns
bool @access private
Referenced by SSH2\_get_channel_packet(), SSH2\disablePTY(), SSH2\exec(), SSH2\ping(), SSH2\reset(), and SSH2\stopSubsystem().
_connect()
_connect ()
Connect to an SSHv2 server
Returns
bool @access private
Referenced by SSH2\_login(), SSH2\_login_helper(), SSH2\_reconnect(), SSH2\getAlgorithmsNegotiated(), SSH2\getCompressionAlgorithmsClient2Server(), SSH2\getCompressionAlgorithmsServer2Client(), SSH2\getEncryptionAlgorithmsClient2Server(), SSH2\getEncryptionAlgorithmsServer2Client(), SSH2\getKexAlgorithms(), SSH2\getLanguagesClient2Server(), SSH2\getLanguagesServer2Client(), SSH2\getMACAlgorithmsClient2Server(), SSH2\getMACAlgorithmsServer2Client(), SSH2\getServerAlgorithms(), SSH2\getServerHostKeyAlgorithms(), SSH2\getServerIdentification(), and SSH2\getServerPublicHostKey().
_define_array()
_define_array ()
Define Array
Takes any number of arrays whose indices are integers and whose values are strings and defines a bunch of named constants from it, using the value as the name of the constant and the index as the value of the constant. If any of the constants that would be defined already exists, none of the constants will be defined.
@access private
Referenced by SFTP\__construct(), and SSH2\__construct().
_disconnect()
_disconnect ($reason)
Disconnect
Parameters
int $reason
Returns
bool @access private
Reimplemented in SFTP.
Referenced by SSH2\_filter(), SSH2\_get_channel_packet(), SSH2\_initShell(), SSH2\_key_exchange(), SSH2\_login_helper(), SSH2\_privatekey_login(), SSH2\_reset_connection(), SSH2\disconnect(), SSH2\exec(), and SSH2\getServerPublicHostKey().
_encryption_algorithm_to_crypt_instance()
_encryption_algorithm_to_crypt_instance ($algorithm)
Maps an encryption algorithm name to an instance of a subclass of \phpseclib\Crypt\Base.
Parameters
string $algorithm Name of the encryption algorithm
Returns
mixed Instance of \phpseclib\Crypt\Base or null for unknown @access private
Referenced by SSH2\_key_exchange(), and SSH2\getSupportedEncryptionAlgorithms().
_encryption_algorithm_to_key_size()
_encryption_algorithm_to_key_size ($algorithm)
Maps an encryption algorithm name to the number of key bytes.
Parameters
string $algorithm Name of the encryption algorithm
Returns
int|null Number of bytes as an integer or null for unknown @access private
Referenced by SSH2\_key_exchange().
_filter()
_filter ($payload, $skip_channel_filter)
Filter Binary Packets
Because some binary packets need to be ignored...
See also
self::_get_binary_packet()
Returns
string @access private
Referenced by SSH2\_get_binary_packet().
_format_log()
_format_log ($message_log, $message_number_log)
Formats a log for printing
Parameters
array $message_log
array $message_number_log @access private
Returns
string
Referenced by SSH2\_append_log(), and SSH2\getLog().
_format_log_helper()
_format_log_helper ($matches)
Helper function for _format_log
For use with preg_replace_callback()
Parameters
array $matches @access private
Returns
string
_generate_identifier()
_generate_identifier ()
Generates the SSH identifier
You should overwrite this method in your own class if you want to use another identifier
@access protected
Returns
string
Referenced by SSH2\_connect().
_get_binary_packet()
_get_binary_packet ($skip_channel_filter = false)
Gets Binary Packets
See '6. Binary Packet Protocol' of rfc4253 for more info.
See also
self::_send_binary_packet()
Returns
string @access private
Referenced by SSH2\_connect(), SSH2\_filter(), SSH2\_get_binary_packet(), SSH2\_get_channel_packet(), SSH2\_key_exchange(), SSH2\_keyboard_interactive_process(), SSH2\_login_helper(), and SSH2\_privatekey_login().
_get_channel_packet()
_get_channel_packet ($client_channel, $skip_extended = false)
Gets channel data
Returns the data as a string if it's available and false if not.
Parameters
int $client_channel
bool $skip_extended
Returns
mixed|bool @access private
Referenced by SSH2\_close_channel(), SSH2\_filter(), SSH2\_get_channel_packet(), SSH2\_initShell(), SFTP\_partial_init_sftp_connection(), SSH2\_send_channel_packet(), SSH2\exec(), SSH2\ping(), SSH2\read(), and SSH2\startSubsystem().
_get_interactive_channel()
_get_interactive_channel ()
Return the channel to be used with read() / write()
See also
self::read()
self::write()
Returns
int @access public
Referenced by SSH2\read(), SSH2\reset(), and SSH2\write().
_get_open_channel()
_get_open_channel ()
Return an available open channel
Returns
int @access public
_initShell()
_initShell ()
Creates an interactive shell
See also
self::read()
self::write()
Returns
bool @access private
Referenced by SSH2\read(), and SSH2\write().
_key_exchange()
_key_exchange ($kexinit_payload_server = false)
Key Exchange
Parameters
string $kexinit_payload_server optional @access private
Referenced by SSH2\_connect(), and SSH2\_filter().
_keyboard_interactive_login()
_keyboard_interactive_login ($username, $password)
Login via keyboard-interactive authentication
See RFC4256 for details. This is not a full-featured keyboard-interactive authenticator.
Parameters
string $username
string $password
Returns
bool @access private
Referenced by SSH2\_login_helper().
_keyboard_interactive_process()
_keyboard_interactive_process ()
Handle the keyboard-interactive requests / responses.
Returns
bool @access private
Referenced by SSH2\_keyboard_interactive_login(), SSH2\_keyboard_interactive_process(), and SSH2\_login_helper().
_login()
_login ($username)
Login Helper
Parameters
string $username
Returns
bool
See also
self::_login_helper() @access private
Referenced by SSH2\login().
_login_helper()
_login_helper ($username, $password = null)
Login Helper
Parameters
string $username
string $password
Returns
bool @access private
Referenced by SSH2\_login(), and SSH2\_login_helper().
_on_channel_open()
_on_channel_open ()
Helper function for agent->_on_channel_open()
Used when channels are created to inform agent of said channel opening. Must be called after channel open confirmation received
@access private
Referenced by SSH2\_get_channel_packet().
_privatekey_login()
_privatekey_login ($username, $privatekey)
Login with an RSA private key
Parameters
string $username
\phpseclib\Crypt\RSA $privatekey
Returns
bool @access private
Referenced by SSH2\_login_helper(), and SSH2\_ssh_agent_login().
_reconnect()
_reconnect ()
In situ reconnect method
Returns
boolean @access private
Referenced by SSH2\ping().
_reset_connection()
_reset_connection ($reason)
Resets a connection for re-use
Parameters
int $reason @access private
Reimplemented in SFTP.
Referenced by SSH2\_get_binary_packet(), and SSH2\_reconnect().
_send_binary_packet()
_send_binary_packet ($data, $logged = null)
Sends Binary Packets
See '6. Binary Packet Protocol' of rfc4253 for more info.
Parameters
string $data
string $logged
See also
self::_get_binary_packet()
Returns
bool @access private
Referenced by SSH2\_close_channel(), SSH2\_disconnect(), SSH2\_filter(), SSH2\_get_binary_packet(), SSH2\_get_channel_packet(), SSH2\_initShell(), SSH2\_key_exchange(), SSH2\_keyboard_interactive_login(), SSH2\_keyboard_interactive_process(), SSH2\_login_helper(), SFTP\_partial_init_sftp_connection(), SSH2\_privatekey_login(), SSH2\_send_channel_packet(), SSH2\exec(), SSH2\ping(), and SSH2\startSubsystem().
_send_channel_packet()
_send_channel_packet ($client_channel, $data)
Sends channel data
Spans multiple SSH_MSG_CHANNEL_DATAs if appropriate
Parameters
int $client_channel
string $data
Returns
bool @access private
Referenced by SSH2\_get_channel_packet(), and SSH2\write().
_ssh_agent_login()
_ssh_agent_login ($username, $agent)
Login with an ssh-agent provided key
Parameters
string $username
\phpseclib\System\SSH\Agent $agent
Returns
bool @access private
Referenced by SSH2\_login_helper().
_string_shift()
_string_shift (& $string, $index = 1)
String Shift
Inspired by array_shift
Parameters
string $string
int $index
Returns
string @access private
Referenced by SSH2\_append_log(), SFTP\_close_handle(), SSH2\_filter(), SSH2\_format_log(), SSH2\_get_binary_packet(), SSH2\_get_channel_packet(), SFTP\_init_sftp_connection(), SSH2\_key_exchange(), SSH2\_keyboard_interactive_process(), SFTP\_list(), SFTP\_logError(), SSH2\_login_helper(), SFTP\_mkdir_helper(), SFTP\_partial_init_sftp_connection(), SSH2\_privatekey_login(), SFTP\_read_put_responses(), SFTP\_realpath(), SSH2\_send_channel_packet(), SFTP\_setstat(), SFTP\delete(), SSH2\getServerPublicHostKey(), SSH2\read(), SFTP\readlink(), SFTP\rmdir(), and SFTP\symlink().
_updateLogHistory()
_updateLogHistory ($old, $new)
Update packet types in log history
Parameters
string $old
string $new @access private
Referenced by SSH2\_key_exchange(), SSH2\_keyboard_interactive_process(), SSH2\_login_helper(), and SSH2\_privatekey_login().
disablePTY()
disablePTY ()
Disable request-pty when using exec()
@access public
disableQuietMode()
disableQuietMode ()
Disable Quiet Mode
Show stderr in output
@access public
disableSmartMFA()
disableSmartMFA ()
Disables "smart" multi-factor authentication (MFA)
disconnect()
disconnect ()
Disconnect
@access public
Referenced by SSH2\__destruct(), and SSH2\_close_channel().
enablePTY()
enablePTY ()
Enable request-pty when using exec()
@access public
enableQuietMode()
enableQuietMode ()
Enable Quiet Mode
Suppress stderr from output
@access public
enableSmartMFA()
enableSmartMFA ()
Enables "smart" multi-factor authentication (MFA)
exec()
exec ($command, $callback = null)
Execute Command
If $callback is set to false then \phpseclib\Net\SSH2::_get_channel_packet(self::CHANNEL_EXEC) will need to be called manually. In all likelihood, this is not a feature you want to be taking advantage of.
Parameters
string $command
Callback $callback
Returns
string @access public
getAlgorithmsNegotiated()
getAlgorithmsNegotiated ()
Return list of negotiated algorithms
Uses the same format as https://www.php.net/ssh2-methods-negotiated
Returns
array @access public
getAuthMethodsToContinue()
getAuthMethodsToContinue ()
Return the list of authentication methods that may productively continue authentication.
See also
https://tools.ietf.org/html/rfc4252#section-5.1
Returns
array|null
getBannerMessage()
getBannerMessage ()
Returns the banner message.
Quoting from the RFC, "in some jurisdictions, sending a warning message before authentication may be relevant for getting legal protection."
Returns
string @access public
getCompressionAlgorithmsClient2Server()
getCompressionAlgorithmsClient2Server ()
Return a list of the compression algorithms the server supports, when receiving stuff from the client.
Returns
array @access public
getCompressionAlgorithmsServer2Client()
getCompressionAlgorithmsServer2Client ()
Return a list of the compression algorithms the server supports, when sending stuff to the client.
Returns
array @access public
getEncryptionAlgorithmsClient2Server()
getEncryptionAlgorithmsClient2Server ()
Return a list of the (symmetric key) encryption algorithms the server supports, when receiving stuff from the client.
Returns
array @access public
getEncryptionAlgorithmsServer2Client()
getEncryptionAlgorithmsServer2Client ()
Return a list of the (symmetric key) encryption algorithms the server supports, when sending stuff to the client.
Returns
array @access public
getErrors()
getErrors ()
Returns all errors
Returns
string[] @access public
getExitStatus()
getExitStatus ()
Returns the exit status of an SSH command or false.
Returns
false|int @access public
getKexAlgorithms()
getKexAlgorithms ()
Return a list of the key exchange algorithms the server supports.
Returns
array @access public
getLanguagesClient2Server()
getLanguagesClient2Server ()
Return a list of the languages the server supports, when receiving stuff from the client.
Returns
array @access public
getLanguagesServer2Client()
getLanguagesServer2Client ()
Return a list of the languages the server supports, when sending stuff to the client.
Returns
array @access public
getLastError()
getLastError ()
Returns the last error
Returns
string @access public
getLog()
getLog ()
Returns a log of the packets that have been sent and received.
Returns a string if NET_SSH2_LOGGING == self::LOG_COMPLEX, an array if NET_SSH2_LOGGING == self::LOG_SIMPLE and false if !defined('NET_SSH2_LOGGING')
@access public
Returns
array|false|string
getMACAlgorithmsClient2Server()
getMACAlgorithmsClient2Server ()
Return a list of the MAC algorithms the server supports, when receiving stuff from the client.
Returns
array @access public
getMACAlgorithmsServer2Client()
getMACAlgorithmsServer2Client ()
Return a list of the MAC algorithms the server supports, when sending stuff to the client.
Returns
array @access public
getServerAlgorithms()
getServerAlgorithms ()
Returns a list of algorithms the server supports
Returns
array @access public
getServerHostKeyAlgorithms()
getServerHostKeyAlgorithms ()
Return a list of the host key (public key) algorithms the server supports.
Returns
array @access public
getServerIdentification()
getServerIdentification ()
Return the server identification.
Returns
string @access public
getServerPublicHostKey()
getServerPublicHostKey ()
Returns the server public host key.
Caching this the first time you connect to a server and checking the result on subsequent connections is recommended. Returns false if the server signature is not signed correctly with the public host key.
Returns
mixed @access public
getStdError()
getStdError ()
Get the output from stdError
@access public
getSupportedCompressionAlgorithms()
getSupportedCompressionAlgorithms ()
Returns a list of compression algorithms that phpseclib supports
Returns
array @access public
Referenced by SSH2\_key_exchange(), and SSH2\setPreferredAlgorithms().
getSupportedEncryptionAlgorithms()
getSupportedEncryptionAlgorithms ()
Returns a list of symmetric key algorithms that phpseclib supports
Returns
array @access public
Referenced by SSH2\_key_exchange(), and SSH2\setPreferredAlgorithms().
getSupportedHostKeyAlgorithms()
getSupportedHostKeyAlgorithms ()
Returns a list of host key algorithms that phpseclib supports
Returns
array @access public
Referenced by SSH2\_key_exchange(), and SSH2\setPreferredAlgorithms().
getSupportedKEXAlgorithms()
getSupportedKEXAlgorithms ()
Returns a list of KEX algorithms that phpseclib supports
Returns
array @access public
Referenced by SSH2\_key_exchange(), and SSH2\setPreferredAlgorithms().
getSupportedMACAlgorithms()
getSupportedMACAlgorithms ()
Returns a list of MAC algorithms that phpseclib supports
Returns
array @access public
Referenced by SSH2\_key_exchange(), and SSH2\setPreferredAlgorithms().
getWindowColumns()
getWindowColumns ()
Returns the number of columns for the terminal window size.
Returns
int @access public
getWindowRows()
getWindowRows ()
Returns the number of rows for the terminal window size.
Returns
int @access public
isAuthenticated()
isAuthenticated ()
Have you successfully been logged in?
Returns
bool @access public
Referenced by SSH2\_filter(), SSH2\_get_binary_packet(), SSH2\_send_binary_packet(), SSH2\exec(), SSH2\ping(), SSH2\read(), and SSH2\write().
isConnected()
isConnected ()
Is the connection still active?
Returns
bool @access public
isPTYEnabled()
isPTYEnabled ()
Returns whether request-pty is enabled or not
See also
self::enablePTY()
self::disablePTY() @access public
Returns
bool
isQuietModeEnabled()
isQuietModeEnabled ()
Returns whether Quiet Mode is enabled or not
See also
self::enableQuietMode()
self::disableQuietMode() @access public
Returns
bool
isTimeout()
isTimeout ()
Is timeout?
Did exec() or read() return because they timed out or because they encountered the end?
@access public
Referenced by SFTP\_partial_init_sftp_connection().
login()
login ($username)
Login
The $password parameter can be a plaintext password, a \phpseclib\Crypt\RSA object or an array
Parameters
string $username
Returns
bool
See also
self::_login() @access public
ping()
ping ()
Pings a server connection, or tries to reconnect if the connection has gone down
Inspired by http://php.net/manual/en/mysqli.ping.php
Returns
bool @access public
read()
read ($expect = '', $mode = self::READ_SIMPLE)
Returns the output of an interactive shell
Returns when there's a match for $expect, which can take the form of a string literal or, if $mode == self::READ_REGEX, a regular expression.
See also
self::write()
Parameters
string $expect
int $mode
Returns
string|bool @access public
reset()
reset ()
Closes a channel
If read() timed out you might want to just close the channel and have it auto-restart on the next read() call
@access public
sendIdentificationStringFirst()
sendIdentificationStringFirst ()
Send Identification String First
https://tools.ietf.org/html/rfc4253#section-4.2 says "when the connection has been established, both sides MUST send an identification string". It does not say which side sends it first. In theory it shouldn't matter but it is a fact of life that some SSH servers are simply buggy
@access public
sendIdentificationStringLast()
sendIdentificationStringLast ()
Send Identification String Last
https://tools.ietf.org/html/rfc4253#section-4.2 says "when the connection has been established, both sides MUST send an identification string". It does not say which side sends it first. In theory it shouldn't matter but it is a fact of life that some SSH servers are simply buggy
@access public
sendKEXINITFirst()
sendKEXINITFirst ()
Send SSH_MSG_KEXINIT First
https://tools.ietf.org/html/rfc4253#section-7.1 says "key exchange begins by each sending sending the [SSH_MSG_KEXINIT] packet". It does not say which side sends it first. In theory it shouldn't matter but it is a fact of life that some SSH servers are simply buggy
@access public
sendKEXINITLast()
sendKEXINITLast ()
Send SSH_MSG_KEXINIT Last
https://tools.ietf.org/html/rfc4253#section-7.1 says "key exchange begins by each sending sending the [SSH_MSG_KEXINIT] packet". It does not say which side sends it first. In theory it shouldn't matter but it is a fact of life that some SSH servers are simply buggy
@access public
setCryptoEngine()
setCryptoEngine ($engine)
Set Crypto Engine Mode
Possible $engine values: CRYPT_MODE_INTERNAL, CRYPT_MODE_MCRYPT
Parameters
int $engine @access public
setKeepAlive()
setKeepAlive ($interval)
Set Keep Alive
Sends an SSH2_MSG_IGNORE message every x seconds, if x is a positive non-zero number.
Parameters
int $interval @access public
setPreferredAlgorithms()
setPreferredAlgorithms ($methods)
Accepts an associative array with up to four parameters as described at https://www.php.net/manual/en/function.ssh2-connect.php
Parameters
array $methods @access public
setTimeout()
setTimeout ($timeout)
Set Timeout
$ssh->exec('ping 127.0.0.1'); on a Linux host will never return and will run indefinitely. setTimeout() makes it so it'll timeout. Setting $timeout to false or 0 will mean there is no timeout.
Parameters
mixed $timeout @access public
setWindowColumns()
setWindowColumns ($value)
Sets the number of columns for the terminal window size.
Parameters
int $value @access public
setWindowRows()
setWindowRows ($value)
Sets the number of rows for the terminal window size.
Parameters
int $value @access public
setWindowSize()
setWindowSize ($columns = 80, $rows = 24)
Sets the number of columns and rows for the terminal window size.
Parameters
int $columns
int $rows @access public
startSubsystem()
startSubsystem ($subsystem)
Start a subsystem.
Right now only one subsystem at a time is supported. To support multiple subsystem's stopSubsystem() could accept a string that contained the name of the subsystem, but at that point, only one subsystem of each type could be opened. To support multiple subsystem's of the same name maybe it'd be best if startSubsystem() generated a new channel id and returns that and then that that was passed into stopSubsystem() but that'll be saved for a future date and implemented if there's sufficient demand for such a feature.
See also
self::stopSubsystem()
Parameters
string $subsystem
Returns
bool @access public
stopSubsystem()
stopSubsystem ()
Stops a subsystem.
See also
self::startSubsystem()
Returns
bool @access public
write()
write ($cmd)
Inputs a command into an interactive shell.
See also
self::read()
Parameters
string $cmd
Returns
bool @access public
Member Data Documentation
$curTimeout
$curTimeout
Current Timeout
See also
self::_get_channel_packet() @access private
$keepAlive
$keepAlive
Keep Alive Interval
See also
self::setKeepAlive() @access private
$quiet_mode
$quiet_mode = false
Flag to suppress stderr from output
See also
self::enableQuietMode() @access private
Referenced by SSH2\isQuietModeEnabled().
$realtime_log_wrap
$realtime_log_wrap
Real-time log file wrap boolean
See also
self::_append_log() @access private
$timeout
$timeout
Timeout
See also
self::setTimeout() @access private
Referenced by SFTP\__construct(), SSH2\__construct(), SSH2\_connect(), SSH2\exec(), SSH2\read(), and SSH2\setTimeout().
CHANNEL_EXEC
const CHANNEL_EXEC = 1
#- #+ Channel constants
RFC4254 refers not to client and server channels but rather to sender and recipient channels. we don't refer to them in that way because RFC4254 toggles the meaning. the client sends a SSH_MSG_CHANNEL_OPEN message with a sender channel and the server sends a SSH_MSG_CHANNEL_OPEN_CONFIRMATION in response, with a sender and a recepient channel. at first glance, you might conclude that SSH_MSG_CHANNEL_OPEN_CONFIRMATION's sender channel would be the same thing as SSH_MSG_CHANNEL_OPEN's sender channel, but it's not, per this snipet: The 'recipient channel' is the channel number given in the original open request, and 'sender channel' is the channel number allocated by the other side.
See also
\phpseclib\Net\SSH2::_send_channel_packet()
\phpseclib\Net\SSH2::_get_channel_packet() @access private
Referenced by SCP\_close(), SSH2\_get_interactive_channel(), SSH2\_get_open_channel(), SCP\_receive(), SCP\_send(), SSH2\exec(), and SCP\put().
LOG_COMPLEX
const LOG_COMPLEX = 2
Returns the message content
Referenced by SSH2\_append_log(), and SSH2\getLog().
LOG_MAX_SIZE
const LOG_MAX_SIZE = 1048576
Make sure that the log never gets larger than this
LOG_REALTIME
const LOG_REALTIME = 3
Outputs the content real-time
Referenced by SSH2\_append_log().
LOG_REALTIME_FILE
const LOG_REALTIME_FILE = 4
Dumps the content real-time to a file
Referenced by SSH2\_append_log().
LOG_SIMPLE
const LOG_SIMPLE = 1
#- #+ @access public
See also
\phpseclib\Net\SSH2::getLog() Returns the message numbers
Referenced by SSH2\_append_log(), and SSH2\getLog().
MASK_CONSTRUCTOR
const MASK_CONSTRUCTOR = 0x00000001
#- #+ Execution Bitmap Masks
See also
\phpseclib\Net\SSH2::bitmap @access private
Referenced by SSH2\_connect().
NET_SSH2_COMPRESSION_NONE
const NET_SSH2_COMPRESSION_NONE = 1
#+ Compression Types
@access private No compression
NET_SSH2_COMPRESSION_ZLIB
const NET_SSH2_COMPRESSION_ZLIB = 2
zlib compression
Referenced by SSH2\_get_binary_packet(), and SSH2\_send_binary_packet().
NET_SSH2_COMPRESSION_ZLIB_AT_OPENSSH
const NET_SSH2_COMPRESSION_ZLIB_AT_OPENSSH = 3
zlib@.nosp@m.open.nosp@m.ssh.c.nosp@m.om
Referenced by SSH2\_get_binary_packet(), and SSH2\_send_binary_packet().
READ_NEXT
const READ_NEXT = 3
Returns whenever a data packet is received.
Some data packets may only contain a single character so it may be necessary to call read() multiple times when using this option
READ_REGEX
const READ_REGEX = 2
Returns when a string matching the regular expression $expect is found
READ_SIMPLE
const READ_SIMPLE = 1
#- #+ @access public
See also
\phpseclib\Net\SSH2::read() Returns when a string matching $expect exactly is found
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php