Utopszkij_db: Utils Class Reference
Utils Class Reference
Static Public Member Functions
static headersFromLines (iterable $lines)
static debugResource ($value=null)
static chooseHandler ()
static defaultUserAgent ()
static defaultCaBundle ()
static normalizeHeaderKeys (array $headers)
static isHostInNoProxy (string $host, array $noProxyArray)
static jsonDecode (string $json, bool $assoc=false, int $depth=512, int $options=0)
static currentTime ()
static idnUriConvert (UriInterface $uri, int $options=0)
static getenv (string $name)
Member Function Documentation
chooseHandler()
static chooseHandler () static
Chooses and creates a default handler to use based on the environment.
The returned handler is not wrapped by any default middlewares.
Exceptions
RuntimeException if no viable Handler is available.
Returns
callable(\Psr\Http\Message\RequestInterface, array): \GuzzleHttp\Promise\PromiseInterface Returns the best handler for the given system.
currentTime()
static currentTime () static
Wrapper for the hrtime() or microtime() functions (depending on the PHP version, one of the two is used)
Returns
float UNIX timestamp
Referenced by StreamHandler\__invoke(), and CurlMultiHandler\tick().
debugResource()
static debugResource ($value = null) static
Returns a debug stream based on the provided variable.
Parameters
mixed $value Optional value
Returns
resource
defaultCaBundle()
static defaultCaBundle () static
Returns the default cacert bundle for the current system.
First, the openssl.cafile and curl.cainfo php.ini settings are checked. If those settings are not configured, then the common locations for bundles found on Red Hat, CentOS, Fedora, Ubuntu, Debian, FreeBSD, OS X and Windows are checked. If any of these file locations are found on disk, they will be utilized.
Note: the result of this function is cached for subsequent calls.
Exceptions
RuntimeException if no bundle can be found.
Deprecated:
Utils::defaultCaBundle will be removed in guzzlehttp/guzzle:8.0. This method is not needed in PHP 5.6+.
defaultUserAgent()
static defaultUserAgent () static
Get the default User-Agent string to use with Guzzle.
headersFromLines()
static headersFromLines (iterable $lines) static
Parses an array of header lines into an associative array of headers.
Parameters
iterable $lines Header lines array of strings in the following format: "Name: Value"
Referenced by HeaderProcessor\parseHeaders().
idnUriConvert()
static idnUriConvert (UriInterface $uri, int $options = 0) static
Exceptions
InvalidArgumentException
isHostInNoProxy()
static isHostInNoProxy (string $host, array $noProxyArray) static
Returns true if the provided host matches any of the no proxy areas.
This method will strip a port from the host if it is present. Each pattern can be matched with an exact match (e.g., "foo.com" == "foo.com") or a partial match: (e.g., "foo.com" == "baz.foo.com" and ".foo.com" == "baz.foo.com", but ".foo.com" != "foo.com").
Areas are matched in the following cases:
"*" (without quotes) always matches any hosts.
An exact match.
The area starts with "." and the area is the last part of the host. e.g. '.mit.edu' will match any host that ends with '.mit.edu'.
Parameters
string $host Host to check against the patterns.
string[] $noProxyArray An array of host patterns.
Exceptions
InvalidArgumentException
jsonDecode()
static jsonDecode (string $json, bool $assoc = false, int $depth = 512, int $options = 0) static
Wrapper for json_decode that throws when an error occurs.
Parameters
string $json JSON data to parse
bool $assoc When true, returned objects will be converted into associative arrays.
int $depth User specified recursion depth.
int $options Bitmask of JSON decode options.
Returns
object|array|string|int|float|bool|null
Exceptions
InvalidArgumentException if the JSON cannot be decoded.
https://www.php.net/manual/en/function.json-decode.php
Referenced by FileCookieJar\load().
normalizeHeaderKeys()
static normalizeHeaderKeys (array $headers) static
Creates an associative array of lowercase header names to the actual header casing.
Referenced by EasyHandle\createResponse().
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/guzzlehttp/guzzle/src/Utils.php