Utopszkij_db: Random Class Reference
Random Class Reference
Static Public Member Functions
static string ($length)
Member Function Documentation
string()
static string ($length) static
Generate a random string.
Although microoptimizations are generally discouraged as they impair readability this function is ripe with microoptimizations because this function has the potential of being called a huge number of times. eg. for RSA key generation.
Parameters
int $length
Returns
string
Referenced by SSH1\_connect(), RSA\_convertPrivateKey(), RSA\_emsa_pss_encode(), SSH2\_key_exchange(), BigInteger\_random_number_helper(), SSH1\_rsa_crypt(), RSA\_rsaes_oaep_encrypt(), RSA\_rsaes_pkcs1_v1_5_encrypt(), SSH1\_send_binary_packet(), SSH2\_send_binary_packet(), and X509\sign().
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/Crypt/Random.php