Utopszkij_db: RSA Class Reference
RSA Class Reference
Public Member Functions
__construct ()
createKey ($bits=1024, $timeout=false, $partial=array())
_convertPrivateKey ($n, $e, $d, $primes, $exponents, $coefficients)
_convertPublicKey ($n, $e)
_parseKey ($key, $type)
getSize ()
_start_element_handler ($parser, $name, $attribs)
_stop_element_handler ($parser, $name)
_data_handler ($parser, $data)
loadKey ($key, $type=false)
setPassword ($password=false)
setPublicKey ($key=false, $type=false)
setPrivateKey ($key=false, $type=false)
getPublicKey ($type=self::PUBLIC_FORMAT_PKCS8)
getPublicKeyFingerprint ($algorithm='md5')
getPrivateKey ($type=self::PUBLIC_FORMAT_PKCS1)
_getPrivatePublicKey ($mode=self::PUBLIC_FORMAT_PKCS8)
__toString ()
__clone ()
_generateMinMax ($bits)
_decodeLength (&$string)
_encodeLength ($length)
_string_shift (&$string, $index=1)
setPrivateKeyFormat ($format)
setPublicKeyFormat ($format)
setHash ($hash)
setMGFHash ($hash)
setSaltLength ($sLen)
_i2osp ($x, $xLen)
_os2ip ($x)
_exponentiate ($x)
_blind ($x, $r, $i)
_equals ($x, $y)
_rsaep ($m)
_rsadp ($c)
_rsasp1 ($m)
_rsavp1 ($s)
_mgf1 ($mgfSeed, $maskLen)
_rsaes_oaep_encrypt ($m, $l='')
_rsaes_oaep_decrypt ($c, $l='')
_raw_encrypt ($m)
_rsaes_pkcs1_v1_5_encrypt ($m)
_rsaes_pkcs1_v1_5_decrypt ($c)
_emsa_pss_encode ($m, $emBits)
_emsa_pss_verify ($m, $em, $emBits)
_rsassa_pss_sign ($m)
_rsassa_pss_verify ($m, $s)
_emsa_pkcs1_v1_5_encode ($m, $emLen)
_emsa_pkcs1_v1_5_encode_without_null ($m, $emLen)
_rsassa_pkcs1_v1_5_sign ($m)
_rsassa_pkcs1_v1_5_verify ($m, $s)
setEncryptionMode ($mode)
setSignatureMode ($mode)
setComment ($comment)
getComment ()
encrypt ($plaintext)
decrypt ($ciphertext)
sign ($message)
verify ($message, $signature)
_extractBER ($str)
Public Attributes
const ENCRYPTION_OAEP = 1
const ENCRYPTION_PKCS1 = 2
const ENCRYPTION_NONE = 3
const SIGNATURE_PSS = 1
const SIGNATURE_PKCS1 = 2
const ASN1_INTEGER = 2
const ASN1_BITSTRING = 3
const ASN1_OCTETSTRING = 4
const ASN1_OBJECT = 6
const ASN1_SEQUENCE = 48
const MODE_INTERNAL = 1
const MODE_OPENSSL = 2
const PRIVATE_FORMAT_PKCS1 = 0
const PRIVATE_FORMAT_PUTTY = 1
const PRIVATE_FORMAT_XML = 2
const PRIVATE_FORMAT_PKCS8 = 8
const PRIVATE_FORMAT_OPENSSH = 9
const PUBLIC_FORMAT_RAW = 3
const PUBLIC_FORMAT_PKCS1 = 4
const PUBLIC_FORMAT_PKCS1_RAW = 4
const PUBLIC_FORMAT_XML = 5
const PUBLIC_FORMAT_OPENSSH = 6
const PUBLIC_FORMAT_PKCS8 = 7
$zero
$one
$privateKeyFormat = self::PRIVATE_FORMAT_PKCS1
$publicKeyFormat = self::PUBLIC_FORMAT_PKCS8
$modulus
$k
$exponent
$primes
$exponents
$coefficients
$hashName
$hash
$hLen
$sLen
$mgfHash
$mgfHLen
$encryptionMode = self::ENCRYPTION_OAEP
$signatureMode = self::SIGNATURE_PSS
$publicExponent = false
$password = false
$components = array()
$current
$configFile
$comment = 'phpseclib-generated-key'
Constructor & Destructor Documentation
__construct()
__construct ()
The constructor
If you want to make use of the openssl extension, you'll need to set the mode manually, yourself. The reason \phpseclib\Crypt\RSA doesn't do it is because OpenSSL doesn't fail gracefully. openssl_pkey_new(), in particular, requires openssl.cnf be present somewhere and, unfortunately, the only real way to find out is too late.
Returns
\phpseclib\Crypt\RSA @access public
Member Function Documentation
__clone()
__clone ()
__clone() magic method
@access public
Returns
Crypt_RSA
__toString()
__toString ()
__toString() magic method
@access public
Returns
string
_blind()
_blind ($x, $r, $i)
Performs RSA Blinding
Protects against timing attacks by employing RSA Blinding. Returns $x->modPow($this->exponents[$i], $this->primes[$i])
@access private
Parameters
\phpseclib\Math\BigInteger $x
\phpseclib\Math\BigInteger $r
int $i
Returns
\phpseclib\Math\BigInteger
Referenced by RSA\_exponentiate().
_convertPrivateKey()
_convertPrivateKey ($n, $e, $d, $primes, $exponents, $coefficients)
Convert a private key to the appropriate format.
@access private
See also
self::setPrivateKeyFormat()
Parameters
Math_BigInteger $n
Math_BigInteger $e
Math_BigInteger $d
array<int,Math_BigInteger> $primes
array<int,Math_BigInteger> $exponents
array<int,Math_BigInteger> $coefficients
Returns
string
Referenced by RSA\createKey(), and RSA\getPrivateKey().
_convertPublicKey()
_convertPublicKey ($n, $e)
Convert a public key to the appropriate format
@access private
See also
self::setPublicKeyFormat()
Parameters
Math_BigInteger $n
Math_BigInteger $e
Returns
string|array<string,Math_BigInteger>
Referenced by RSA\_getPrivatePublicKey(), RSA\createKey(), and RSA\getPublicKey().
_data_handler()
_data_handler ($parser, $data)
Data Handler
Called by xml_set_character_data_handler()
@access private
Parameters
resource $parser
string $data
_decodeLength()
_decodeLength (& $string)
DER-decode the length
DER supports lengths up to (2**8)**127, however, we'll only support lengths up to (2**8)**4. See X.690 paragraph 8.1.3 for more information.
@access private
Parameters
string $string
Returns
int
Referenced by RSA\_parseKey().
_emsa_pkcs1_v1_5_encode()
_emsa_pkcs1_v1_5_encode ($m, $emLen)
EMSA-PKCS1-V1_5-ENCODE
See RFC3447#section-9.2.
@access private
Parameters
string $m
int $emLen
Returns
string
Referenced by RSA\_rsassa_pkcs1_v1_5_sign(), and RSA\_rsassa_pkcs1_v1_5_verify().
_emsa_pkcs1_v1_5_encode_without_null()
_emsa_pkcs1_v1_5_encode_without_null ($m, $emLen)
EMSA-PKCS1-V1_5-ENCODE (without NULL)
Quoting https://tools.ietf.org/html/rfc8017#page-65,
"The parameters field associated with id-sha1, id-sha224, id-sha256, id-sha384, id-sha512, id-sha512/224, and id-sha512/256 should generally be omitted, but if present, it shall have a value of type NULL"
@access private
Parameters
string $m
int $emLen
Returns
string
Referenced by RSA\_rsassa_pkcs1_v1_5_verify().
_emsa_pss_encode()
_emsa_pss_encode ($m, $emBits)
EMSA-PSS-ENCODE
See RFC3447#section-9.1.1.
@access private
Parameters
string $m
int $emBits
Referenced by RSA\_rsassa_pss_sign().
_emsa_pss_verify()
_emsa_pss_verify ($m, $em, $emBits)
EMSA-PSS-VERIFY
See RFC3447#section-9.1.2.
@access private
Parameters
string $m
string $em
int $emBits
Returns
string
Referenced by RSA\_rsassa_pss_verify().
_encodeLength()
_encodeLength ($length)
DER-encode the length
DER supports lengths up to (2**8)**127, however, we'll only support lengths up to (2**8)**4. See X.690 paragraph 8.1.3 for more information.
@access private
Parameters
int $length
Returns
string
Referenced by RSA\_convertPrivateKey(), and RSA\_convertPublicKey().
_equals()
_equals ($x, $y)
Performs blinded RSA equality testing
Protects against a particular type of timing attack described.
See A Lesson In Timing Attacks (or, Don't use MessageDigest.isEquals)
Thanks for the heads up singpolyma!
@access private
Parameters
string $x
string $y
Returns
bool
Referenced by RSA\_emsa_pss_verify(), RSA\_rsaes_oaep_decrypt(), and RSA\_rsassa_pkcs1_v1_5_verify().
_exponentiate()
_exponentiate ($x)
Exponentiate with or without Chinese Remainder Theorem
See RFC3447#section-5.1.2.
@access private
Parameters
\phpseclib\Math\BigInteger $x
Returns
\phpseclib\Math\BigInteger
Referenced by RSA\_rsadp(), RSA\_rsaep(), RSA\_rsasp1(), and RSA\_rsavp1().
_extractBER()
_extractBER ($str)
Extract raw BER from Base64 encoding
@access private
Parameters
string $str
Returns
string
Referenced by RSA\_parseKey().
_generateMinMax()
_generateMinMax ($bits)
Generates the smallest and largest numbers requiring $bits bits
@access private
Parameters
int $bits
Returns
array
Referenced by RSA\createKey().
_getPrivatePublicKey()
_getPrivatePublicKey ($mode = self::PUBLIC_FORMAT_PKCS8)
Returns a minimalistic private key
Returns the private key without the prime number constituants. Structurally identical to a public key that hasn't been set as the public key
See also
self::getPrivateKey() @access private
Parameters
int $mode optional
Referenced by RSA\__toString().
_i2osp()
_i2osp ($x, $xLen)
Integer-to-Octet-String primitive
See RFC3447#section-4.1.
@access private
Parameters
\phpseclib\Math\BigInteger $x
int $xLen
Returns
string
Referenced by RSA\_raw_encrypt(), RSA\_rsaes_oaep_decrypt(), RSA\_rsaes_oaep_encrypt(), RSA\_rsaes_pkcs1_v1_5_decrypt(), RSA\_rsaes_pkcs1_v1_5_encrypt(), RSA\_rsassa_pkcs1_v1_5_sign(), RSA\_rsassa_pkcs1_v1_5_verify(), RSA\_rsassa_pss_sign(), and RSA\_rsassa_pss_verify().
_mgf1()
_mgf1 ($mgfSeed, $maskLen)
MGF1
See RFC3447#appendix-B.2.1.
@access private
Parameters
string $mgfSeed
int $maskLen
Returns
string
Referenced by RSA\_emsa_pss_encode(), RSA\_emsa_pss_verify(), RSA\_rsaes_oaep_decrypt(), and RSA\_rsaes_oaep_encrypt().
_os2ip()
_os2ip ($x)
Octet-String-to-Integer primitive
See RFC3447#section-4.2.
@access private
Parameters
int | string | resource $x
Returns
\phpseclib\Math\BigInteger
Referenced by RSA\_raw_encrypt(), RSA\_rsaes_oaep_decrypt(), RSA\_rsaes_oaep_encrypt(), RSA\_rsaes_pkcs1_v1_5_decrypt(), RSA\_rsaes_pkcs1_v1_5_encrypt(), RSA\_rsassa_pkcs1_v1_5_sign(), RSA\_rsassa_pkcs1_v1_5_verify(), RSA\_rsassa_pss_sign(), and RSA\_rsassa_pss_verify().
_parseKey()
_parseKey ($key, $type)
Break a public or private key down into its constituant components
@access private
See also
self::_convertPublicKey()
self::_convertPrivateKey()
Parameters
string | array $key
int $type
Returns
array|bool
Referenced by RSA\_parseKey(), RSA\createKey(), RSA\loadKey(), and RSA\setPublicKey().
_raw_encrypt()
_raw_encrypt ($m)
Raw Encryption / Decryption
Doesn't use padding and is not recommended.
@access private
Parameters
string $m
Returns
string
Referenced by RSA\encrypt().
_rsadp()
_rsadp ($c)
RSADP
See RFC3447#section-5.1.2.
@access private
Parameters
\phpseclib\Math\BigInteger $c
Returns
\phpseclib\Math\BigInteger
Referenced by RSA\_rsaes_oaep_decrypt(), and RSA\_rsaes_pkcs1_v1_5_decrypt().
_rsaep()
_rsaep ($m)
RSAEP
See RFC3447#section-5.1.1.
@access private
Parameters
\phpseclib\Math\BigInteger $m
Returns
\phpseclib\Math\BigInteger
Referenced by RSA\_raw_encrypt(), RSA\_rsaes_oaep_encrypt(), and RSA\_rsaes_pkcs1_v1_5_encrypt().
_rsaes_oaep_decrypt()
_rsaes_oaep_decrypt ($c, $l = '')
RSAES-OAEP-DECRYPT
See RFC3447#section-7.1.2. The fact that the error messages aren't distinguishable from one another hinders debugging, but, to quote from RFC3447::section-7.1.2:
Note. Care must be taken to ensure that an opponent cannot distinguish the different error conditions in Step 3.g, whether by error message or timing, or, more generally, learn partial information about the encoded message EM. Otherwise an opponent may be able to obtain useful information about the decryption of the ciphertext C, leading to a chosen-ciphertext attack such as the one observed by Manger [36].
As for $l... to quote from RFC3447#page-17:
Both the encryption and the decryption operations of RSAES-OAEP take the value of a label L as input. In this version of PKCS #1, L is the empty string; other uses of the label are outside the scope of this document.
@access private
Parameters
string $c
string $l
Returns
string
_rsaes_oaep_encrypt()
_rsaes_oaep_encrypt ($m, $l = '')
RSAES-OAEP-ENCRYPT
See RFC3447#section-7.1.1 and {http://en.wikipedia.org/wiki/Optimal_Asymmetric_Encryption_Padding OAES}.
@access private
Parameters
string $m
string $l
Returns
string
Referenced by RSA\encrypt().
_rsaes_pkcs1_v1_5_decrypt()
_rsaes_pkcs1_v1_5_decrypt ($c)
RSAES-PKCS1-V1_5-DECRYPT
See RFC3447#section-7.2.2.
For compatibility purposes, this function departs slightly from the description given in RFC3447. The reason being that RFC2313::section-8.1 (PKCS#1 v1.5) states that ciphertext's encrypted by the private key should have the second byte set to either 0 or 1 and that ciphertext's encrypted by the public key should have the second byte set to 2. In RFC3447 (PKCS#1 v2.1), the second byte is supposed to be 2 regardless of which key is used. For compatibility purposes, we'll just check to make sure the second byte is 2 or less. If it is, we'll accept the decrypted string as valid.
As a consequence of this, a private key encrypted ciphertext produced with \phpseclib\Crypt\RSA may not decrypt with a strictly PKCS#1 v1.5 compliant RSA implementation. Public key encrypted ciphertext's should but not private key encrypted ciphertext's.
@access private
Parameters
string $c
Returns
string
_rsaes_pkcs1_v1_5_encrypt()
_rsaes_pkcs1_v1_5_encrypt ($m)
RSAES-PKCS1-V1_5-ENCRYPT
See RFC3447#section-7.2.1.
@access private
Parameters
string $m
Returns
string
Referenced by RSA\encrypt().
_rsasp1()
_rsasp1 ($m)
RSASP1
See RFC3447#section-5.2.1.
@access private
Parameters
\phpseclib\Math\BigInteger $m
Returns
\phpseclib\Math\BigInteger
Referenced by RSA\_rsassa_pkcs1_v1_5_sign(), and RSA\_rsassa_pss_sign().
_rsassa_pkcs1_v1_5_sign()
_rsassa_pkcs1_v1_5_sign ($m)
RSASSA-PKCS1-V1_5-SIGN
See RFC3447#section-8.2.1.
@access private
Parameters
string $m
Returns
string
Referenced by RSA\sign().
_rsassa_pkcs1_v1_5_verify()
_rsassa_pkcs1_v1_5_verify ($m, $s)
RSASSA-PKCS1-V1_5-VERIFY
See RFC3447#section-8.2.2.
@access private
Parameters
string $m
string $s
Returns
string
Referenced by RSA\verify().
_rsassa_pss_sign()
_rsassa_pss_sign ($m)
RSASSA-PSS-SIGN
See RFC3447#section-8.1.1.
@access private
Parameters
string $m
Returns
string
Referenced by RSA\sign().
_rsassa_pss_verify()
_rsassa_pss_verify ($m, $s)
RSASSA-PSS-VERIFY
See RFC3447#section-8.1.2.
@access private
Parameters
string $m
string $s
Returns
string
Referenced by RSA\verify().
_rsavp1()
_rsavp1 ($s)
RSAVP1
See RFC3447#section-5.2.2.
@access private
Parameters
\phpseclib\Math\BigInteger $s
Returns
\phpseclib\Math\BigInteger
Referenced by RSA\_rsassa_pkcs1_v1_5_verify(), and RSA\_rsassa_pss_verify().
_start_element_handler()
_start_element_handler ($parser, $name, $attribs)
Start Element Handler
Called by xml_set_element_handler()
@access private
Parameters
resource $parser
string $name
array $attribs
_stop_element_handler()
_stop_element_handler ($parser, $name)
Stop Element Handler
Called by xml_set_element_handler()
@access private
Parameters
resource $parser
string $name
_string_shift()
_string_shift (& $string, $index = 1)
String Shift
Inspired by array_shift
Parameters
string $string
int $index
Returns
string @access private
Referenced by RSA\_decodeLength(), and RSA\_parseKey().
createKey()
createKey ($bits = 1024, $timeout = false, $partial = array())
Create public / private key pair
Returns an array with the following three elements:
'privatekey': The private key.
'publickey': The public key.
'partialkey': A partially computed key (if the execution time exceeded $timeout). Will need to be passed back to \phpseclib\Crypt\RSA::createKey() as the third parameter for further processing.
@access public
Parameters
int $bits
int $timeout
array $partial
decrypt()
decrypt ($ciphertext)
Decryption
See also
self::encrypt() @access public
Parameters
string $ciphertext
Returns
string
encrypt()
encrypt ($plaintext)
Encryption
Both self::ENCRYPTION_OAEP and self::ENCRYPTION_PKCS1 both place limits on how long $plaintext can be. If $plaintext exceeds those limits it will be broken up so that it does and the resultant ciphertext's will be concatenated together.
See also
self::decrypt() @access public
Parameters
string $plaintext
Returns
string
getComment()
getComment ()
Get public key comment.
@access public
Returns
string
getPrivateKey()
getPrivateKey ($type = self::PUBLIC_FORMAT_PKCS1)
Returns the private key
The private key is only returned if the currently loaded key contains the constituent prime numbers.
See also
self::getPublicKey() @access public
Parameters
int $type optional
Returns
mixed
Referenced by RSA\__toString().
getPublicKey()
getPublicKey ($type = self::PUBLIC_FORMAT_PKCS8)
Returns the public key
The public key is only returned under two circumstances - if the private key had the public key embedded within it or if the public key was set via setPublicKey(). If the currently loaded key is supposed to be the public key this function won't return it since this library, for the most part, doesn't distinguish between public and private keys.
See also
self::getPublicKey() @access public
Parameters
int $type optional
getPublicKeyFingerprint()
getPublicKeyFingerprint ($algorithm = 'md5')
Returns the public key's fingerprint
The public key's fingerprint is returned, which is equivalent to running ssh-keygen -lf rsa.pub. If there is no public key currently loaded, false is returned. Example output (md5): "c1:b1:30:29:d7:b8:de:6c:97:77:10:d7:46:41:63:87" (as specified by RFC 4716)
@access public
Parameters
string $algorithm The hashing algorithm to be used. Valid options are 'md5' and 'sha256'. False is returned for invalid values.
Returns
mixed
getSize()
getSize ()
Returns the key size
More specifically, this returns the size of the modulo in bits.
@access public
Returns
int
loadKey()
loadKey ($key, $type = false)
Loads a public or private key
Returns true on success and false on failure (ie. an incorrect password was provided or the key was malformed)
@access public
Parameters
string | RSA | array $key
bool | int $type optional
Returns
bool
Referenced by RSA\setPrivateKey().
setComment()
setComment ($comment)
Set public key comment.
@access public
Parameters
string $comment
setEncryptionMode()
setEncryptionMode ($mode)
Set Encryption Mode
Valid values include self::ENCRYPTION_OAEP and self::ENCRYPTION_PKCS1.
@access public
Parameters
int $mode
setHash()
setHash ($hash)
Determines which hashing function should be used
Used with signature production / verification and (if the encryption mode is self::ENCRYPTION_OAEP) encryption and decryption. If $hash isn't supported, sha1 is used.
@access public
Parameters
string $hash
setMGFHash()
setMGFHash ($hash)
Determines which hashing function should be used for the mask generation function
The mask generation function is used by self::ENCRYPTION_OAEP and self::SIGNATURE_PSS and although it's best if Hash and MGFHash are set to the same thing this is not a requirement.
@access public
Parameters
string $hash
setPassword()
setPassword ($password = false)
Sets the password
Private keys can be encrypted with a password. To unset the password, pass in the empty string or false. Or rather, pass in $password such that empty($password) && !is_string($password) is true.
See also
self::createKey()
self::loadKey() @access public
Parameters
string $password
setPrivateKey()
setPrivateKey ($key = false, $type = false)
Defines the private key
If phpseclib guessed a private key was a public key and loaded it as such it might be desirable to force phpseclib to treat the key as a private key. This function will do that.
Do note that when a new key is loaded the index will be cleared.
Returns true on success, false on failure
See also
self::getPublicKey() @access public
Parameters
string $key optional
int $type optional
Returns
bool
setPrivateKeyFormat()
setPrivateKeyFormat ($format)
Determines the private key format
See also
self::createKey() @access public
Parameters
int $format
setPublicKey()
setPublicKey ($key = false, $type = false)
Defines the public key
Some private key formats define the public exponent and some don't. Those that don't define it are problematic when used in certain contexts. For example, in SSH-2, RSA authentication works by sending the public key along with a message signed by the private key to the server. The SSH-2 server looks the public key up in an index of public keys and if it's present then proceeds to verify the signature. Problem is, if your private key doesn't include the public exponent this won't work unless you manually add the public exponent. phpseclib tries to guess if the key being used is the public key but in the event that it guesses incorrectly you might still want to explicitly set the key as being public.
Do note that when a new key is loaded the index will be cleared.
Returns true on success, false on failure
See also
self::getPublicKey() @access public
Parameters
string $key optional
int $type optional
Returns
bool
Referenced by RSA\loadKey().
setPublicKeyFormat()
setPublicKeyFormat ($format)
Determines the public key format
See also
self::createKey() @access public
Parameters
int $format
setSaltLength()
setSaltLength ($sLen)
Determines the salt length
To quote from RFC3447#page-38:
Typical salt lengths in octets are hLen (the length of the output of the hash function Hash) and 0.
@access public
Parameters
int $sLen
setSignatureMode()
setSignatureMode ($mode)
Set Signature Mode
Valid values include self::SIGNATURE_PSS and self::SIGNATURE_PKCS1
@access public
Parameters
int $mode
sign()
sign ($message)
Create a signature
See also
self::verify() @access public
Parameters
string $message
Returns
string
verify()
verify ($message, $signature)
Verifies a signature
See also
self::sign() @access public
Parameters
string $message
string $signature
Returns
bool
Member Data Documentation
ASN1_BITSTRING
const ASN1_BITSTRING = 3
ASN1 Bit String
ASN1_INTEGER
const ASN1_INTEGER = 2
#- #+ @access private
See also
\phpseclib\Crypt\RSA::createKey() ASN1 Integer
ASN1_OBJECT
const ASN1_OBJECT = 6
ASN1 Object Identifier
ASN1_OCTETSTRING
const ASN1_OCTETSTRING = 4
ASN1 Octet String
ASN1_SEQUENCE
const ASN1_SEQUENCE = 48
ASN1 Sequence (with the constucted bit set)
Referenced by RSA\_parseKey().
ENCRYPTION_NONE
const ENCRYPTION_NONE = 3
Do not use any padding
Although this method is not recommended it can none-the-less sometimes be useful if you're trying to decrypt some legacy stuff, if you're trying to diagnose why an encrypted message isn't decrypting, etc.
Referenced by RSA\decrypt(), and RSA\encrypt().
ENCRYPTION_OAEP
const ENCRYPTION_OAEP = 1
#+ @access public
See also
self::encrypt()
self::decrypt() Use Optimal Asymmetric Encryption Padding (OAEP) for encryption / decryption.
Uses sha1 by default.
See also
self::setHash()
self::setMGFHash()
ENCRYPTION_PKCS1
const ENCRYPTION_PKCS1 = 2
Use PKCS#1 padding.
Although self::ENCRYPTION_OAEP offers more security, including PKCS#1 padding is necessary for purposes of backwards compatibility with protocols (like SSH-1) written before OAEP's introduction.
Referenced by RSA\decrypt(), and RSA\encrypt().
MODE_INTERNAL
const MODE_INTERNAL = 1
#- #+ @access private
See also
\phpseclib\Crypt\RSA::__construct() To use the pure-PHP implementation
MODE_OPENSSL
const MODE_OPENSSL = 2
To use the OpenSSL library
(if enabled; otherwise, the internal implementation will be used)
PRIVATE_FORMAT_OPENSSH
const PRIVATE_FORMAT_OPENSSH = 9
OpenSSH formatted private key
Referenced by RSA\_convertPrivateKey(), and RSA\_parseKey().
PRIVATE_FORMAT_PKCS1
const PRIVATE_FORMAT_PKCS1 = 0
#- #+ @access public
See also
\phpseclib\Crypt\RSA::createKey()
\phpseclib\Crypt\RSA::setPrivateKeyFormat() PKCS#1 formatted private key
Used by OpenSSH
Referenced by RSA\_parseKey(), and RSA\loadKey().
PRIVATE_FORMAT_PKCS8
const PRIVATE_FORMAT_PKCS8 = 8
PKCS#8 formatted private key
Referenced by RSA\_parseKey().
PRIVATE_FORMAT_PUTTY
const PRIVATE_FORMAT_PUTTY = 1
PuTTY formatted private key
Referenced by RSA\_convertPrivateKey(), and RSA\_parseKey().
PRIVATE_FORMAT_XML
const PRIVATE_FORMAT_XML = 2
XML formatted private key
Referenced by RSA\_convertPrivateKey(), and RSA\_parseKey().
PUBLIC_FORMAT_OPENSSH
const PUBLIC_FORMAT_OPENSSH = 6
OpenSSH formatted public key
Place in $HOME/.ssh/authorized_keys
Referenced by RSA\_convertPublicKey(), RSA\_parseKey(), and RSA\loadKey().
PUBLIC_FORMAT_PKCS1
const PUBLIC_FORMAT_PKCS1 = 4
PKCS#1 formatted public key (raw)
Used by File/X509.php
Has the following header:
--—BEGIN RSA PUBLIC KEY--—
Analogous to ssh-keygen's pem format (as specified by -m)
Referenced by X509\_formatSubjectPublicKey(), RSA\_parseKey(), and X509\computeKeyIdentifier().
PUBLIC_FORMAT_PKCS8
const PUBLIC_FORMAT_PKCS8 = 7
PKCS#1 formatted public key (encapsulated)
Used by PHP's openssl_public_encrypt() and openssl's rsautl (when -pubin is set)
Has the following header:
--—BEGIN PUBLIC KEY--—
Analogous to ssh-keygen's pkcs8 format (as specified by -m). Although PKCS8 is specific to private keys it's basically creating a DER-encoded wrapper for keys. This just extends that same concept to public keys (much like ssh-keygen)
PUBLIC_FORMAT_RAW
const PUBLIC_FORMAT_RAW = 3
#- #+ @access public
See also
\phpseclib\Crypt\RSA::createKey()
\phpseclib\Crypt\RSA::setPublicKeyFormat() Raw public key
An array containing two \phpseclib\Math\BigInteger objects.
The exponent can be indexed with any of the following:
0, e, exponent, publicExponent
The modulus can be indexed with any of the following:
1, n, modulo, modulus
Referenced by RSA\_convertPublicKey(), RSA\_parseKey(), SSH2\_privatekey_login(), and RSA\loadKey().
PUBLIC_FORMAT_XML
const PUBLIC_FORMAT_XML = 5
XML formatted public key
Referenced by RSA\_convertPublicKey(), and RSA\_parseKey().
SIGNATURE_PKCS1
const SIGNATURE_PKCS1 = 2
Use the PKCS#1 scheme by default.
Although self::SIGNATURE_PSS offers more security, including PKCS#1 signing is necessary for purposes of backwards compatibility with protocols (like SSH-2) written before PSS's introduction.
Referenced by SSH2\_privatekey_login(), X509\_sign(), X509\_validateSignature(), RSA\sign(), and RSA\verify().
SIGNATURE_PSS
const SIGNATURE_PSS = 1
#- #+ @access public
See also
self::sign()
self::verify()
self::setHash() Use the Probabilistic Signature Scheme for signing
Uses sha1 by default.
See also
self::setSaltLength()
self::setMGFHash()
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_db/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA.php