Utopszkij_db: UriInterface Interface Reference
UriInterface Interface Reference
Public Member Functions
getScheme ()
getAuthority ()
getUserInfo ()
getHost ()
getPort ()
getPath ()
getQuery ()
getFragment ()
withScheme ($scheme)
withUserInfo ($user, $password=null)
withHost ($host)
withPort ($port)
withPath ($path)
withQuery ($query)
withFragment ($fragment)
__toString ()
Detailed Description
Value object representing a URI.
This interface is meant to represent URIs according to RFC 3986 and to provide methods for most common operations. Additional functionality for working with URIs can be provided on top of the interface or externally. Its primary use is for HTTP requests, but may also be used in other contexts.
Instances of this interface are considered immutable; all methods that might change state MUST be implemented such that they retain the internal state of the current instance and return an instance that contains the changed state.
Typically the Host header will be also be present in the request message. For server-side requests, the scheme will typically be discoverable in the server parameters.
(the URI specification)
Member Function Documentation
__toString()
__toString ()
Return the string representation as a URI reference.
Depending on which components of the URI are present, the resulting string is either a full URI or relative reference according to RFC 3986, Section 4.1. The method concatenates the various components of the URI, using the appropriate delimiters:
If a scheme is present, it MUST be suffixed by ":".
If an authority is present, it MUST be prefixed by "//".
The path can be concatenated without delimiters. But there are two cases where the path has to be adjusted to make the URI reference valid as PHP does not allow to throw an exception in __toString():
If the path is rootless and an authority is present, the path MUST be prefixed by "/".
If the path is starting with more than one "/" and no authority is present, the starting slashes MUST be reduced to one.
If a query is present, it MUST be prefixed by "?".
If a fragment is present, it MUST be prefixed by "#".
See also
http://tools.ietf.org/html/rfc3986#section-4.1
Returns
string
Implemented in Uri.
getAuthority()
getAuthority ()
Retrieve the authority component of the URI.
If no authority information is present, this method MUST return an empty string.
The authority syntax of the URI is:
[user-info@]host[:port]
If the port component is not set or is the standard port for the current scheme, it SHOULD NOT be included.
See also
https://tools.ietf.org/html/rfc3986#section-3.2
Returns
string The URI authority, in "[user-info@]host[:port]" format.
Implemented in Uri.
Referenced by Uri\isAbsolutePathReference(), Uri\isNetworkPathReference(), Uri\isRelativePathReference(), Uri\isSameDocumentReference(), and UriResolver\resolve().
getFragment()
getFragment ()
Retrieve the fragment component of the URI.
If no fragment is present, this method MUST return an empty string.
The leading "#" character is not part of the fragment and MUST NOT be added.
The value returned MUST be percent-encoded, but MUST NOT double-encode any characters. To determine what characters to encode, please refer to RFC 3986, Sections 2 and 3.5.
See also
https://tools.ietf.org/html/rfc3986#section-2
https://tools.ietf.org/html/rfc3986#section-3.5
Returns
string The URI fragment.
Implemented in Uri.
Referenced by UriResolver\resolve().
getHost()
getHost ()
Retrieve the host component of the URI.
If no host is present, this method MUST return an empty string.
The value returned MUST be normalized to lowercase, per RFC 3986 Section 3.2.2.
See also
http://tools.ietf.org/html/rfc3986#section-3.2.2
Returns
string The URI host.
Implemented in Uri.
Referenced by Utils\idnUriConvert(), UriComparator\isCrossOrigin(), and UriNormalizer\normalize().
getPath()
getPath ()
Retrieve the path component of the URI.
The path can either be empty or absolute (starting with a slash) or rootless (not starting with a slash). Implementations MUST support all three syntaxes.
Normally, the empty path "" and absolute path "/" are considered equal as defined in RFC 7230 Section 2.7.3. But this method MUST NOT automatically do this normalization because in contexts with a trimmed base path, e.g. the front controller, this difference becomes significant. It's the task of the user to handle both "" and "/".
The value returned MUST be percent-encoded, but MUST NOT double-encode any characters. To determine what characters to encode, please refer to RFC 3986, Sections 2 and 3.3.
As an example, if the value should include a slash ("/") not intended as delimiter between path segments, that value MUST be passed in encoded form (e.g., "%2F") to the instance.
See also
https://tools.ietf.org/html/rfc3986#section-2
https://tools.ietf.org/html/rfc3986#section-3.3
Returns
string The URI path.
Implemented in Uri.
Referenced by Uri\isAbsolutePathReference(), Uri\isRelativePathReference(), Uri\isSameDocumentReference(), UriNormalizer\normalize(), and UriResolver\resolve().
getPort()
getPort ()
Retrieve the port component of the URI.
If a port is present, and it is non-standard for the current scheme, this method MUST return it as an integer. If the port is the standard port used with the current scheme, this method SHOULD return null.
If no port is present, and no scheme is present, this method MUST return a null value.
If no port is present, but a scheme is present, this method MAY return the standard port for that scheme, but SHOULD return null.
Returns
null|int The URI port.
Implemented in Uri.
Referenced by Uri\isDefaultPort(), and UriNormalizer\normalize().
getQuery()
getQuery ()
Retrieve the query string of the URI.
If no query string is present, this method MUST return an empty string.
The leading "?" character is not part of the query and MUST NOT be added.
The value returned MUST be percent-encoded, but MUST NOT double-encode any characters. To determine what characters to encode, please refer to RFC 3986, Sections 2 and 3.4.
As an example, if a value in a key/value pair of the query string should include an ampersand ("&") not intended as a delimiter between values, that value MUST be passed in encoded form (e.g., "%26") to the instance.
See also
https://tools.ietf.org/html/rfc3986#section-2
https://tools.ietf.org/html/rfc3986#section-3.4
Returns
string The URI query string.
Implemented in Uri.
Referenced by Uri\isSameDocumentReference(), UriNormalizer\normalize(), and UriResolver\resolve().
getScheme()
getScheme ()
Retrieve the scheme component of the URI.
If no scheme is present, this method MUST return an empty string.
The value returned MUST be normalized to lowercase, per RFC 3986 Section 3.1.
The trailing ":" character is not part of the scheme and MUST NOT be added.
See also
https://tools.ietf.org/html/rfc3986#section-3.1
Returns
string The URI scheme.
Implemented in Uri.
Referenced by Uri\isAbsolute(), Uri\isAbsolutePathReference(), UriComparator\isCrossOrigin(), Uri\isDefaultPort(), Uri\isNetworkPathReference(), Uri\isRelativePathReference(), Uri\isSameDocumentReference(), UriNormalizer\normalize(), and UriResolver\resolve().
getUserInfo()
getUserInfo ()
Retrieve the user information component of the URI.
If no user information is present, this method MUST return an empty string.
If a user is present in the URI, this will return that value; additionally, if the password is also present, it will be appended to the user value, with a colon (":") separating the values.
The trailing "@" character is not part of the user information and MUST NOT be added.
Returns
string The URI user information, in "username[:password]" format.
Implemented in Uri.
withFragment()
withFragment ($fragment)
Return an instance with the specified URI fragment.
This method MUST retain the state of the current instance, and return an instance that contains the specified URI fragment.
Users can provide both encoded and decoded fragment characters. Implementations ensure the correct encoding as outlined in getFragment().
An empty fragment value is equivalent to removing the fragment.
Parameters
string $fragment The fragment to use with the new instance.
Returns
static A new instance with the specified fragment.
Implemented in Uri.
withHost()
withHost ($host)
Return an instance with the specified host.
This method MUST retain the state of the current instance, and return an instance that contains the specified host.
An empty host value is equivalent to removing the host.
Parameters
string $host The hostname to use with the new instance.
Returns
static A new instance with the specified host.
Exceptions
InvalidArgumentException for invalid hostnames.
Implemented in Uri.
Referenced by Utils\idnUriConvert(), and UriNormalizer\normalize().
withPath()
withPath ($path)
Return an instance with the specified path.
This method MUST retain the state of the current instance, and return an instance that contains the specified path.
The path can either be empty or absolute (starting with a slash) or rootless (not starting with a slash). Implementations MUST support all three syntaxes.
If the path is intended to be domain-relative rather than path relative then it must begin with a slash ("/"). Paths not starting with a slash ("/") are assumed to be relative to some base path known to the application or consumer.
Users can provide both encoded and decoded path characters. Implementations ensure the correct encoding as outlined in getPath().
Parameters
string $path The path to use with the new instance.
Returns
static A new instance with the specified path.
Exceptions
InvalidArgumentException for invalid paths.
Implemented in Uri.
Referenced by UriNormalizer\normalize(), and UriResolver\resolve().
withPort()
withPort ($port)
Return an instance with the specified port.
This method MUST retain the state of the current instance, and return an instance that contains the specified port.
Implementations MUST raise an exception for ports outside the established TCP and UDP port ranges.
A null value provided for the port is equivalent to removing the port information.
Parameters
null | int $port The port to use with the new instance; a null value removes the port information.
Returns
static A new instance with the specified port.
Exceptions
InvalidArgumentException for invalid ports.
Implemented in Uri.
Referenced by UriNormalizer\normalize().
withQuery()
withQuery ($query)
Return an instance with the specified query string.
This method MUST retain the state of the current instance, and return an instance that contains the specified query string.
Users can provide both encoded and decoded query characters. Implementations ensure the correct encoding as outlined in getQuery().
An empty query string value is equivalent to removing the query string.
Parameters
string $query The query string to use with the new instance.
Returns
static A new instance with the specified query string.
Exceptions
InvalidArgumentException for invalid query strings.
Implemented in Uri.
Referenced by UriNormalizer\normalize(), Uri\withoutQueryValue(), Uri\withQueryValue(), and Uri\withQueryValues().
withScheme()
withScheme ($scheme)
Return an instance with the specified scheme.
This method MUST retain the state of the current instance, and return an instance that contains the specified scheme.
Implementations MUST support the schemes "http" and "https" case insensitively, and MAY accommodate other schemes if required.
An empty scheme is equivalent to removing the scheme.
Parameters
string $scheme The scheme to use with the new instance.
Returns
static A new instance with the specified scheme.
Exceptions
InvalidArgumentException for invalid or unsupported schemes.
Implemented in Uri.
withUserInfo()
withUserInfo ($user, $password = null)
Return an instance with the specified user information.
This method MUST retain the state of the current instance, and return an instance that contains the specified user information.
Password is optional, but the user information MUST include the user; an empty string for the user is equivalent to removing user information.
Parameters
string $user The user name to use for authority.
null | string $password The password associated with $user.
Returns
static A new instance with the specified user information.
Implemented in Uri.
The documentation for this interface was generated from the following file:
/var/www/html/utopszkij_db/vendor/psr/http-message/src/UriInterface.php