Utopszkij_db: MessageInterface Interface Reference
MessageInterface Interface Reference
Public Member Functions
getProtocolVersion ()
withProtocolVersion ($version)
getHeaders ()
hasHeader ($name)
getHeader ($name)
getHeaderLine ($name)
withHeader ($name, $value)
withAddedHeader ($name, $value)
withoutHeader ($name)
getBody ()
withBody (StreamInterface $body)
Detailed Description
HTTP messages consist of requests from a client to a server and responses from a server to a client. This interface defines the methods common to each.
Messages are considered immutable; all methods that might change state MUST be implemented such that they retain the internal state of the current message and return an instance that contains the changed state.
http://www.ietf.org/rfc/rfc7231.txt
Member Function Documentation
getBody()
getBody ()
Gets the body of the message.
Returns
StreamInterface Returns the body as a stream.
Referenced by StreamHandler\__invoke(), Message\bodySummary(), Utils\modifyRequest(), Message\rewindBody(), and Message\toString().
getHeader()
getHeader ($name)
Retrieves a message header value by the given case-insensitive name.
This method returns an array of all the header values of the given case-insensitive header name.
If the header does not appear in the message, this method MUST return an empty array.
Parameters
string $name Case-insensitive header field name.
Returns
string[] An array of string values as provided for the given header. If the header does not appear in the message, this method MUST return an empty array.
Referenced by CookieJar\extractCookies().
getHeaderLine()
getHeaderLine ($name)
Retrieves a comma-separated string of the values for a single header.
This method returns all of the header values of the given case-insensitive header name as a string concatenated together using a comma.
NOTE: Not all header values may be appropriately represented using comma concatenation. For such headers, use getHeader() instead and supply your own delimiter when concatenating.
If the header does not appear in the message, this method MUST return an empty string.
Parameters
string $name Case-insensitive header field name.
Returns
string A string of values as provided for the given header concatenated together using a comma. If the header does not appear in the message, this method MUST return an empty string.
getHeaders()
getHeaders ()
Retrieves all message header values.
The keys represent the header name as it will be sent over the wire, and each value is an array of strings associated with the header.
// Represent the headers as a string
foreach ($message->getHeaders() as $name => $values) {
    echo $name . ": " . implode(", ", $values);
}
// Emit headers iteratively:
foreach ($message->getHeaders() as $name => $values) {
    foreach ($values as $value) {
        header(sprintf('%s: %s', $name, $value), false);
    }
}
While header names are not case-sensitive, getHeaders() will preserve the exact case in which headers were originally specified.
Returns
string[][] Returns an associative array of the message's headers. Each key MUST be a header name, and each value MUST be an array of strings for that header.
Referenced by Utils\modifyRequest(), and Message\toString().
getProtocolVersion()
getProtocolVersion ()
Retrieves the HTTP protocol version as a string.
The string MUST contain only the HTTP version number (e.g., "1.1", "1.0").
Returns
string HTTP protocol version.
Referenced by Utils\modifyRequest(), and Message\toString().
hasHeader()
hasHeader ($name)
Checks if a header exists by the given case-insensitive name.
Parameters
string $name Case-insensitive header field name.
Returns
bool Returns true if any header names match the given header name using a case-insensitive string comparison. Returns false if no matching header name is found in the message.
Referenced by RedirectMiddleware\checkRedirect(), Client\sendAsync(), and Message\toString().
withAddedHeader()
withAddedHeader ($name, $value)
Return an instance with the specified header appended with the given value.
Existing values for the specified header will be maintained. The new value(s) will be appended to the existing list. If the header did not exist previously, it will be added.
This method MUST be implemented in such a way as to retain the immutability of the message, and MUST return an instance that has the new header and/or value.
Parameters
string $name Case-insensitive header field name to add.
string | string[] $value Header value(s).
Returns
static
Exceptions
InvalidArgumentException for invalid header names or values.
withBody()
withBody (StreamInterface $body)
Return an instance with the specified message body.
The body MUST be a StreamInterface object.
This method MUST be implemented in such a way as to retain the immutability of the message, and MUST return a new instance that has the new body stream.
Parameters
StreamInterface $body Body.
Returns
static
Exceptions
InvalidArgumentException When the body is not valid.
withHeader()
withHeader ($name, $value)
Return an instance with the provided value replacing the specified header.
While header names are case-insensitive, the casing of the header will be preserved by this function, and returned from getHeaders().
This method MUST be implemented in such a way as to retain the immutability of the message, and MUST return an instance that has the new and/or updated header and value.
Parameters
string $name Case-insensitive header field name.
string | string[] $value Header value(s).
Returns
static
Exceptions
InvalidArgumentException for invalid header names or values.
Referenced by StreamHandler\__invoke(), and CookieJar\withCookieHeader().
withoutHeader()
withoutHeader ($name)
Return an instance without the specified header.
Header resolution MUST be done without case-sensitivity.
This method MUST be implemented in such a way as to retain the immutability of the message, and MUST return an instance that removes the named header.
Parameters
string $name Case-insensitive header field name to remove.
Returns
static
Referenced by StreamHandler\__invoke().
withProtocolVersion()
withProtocolVersion ($version)
Return an instance with the specified HTTP protocol version.
The version string MUST contain only the HTTP version number (e.g., "1.1", "1.0").
This method MUST be implemented in such a way as to retain the immutability of the message, and MUST return an instance that has the new protocol version.
Parameters
string $version HTTP protocol version
Returns
static
The documentation for this interface was generated from the following file:
/var/www/html/utopszkij_db/vendor/psr/http-message/src/MessageInterface.php