Utopszkij_db: RequestInterface Interface Reference
RequestInterface Interface Reference
Public Member Functions
getRequestTarget ()
withRequestTarget ($requestTarget)
getMethod ()
withMethod ($method)
getUri ()
withUri (UriInterface $uri, $preserveHost=false)
Public Member Functions inherited from MessageInterface
getProtocolVersion ()
withProtocolVersion ($version)
getHeaders ()
hasHeader ($name)
getHeader ($name)
getHeaderLine ($name)
withHeader ($name, $value)
withAddedHeader ($name, $value)
withoutHeader ($name)
getBody ()
withBody (StreamInterface $body)
Detailed Description
Representation of an outgoing, client-side request.
Per the HTTP specification, this interface includes properties for each of the following:
Protocol version
HTTP method
URI
Headers
Message body
During construction, implementations MUST attempt to set the Host header from a provided URI if no Host header is provided.
Requests are considered immutable; all methods that might change state MUST be implemented such that they retain the internal state of the current message and return an instance that contains the changed state.
Member Function Documentation
getMethod()
getMethod ()
Retrieves the HTTP method of the request.
Returns
string Returns the request method.
Implemented in Request.
Referenced by Utils\modifyRequest().
getRequestTarget()
getRequestTarget ()
Retrieves the message's request target.
Retrieves the message's request-target either as it will appear (for clients), as it appeared at request (for servers), or as it was specified for the instance (see withRequestTarget()).
In most cases, this will be the origin-form of the composed URI, unless a value was provided to the concrete implementation (see withRequestTarget() below).
If no URI is available, and no request-target has been specifically provided, this method MUST return the string "/".
Returns
string
Implemented in Request.
getUri()
getUri ()
Retrieves the URI instance.
This method MUST return a UriInterface instance.
UriInterface Returns a UriInterface instance representing the URI of the request.
Implemented in Request.
Referenced by RedirectMiddleware\checkRedirect(), CookieJar\extractCookies(), Utils\modifyRequest(), Client\sendAsync(), and CookieJar\withCookieHeader().
withMethod()
withMethod ($method)
Return an instance with the provided HTTP method.
While HTTP method names are typically all uppercase characters, HTTP method names are case-sensitive and thus implementations SHOULD NOT modify the given string.
This method MUST be implemented in such a way as to retain the immutability of the message, and MUST return an instance that has the changed request method.
Parameters
string $method Case-sensitive method.
Returns
static
Exceptions
InvalidArgumentException for invalid HTTP methods.
Implemented in Request.
withRequestTarget()
withRequestTarget ($requestTarget)
Return an instance with the specific request-target.
If the request needs a non-origin-form request-target — e.g., for specifying an absolute-form, authority-form, or asterisk-form — this method may be used to create an instance with the specified request-target, verbatim.
This method MUST be implemented in such a way as to retain the immutability of the message, and MUST return an instance that has the changed request target.
(for the various request-target forms allowed in request messages) mixed $requestTarget static
Implemented in Request.
withUri()
withUri (UriInterface $uri, $preserveHost = false)
Returns an instance with the provided URI.
This method MUST update the Host header of the returned request by default if the URI contains a host component. If the URI does not contain a host component, any pre-existing Host header MUST be carried over to the returned request.
You can opt-in to preserving the original state of the Host header by setting $preserveHost to true. When $preserveHost is set to true, this method interacts with the Host header in the following ways:
If the Host header is missing or empty, and the new URI contains a host component, this method MUST update the Host header in the returned request.
If the Host header is missing or empty, and the new URI does not contain a host component, this method MUST NOT update the Host header in the returned request.
If a Host header is present and non-empty, this method MUST NOT update the Host header in the returned request.
This method MUST be implemented in such a way as to retain the immutability of the message, and MUST return an instance that has the new UriInterface instance.
UriInterface $uri New request URI to use. bool $preserveHost Preserve the original state of the Host header. static
Implemented in Request.
Referenced by Client\sendAsync().
The documentation for this interface was generated from the following file:
/var/www/html/utopszkij_db/vendor/psr/http-message/src/RequestInterface.php