Utopszkij_db: PromiseInterface Interface Reference
PromiseInterface Interface Reference
Public Member Functions
then (callable $onFulfilled=null, callable $onRejected=null)
otherwise (callable $onRejected)
getState ()
resolve ($value)
reject ($reason)
cancel ()
wait ($unwrap=true)
Public Attributes
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'
Detailed Description
A promise represents the eventual result of an asynchronous operation.
The primary way of interacting with a promise is through its then method, which registers callbacks to receive either a promise’s eventual value or the reason why the promise cannot be fulfilled.
https://promisesaplus.com/
Member Function Documentation
cancel()
cancel ()
Cancels the promise if possible.
https://github.com/promises-aplus/cancellation-spec/issues/7
Implemented in Coroutine, FulfilledPromise, Promise, and RejectedPromise.
getState()
getState ()
Get the state of the promise ("pending", "rejected", or "fulfilled").
The three states can be checked against the constants defined on PromiseInterface: PENDING, FULFILLED, and REJECTED.
Returns
string
Implemented in Coroutine, FulfilledPromise, Promise, and RejectedPromise.
Referenced by Is\fulfilled(), Is\pending(), Is\rejected(), and Is\settled().
otherwise()
otherwise (callable $onRejected)
Appends a rejection handler callback to the promise, and returns a new promise resolving to the return value of the callback if it is called, or to its original fulfillment value if the promise is instead fulfilled.
Parameters
callable $onRejected Invoked when the promise is rejected.
Returns
PromiseInterface
Implemented in Coroutine, FulfilledPromise, Promise, and RejectedPromise.
reject()
reject ($reason)
Reject the promise with the given reason.
Parameters
mixed $reason
Exceptions
RuntimeException if the promise is already resolved.
Implemented in Coroutine, FulfilledPromise, Promise, and RejectedPromise.
Referenced by Each\ofLimitAll().
resolve()
resolve ($value)
Resolve the promise with the given value.
Parameters
mixed $value
Exceptions
RuntimeException if the promise is already resolved.
Implemented in Coroutine, FulfilledPromise, Promise, and RejectedPromise.
Referenced by Utils\some().
then()
then (callable $onFulfilled = null, callable $onRejected = null)
Appends fulfillment and rejection handlers to the promise, and returns a new promise resolving to the return value of the called handler.
Parameters
callable $onFulfilled Invoked when the promise fulfills.
callable $onRejected Invoked when the promise is rejected.
Returns
PromiseInterface
Implemented in Coroutine, FulfilledPromise, Promise, and RejectedPromise.
wait()
wait ($unwrap = true)
Waits until the promise completes if possible.
Pass $unwrap as true to unwrap the result of the promise, either returning the resolved value or throwing the rejected exception.
If the promise cannot be waited on, then the promise will be rejected.
Parameters
bool $unwrap
Returns
mixed
Exceptions
LogicException if the promise has no wait function or if the promise does not settle after waiting.
Implemented in Coroutine, and Promise.
Referenced by Utils\inspect().
The documentation for this interface was generated from the following file:
/var/www/html/utopszkij_db/vendor/guzzlehttp/promises/src/PromiseInterface.php